import { Question } from './index';

export const estudoDoMeioQuestions: Question[] = [
  // ============================================
  // ESTUDO DO MEIO - GRADE 1
  // ============================================
  {
    id: 'em-g1-001',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Natureza',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos estados da matéria existem?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'Existem 3 estados: sólido, líquido e gasoso.',
  },
  {
    id: 'em-g1-002',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Animais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual animal faz "mu"?',
    options: ['Cão', 'Gato', 'Vaca', 'Galinha'],
    correctAnswer: 'Vaca',
    explanation: 'A vaca faz "mu".',
  },
  {
    id: 'em-g1-003',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Plantas',
    difficulty: 'easy',
    type: 'true_false',
    question: 'As plantas precisam de sol para crescer.',
    correctAnswer: 'true',
    explanation: 'As plantas fazem fotossíntese com a luz do sol.',
  },
  {
    id: 'em-g1-004',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Clima',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Em que estação do ano faz mais calor?',
    options: ['Inverno', 'Primavera', 'Veraão', 'Outono'],
    correctAnswer: 'Veraão',
    explanation: 'No verão as temperaturas são mais altas.',
  },
  {
    id: 'em-g1-005',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Corpo Humano',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos sentidos temos?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'Temoss: visão, audição, olfato, paladar e tato.',
  },
  {
    id: 'em-g1-006',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Natureza',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é a estrela mais próxima da Terra?',
    options: ['Lua', 'Marte', 'Sol', 'Estrela Polar'],
    correctAnswer: 'Sol',
    explanation: 'O Sol é a estrela mais próxima da Terra.',
  },
  {
    id: 'em-g1-007',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Animais',
    difficulty: 'easy',
    type: 'true_false',
    question: 'O peixe vive na água.',
    correctAnswer: 'true',
    explanation: 'Os peixes são animais aquáticos.',
  },
  {
    id: 'em-g1-008',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Materiais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'De que é feita a água?',
    options: ['Oxigénio e carbono', 'Hidrogénio e oxigénio', 'Nitrogénio e oxigénio', 'Hidrogénio e carbono'],
    correctAnswer: 'Hidrogénio e oxigénio',
    explanation: 'A água é formada por hidrogénio e oxigénio (H₂O).',
  },
  {
    id: 'em-g1-009',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Alimentos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual grupo alimentar nos dá energia rápida?',
    options: ['Proteínas', 'Hidratos de carbono', 'Vitaminas', 'Minerais'],
    correctAnswer: 'Hidratos de carbono',
    explanation: 'Os hidratos de carbono são a principal fonte de energia.',
  },
  {
    id: 'em-g1-010',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Sociedade',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Onde se compra pão?',
    options: ['Escola', 'Padaria', 'Farmácia', 'Biblioteca'],
    correctAnswer: 'Padaria',
    explanation: 'O pão é comprado na padaria.',
  },
  {
    id: 'em-g1-011',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Corpo Humano',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual órgão usamos para ver?',
    options: ['Ouvidos', 'Olhos', 'Nariz', 'Boca'],
    correctAnswer: 'Olhos',
    explanation: 'Os olhos são os órgãos da visão.',
  },
  {
    id: 'em-g1-012',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Animais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual animal dá leite?',
    options: ['Peixe', 'Pássaro', 'Vaca', 'Réptil'],
    correctAnswer: 'Vaca',
    explanation: 'A vaca é um mamífero que dá leite.',
  },
  {
    id: 'em-g1-013',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Plantas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual parte da planta faz fotossíntese?',
    options: ['Raiz', 'Caule', 'Folha', 'Flor'],
    correctAnswer: 'Folha',
    explanation: 'As folhas são responsáveis pela fotossíntese.',
  },
  {
    id: 'em-g1-014',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Materiais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'De que material é feita a janela?',
    options: ['Madeira', 'Vidro', 'Plástico', 'Metal'],
    correctAnswer: 'Vidro',
    explanation: 'As janelas são feitas de vidro.',
  },
  {
    id: 'em-g1-015',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Alimentos',
    difficulty: 'easy',
    type: 'true_false',
    question: 'As frutas são saudáveis.',
    correctAnswer: 'true',
    explanation: 'As frutas são ricas em vitaminas e fibras.',
  },
  {
    id: 'em-g1-016',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Sociedade',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Onde vivemos?',
    options: ['Na água', 'No céu', 'Em casa', 'Na floresta'],
    correctAnswer: 'Em casa',
    explanation: 'As pessoas vivem em casas ou apartamentos.',
  },
  {
    id: 'em-g1-017',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Clima',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Em que estação do ano há mais neve?',
    options: ['Verão', 'Primavera', 'Inverno', 'Outono'],
    correctAnswer: 'Inverno',
    explanation: 'No inverno as temperaturas são mais baixas e pode nevar.',
  },
  {
    id: 'em-g1-018',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Animais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual animal voa?',
    options: ['Peixe', 'Cão', 'Águia', 'Tartaruga'],
    correctAnswer: 'Águia',
    explanation: 'A águia é uma ave que voa.',
  },
  {
    id: 'em-g1-019',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Corpo Humano',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas patas temos?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'Os seres humanos têm 2 patas (pernas).',
  },
  {
    id: 'em-g1-020',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Natureza',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'De onde vem a chuva?',
    options: ['Das árvores', 'Das nuvens', 'Do solo', 'Do mar'],
    correctAnswer: 'Das nuvens',
    explanation: 'A chuva vem das nuvens quando a água condensa.',
  },

  // ============================================
  // ESTUDO DO MEIO - GRADE 2
  // ============================================
  {
    id: 'em-g2-001',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o ciclo da água?',
    options: ['Evaporação, condensação, precipitação, escoamento', 'Fusão, ebulição, sublimação', 'Fusão, solidificação, condensação', 'Evaporação, sublimação, precipitação'],
    correctAnswer: 'Evaporação, condensação, precipitação, escoamento',
    explanation: 'O ciclo da água inclui evaporação, condensação, precipitação e escoamento.',
  },
  {
    id: 'em-g2-002',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Animais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que classe de animais inclui as rãs?',
    options: ['Mamíferos', 'Répteis', 'Anfíbios', 'Aves'],
    correctAnswer: 'Anfíbios',
    explanation: 'As rãs são anfíbios, vivem na água e na terra.',
  },
  {
    id: 'em-g2-003',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Plantas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual parte da planta absorve a água do solo?',
    options: ['Folhas', 'Caule', 'Raízes', 'Flores'],
    correctAnswer: 'Raízes',
    explanation: 'As raízes absorvem a água e os nutrientes do solo.',
  },
  {
    id: 'em-g2-004',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Corpo Humano',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual órgão bombeia o sangue?',
    options: ['Pulmões', 'Fígado', 'Coração', 'Cérebro'],
    correctAnswer: 'Coração',
    explanation: 'O coração é o órgão que bombeia o sangue.',
  },
  {
    id: 'em-g2-005',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Materiais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que material é melhor condutor de eletricidade?',
    options: ['Plástico', 'Madeira', 'Metal', 'Vidro'],
    correctAnswer: 'Metal',
    explanation: 'Os metais são bons condutores de eletricidade.',
  },
  {
    id: 'em-g2-006',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Clima',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que instrumento mede a temperatura?',
    options: ['Barómetro', 'Termómetro', 'Higrómetro', 'Anemómetro'],
    correctAnswer: 'Termómetro',
    explanation: 'O termómetro mede a temperatura.',
  },
  {
    id: 'em-g2-007',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Alimentos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que grupo alimentar ajuda a construir e reparar o corpo?',
    options: ['Hidratos de carbono', 'Gorduras', 'Proteínas', 'Vitaminas'],
    correctAnswer: 'Proteínas',
    explanation: 'As proteínas são essenciais para crescimento e reparação.',
  },
  {
    id: 'em-g2-008',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'true_false',
    question: 'O papel é feito de árvores.',
    correctAnswer: 'true',
    explanation: 'O papel é fabricado a partir de cellulose da madeira.',
  },
  {
    id: 'em-g2-009',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que tipo de rocha é formada por vulcões?',
    options: ['Sedimentar', 'Metamórfica', 'Ígnea', 'Calcária'],
    correctAnswer: 'Ígnea',
    explanation: 'As rochas ígneas são formadas pelo resfriamento de magma.',
  },
  {
    id: 'em-g2-010',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Corpo Humano',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos ossos tem o corpo humano adulto?',
    options: ['106', '206', '306', '406'],
    correctAnswer: '206',
    explanation: 'O corpo humano adulto tem 206 ossos.',
  },
  {
    id: 'em-g2-011',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Animais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que classe de animais põem ovos e tem penas?',
    options: ['Mamíferos', 'Répteis', 'Aves', 'Anfíbios'],
    correctAnswer: 'Aves',
    explanation: 'As aves põem ovos e têm penas.',
  },
  {
    id: 'em-g2-012',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Plantas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a função das flores numa planta?',
    options: ['Absorver água', 'Produzir alimento', 'Reprodução', 'Transportar seiva'],
    correctAnswer: 'Reprodução',
    explanation: 'As flores são responsáveis pela reprodução da planta.',
  },
  {
    id: 'em-g2-013',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'true_false',
    question: 'O Sol é uma estrela.',
    correctAnswer: 'true',
    explanation: 'O Sol é uma estrela de tipo espectral G.',
  },
  {
    id: 'em-g2-014',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Materiais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que material é um isolante térmico?',
    options: ['Metal', 'Cobre', 'Madeira', 'Alumínio'],
    correctAnswer: 'Madeira',
    explanation: 'A madeira é um mau condutor de calor, por isso é isolante.',
  },
  {
    id: 'em-g2-015',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Alimentos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'De onde vêm os ovos que comemos?',
    options: ['Vacas', 'Galinhas', 'Peixes', 'Coelhos'],
    correctAnswer: 'Galinhas',
    explanation: 'Os ovos que comemos vêm das galinhas.',
  },
  {
    id: 'em-g2-016',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quem nos ajuda a aprender na escola?',
    options: ['O médico', 'O professor', 'O bombeiro', 'O polícia'],
    correctAnswer: 'O professor',
    explanation: 'O professor é quem ensina na escola.',
  },
  {
    id: 'em-g2-017',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Corpo Humano',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual órgão usamos para ouvir?',
    options: ['Olhos', 'Nariz', 'Ouvidos', 'Boca'],
    correctAnswer: 'Ouvidos',
    explanation: 'Os ouvidos são os órgãos da audição.',
  },
  {
    id: 'em-g2-018',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Clima',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que acontece quando a temperatura da água atinge 100°C?',
    options: ['Congela', 'Evapora', 'Funde', 'Sublima'],
    correctAnswer: 'Evapora',
    explanation: 'A 100°C a água ferve e evapora.',
  },
  {
    id: 'em-g2-019',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Animais',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A baleia é um peixe.',
    correctAnswer: 'false',
    explanation: 'A baleia é um mamífero, não um peixe.',
  },
  {
    id: 'em-g2-020',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a camada protetora da Terra?',
    options: ['Litosfera', 'Atmosfera', 'Hidrosfera', 'Biosfera'],
    correctAnswer: 'Atmosfera',
    explanation: 'A atmosfera é a camada de gases que envolve a Terra.',
  },

  // ============================================
  // ESTUDO DO MEIO - GRADE 3
  // ============================================
  {
    id: 'em-g3-001',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Ecologia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é a fotossíntese?',
    options: ['Produção de energia pelo fogo', 'Produção de oxigénio pelas plantas', 'Decomposição da matéria', 'Absorção de água pelo solo'],
    correctAnswer: 'Produção de oxigénio pelas plantas',
    explanation: 'A fotossíntese é o processo pelo qual as plantas produzem oxigénio e energia.',
  },
  {
    id: 'em-g3-002',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Sistema Solar',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o maior planeta do sistema solar?',
    options: ['Terra', 'Marte', 'Júpiter', 'Saturno'],
    correctAnswer: 'Júpiter',
    explanation: 'Júpiter é o maior planeta do sistema solar.',
  },
  {
    id: 'em-g3-003',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Eletricidade',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'De onde vem a eletricidade que usamos em casa?',
    options: ['Da Lua', 'Do Sol', 'De usinas e barragens', 'Da chuva'],
    correctAnswer: 'De usinas e barragens',
    explanation: 'A eletricidade é produzida em usinas elétricas e barragens.',
  },
  {
    id: 'em-g3-004',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Geografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o maior oceano do mundo?',
    options: ['Atlântico', 'Índico', 'Pacífico', 'Ártico'],
    correctAnswer: 'Pacífico',
    explanation: 'O oceano Pacífico é o maior e mais profundo.',
  },
  {
    id: 'em-g3-005',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Alimentos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que são os aditivos alimentares?',
    options: ['Alimentos naturais', 'Substâncias adicionadas aos alimentos', 'Alimentos biológicos', 'Frutas secas'],
    correctAnswer: 'Substâncias adicionadas aos alimentos',
    explanation: 'Aditivos são substâncias adicionadas para conservar ou melhorar os alimentos.',
  },
  {
    id: 'em-g3-006',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Corpo Humano',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a função dos pulmões?',
    options: ['Bombear sangue', 'Filtrar o sangue', 'Realizar trocas gasosas', 'Digirir os alimentos'],
    correctAnswer: 'Realizar trocas gasosas',
    explanation: 'Os pulmões permitem a entrada de oxigénio e saída de CO₂.',
  },
  {
    id: 'em-g3-007',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Recursos Naturais',
    difficulty: 'normal',
    type: 'true_false',
    question: 'O petróleo é um recurso natural renovável.',
    correctAnswer: 'false',
    explanation: 'O petróleo é um recurso não renovável, demora milhões de anos a formar-se.',
  },
  {
    id: 'em-g3-008',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Clima',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que gases formam a atmosfera terrestre?',
    options: ['Oxigénio e azoto', 'Hidrogénio e hélio', 'Dióxido de carbono e oxigénio', 'Azoto e hélio'],
    correctAnswer: 'Oxigénio e azoto',
    explanation: 'A atmosfera é composta principalmente por azoto (78%) e oxigénio (21%).',
  },
  {
    id: 'em-g3-009',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é o património cultural?',
    options: ['Apenas edifícios antigos', 'Bens materiais e imateriais de uma cultura', 'Apenas monumentos', 'Apenas tradições'],
    correctAnswer: 'Bens materiais e imateriais de uma cultura',
    explanation: 'O património cultural inclui bens físicos e tradições de um povo.',
  },
  {
    id: 'em-g3-010',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que seres vivos produzem o seu próprio alimento?',
    options: ['Animais', 'Plantas', 'Fungos', 'Bactérias'],
    correctAnswer: 'Plantas',
    explanation: 'As plantas são seres autotróficos, produzem o seu próprio alimento.',
  },
  {
    id: 'em-g3-011',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Sistema Solar',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual planeta é conhecido como "Planeta Vermelho"?',
    options: ['Vénus', 'Marte', 'Júpiter', 'Saturno'],
    correctAnswer: 'Marte',
    explanation: 'Marte é conhecido como Planeta Vermelho devido ao óxido de ferro na sua superfície.',
  },
  {
    id: 'em-g3-012',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Ecologia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é um ecossistema?',
    options: ['Apenas os animais', 'A interação entre seres vivos e o ambiente', 'Apenas as plantas', 'Apenas o solo'],
    correctAnswer: 'A interação entre seres vivos e o ambiente',
    explanation: 'Um ecossistema é o conjunto de seres vivos e o seu ambiente.',
  },
  {
    id: 'em-g3-013',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Eletricidade',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A eletricidade pode causar choques elétricos.',
    correctAnswer: 'true',
    explanation: 'A eletricidade pode ser perigosa e causar choques.',
  },
  {
    id: 'em-g3-014',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Geografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos planetas tem o sistema solar?',
    options: ['7', '8', '9', '10'],
    correctAnswer: '8',
    explanation: 'O sistema solar tem 8 planetas.',
  },
  {
    id: 'em-g3-015',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Corpo Humano',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a função do fígado?',
    options: ['Bombear sangue', 'Filtrar toxinas', 'Produzir insulina', 'Armazenar oxigénio'],
    correctAnswer: 'Filtrar toxinas',
    explanation: 'O fígado filtra toxinas do sangue e ajuda na digestão.',
  },
  {
    id: 'em-g3-016',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Recursos Naturais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que energia é produzida pelas barragens?',
    options: ['Solar', 'Eólica', 'Hidroeléctrica', 'Nuclear'],
    correctAnswer: 'Hidroeléctrica',
    explanation: 'As barragens produzem energia hidroeléctrica a partir da água.',
  },
  {
    id: 'em-g3-017',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Alimentos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que vitamina obtemos do sol?',
    options: ['Vitamina A', 'Vitamina B', 'Vitamina C', 'Vitamina D'],
    correctAnswer: 'Vitamina D',
    explanation: 'A vitamina D é produzida pela pele quando exposta ao sol.',
  },
  {
    id: 'em-g3-018',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que seres decomponem a matéria orgânica?',
    options: ['Animais', 'Plantas', 'Fungos e bactérias', 'Insetos apenas'],
    correctAnswer: 'Fungos e bactérias',
    explanation: 'Os fungos e bactérias são decompositores da matéria orgânica.',
  },
  {
    id: 'em-g3-019',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'true_false',
    question: 'Portugal está na Europa.',
    correctAnswer: 'true',
    explanation: 'Portugal é um país europeu, localizado na Península Ibérica.',
  },
  {
    id: 'em-g3-020',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Clima',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que provoca os terremotos?',
    options: ['Chuva forte', 'Movimento das placas tectónicas', 'Vulcões', 'Vento'],
    correctAnswer: 'Movimento das placas tectónicas',
    explanation: 'Os terremotos são causados pelo movimento das placas tectónicas.',
  },

  // ============================================
  // ESTUDO DO MEIO - GRADE 4
  // ============================================
  {
    id: 'em-g4-001',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Genetica',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é o ADN?',
    options: ['Uma proteína', 'Uma molécula que guarda informações genéticas', 'Um tipo de célula', 'Uma vitamina'],
    correctAnswer: 'Uma molécula que guarda informações genéticas',
    explanation: 'O ADN (Ácido Desoxirribonucleico) contém as instruções genéticas.',
  },
  {
    id: 'em-g4-002',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Forca e Movimento',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é a gravidade?',
    options: ['Uma força que empurra os objetos para cima', 'Uma força que atrai os corpos entre si', 'Um tipo de energia', 'Uma corrente de ar'],
    correctAnswer: 'Uma força que atrai os corpos entre si',
    explanation: 'A gravidade é uma força de atração entre dois corpos com massa.',
  },
  {
    id: 'em-g4-003',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Sistema Solar',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto tempo demora a Terra a dar uma volta completa ao Sol?',
    options: ['30 dias', '365 dias', '3650 dias', '1000 dias'],
    correctAnswer: '365 dias',
    explanation: 'A Terra demora aproximadamente 365 dias (1 ano) a orbitar o Sol.',
  },
  {
    id: 'em-g4-004',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Ecologia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é a biodiversidade?',
    options: ['Apenas a quantidade de árvores', 'A variedade de seres vivos num ecossistema', 'Apenas a quantidade de animais', 'A poluição do ar'],
    correctAnswer: 'A variedade de seres vivos num ecossistema',
    explanation: 'Biodiversidade é a diversidade de vida num determinado ambiente.',
  },
  {
    id: 'em-g4-005',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Tecnologia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é um sistema solar fotovoltaico?',
    options: ['Um painel de aquecimento', 'Um sistema que converte luz solar em eletricidade', 'Um tipo de foguete', 'Uma estação de rádio'],
    correctAnswer: 'Um sistema que converte luz solar em eletricidade',
    explanation: 'Os painéis fotovoltaicos convertem energia solar em eletricidade.',
  },
  {
    id: 'em-g4-006',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Corpo Humano',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o maior órgão do corpo humano?',
    options: ['Fígado', 'Pulmão', 'Pele', 'Cérebro'],
    correctAnswer: 'Pele',
    explanation: 'A pele é o maior órgão do corpo humano.',
  },
  {
    id: 'em-g4-007',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Clima',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é o efeito de estufa?',
    options: ['Resfriamento da Terra', 'Aquecimento da Terra por gases na atmosfera', 'Formação de buracos no ozono', 'Poluição da água'],
    correctAnswer: 'Aquecimento da Terra por gases na atmosfera',
    explanation: 'O efeito de estufa é causado por gases que retêm calor na atmosfera.',
  },
  {
    id: 'em-g4-008',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Recursos Naturais',
    difficulty: 'hard',
    type: 'true_false',
    question: 'A energia eólica é uma energia renovável.',
    correctAnswer: 'true',
    explanation: 'A energia eólica (dos ventos) é renovável e limpa.',
  },
  {
    id: 'em-g4-009',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Geografia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quantos continentes existem?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '7',
    explanation: 'Existem 7 continentes: Europa, Ásia, África, América do Norte, América do Sul, Oceânia e Antártida.',
  },
  {
    id: 'em-g4-010',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é o reciclagem?',
    options: ['Jogar lixo fora', 'Transformar resíduos em novos materiais', 'Queimar lixo', 'Enterrar resíduos'],
    correctAnswer: 'Transformar resíduos em novos materiais',
    explanation: 'A reciclagem transforma resíduos em matéria-prima para novos produtos.',
  },
  {
    id: 'em-g4-011',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Genetica',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'De quem herdamos as características físicas?',
    options: ['Dos professores', 'Dos amigos', 'Dos pais', 'Dos vizinhos'],
    correctAnswer: 'Dos pais',
    explanation: 'Herdamos as características genéticas dos nossos pais.',
  },
  {
    id: 'em-g4-012',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Forca e Movimento',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é a velocidade?',
    options: ['Quantidade de matéria', 'Distância percorrida por unidade de tempo', 'Peso de um objeto', 'Temperatura'],
    correctAnswer: 'Distância percorrida por unidade de tempo',
    explanation: 'Velocidade = distância / tempo.',
  },
  {
    id: 'em-g4-013',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Ecologia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é a reciclagem selectiva?',
    options: ['Juntar todo o lixo', 'Separar resíduos por tipo', 'Queimar resíduos', 'Enterrar todo o lixo'],
    correctAnswer: 'Separar resíduos por tipo',
    explanation: 'A reciclagem selectiva consiste em separar os resíduos (papel, vidro, plástico).',
  },
  {
    id: 'em-g4-014',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Tecnologia',
    difficulty: 'normal',
    type: 'true_false',
    question: 'Os computadores são ferramentas de tecnologia.',
    correctAnswer: 'true',
    explanation: 'Os computadores são dispositivos tecnológicos essenciais.',
  },
  {
    id: 'em-g4-015',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Corpo Humano',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a função do sistema nervoso?',
    options: ['Digirir alimentos', 'Controlar movimentos e sentimentos', 'Bombear sangue', 'Produzir energia'],
    correctAnswer: 'Controlar movimentos e sentimentos',
    explanation: 'O sistema nervoso controla todas as funções do corpo.',
  },
  {
    id: 'em-g4-016',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Sistema Solar',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o planeta mais próximo do Sol?',
    options: ['Vénus', 'Mercúrio', 'Terra', 'Marte'],
    correctAnswer: 'Mercúrio',
    explanation: 'Mercúrio é o planeta mais próximo do Sol.',
  },
  {
    id: 'em-g4-017',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Onde se encontra a Torre de Belém?',
    options: ['Em Espanha', 'Em Lisboa', 'No Porto', 'Em Coimbra'],
    correctAnswer: 'Em Lisboa',
    explanation: 'A Torre de Belém é um monumento em Lisboa.',
  },
  {
    id: 'em-g4-018',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Clima',
    difficulty: 'hard',
    type: 'true_false',
    question: 'O buraco na camada de ozono é causado por CFCs.',
    correctAnswer: 'true',
    explanation: 'Os CFCs (clorofluorcarbonetos) danificam a camada de ozono.',
  },
  {
    id: 'em-g4-019',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Geografia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o rio mais longo de Portugal?',
    options: ['Rio Douro', 'Rio Tejo', 'Rio Mondego', 'Rio Guadiana'],
    correctAnswer: 'Rio Tejo',
    explanation: 'O Tejo é o rio mais longo de Portugal (com cerca de 275 km em território português).',
  },
  {
    id: 'em-g4-020',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Recursos Naturais',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Que tipo de energia é produzida por painéis solares?',
    options: ['Eólica', 'Hidroeléctrica', 'Solar', 'Geotérmica'],
    correctAnswer: 'Solar',
    explanation: 'Os painéis solares produzem energia a partir da luz do sol.',
  },
];
