import { Question } from './index';

export const matchingQuestions: Question[] = [
  // ============================================
  // MATCHING QUESTIONS - PORTUGUES
  // ============================================
  {
    id: 'pt-match-g1-001',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a palavra ao seu género correto:',
    options: ['menino → masculino', 'menina → feminino', 'gato → masculino', 'casa → feminino'],
    correctAnswer: ['menino → masculino', 'menina → feminino', 'gato → masculino', 'casa → feminino'],
    explanation: 'Menino e gato são masculinos; menina e casa são femininos.',
  },
  {
    id: 'pt-match-g1-002',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a letra à vogal ou consoante:',
    options: ['A → vogal', 'B → consoante', 'E → vogal', 'F → consoante'],
    correctAnswer: ['A → vogal', 'B → consoante', 'E → vogal', 'F → consoante'],
    explanation: 'A e E são vogais; B e F são consoantes.',
  },
  {
    id: 'pt-match-g2-001',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o pronome pessoal à sua pessoa gramatical:',
    options: ['Eu → 1ª pessoa do singular', 'Tu → 2ª pessoa do singular', 'Ele → 3ª pessoa do singular', 'Nós → 1ª pessoa do plural'],
    correctAnswer: ['Eu → 1ª pessoa do singular', 'Tu → 2ª pessoa do singular', 'Ele → 3ª pessoa do singular', 'Nós → 1ª pessoa do plural'],
    explanation: 'Cada pronome corresponde a uma pessoa gramatical diferente.',
  },
  {
    id: 'pt-match-g2-002',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a palavra ao seu sinónimo:',
    options: ['alegre → feliz', 'triste → aborrecido', 'grande → enorme', 'bonito → lindo'],
    correctAnswer: ['alegre → feliz', 'triste → aborrecido', 'grande → enorme', 'bonito → lindo'],
    explanation: 'Cada par são sinónimos.',
  },
  {
    id: 'pt-match-g3-001',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o tipo de texto à sua descrição:',
    options: ['Narrativo → conta uma história', 'Informativo → transmite informação', 'Descritivo → descreve seres ou coisas', 'Dissuasivo → convence o leitor'],
    correctAnswer: ['Narrativo → conta uma história', 'Informativo → transmite informação', 'Descritivo → descreve seres ou coisas', 'Dissuasivo → convence o leitor'],
    explanation: 'Cada tipo de texto tem uma função comunicativa diferente.',
  },
  {
    id: 'pt-match-g3-002',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o sinal de pontuação à sua função:',
    options: ['Vírgula → separa elementos', 'Dois pontos → introduz fala', 'Ponto de interrogação → indica pergunta', 'Ponto e vírgula → pausa média'],
    correctAnswer: ['Vírgula → separa elementos', 'Dois pontos → introduz fala', 'Ponto de interrogação → indica pergunta', 'Ponto e vírgula → pausa média'],
    explanation: 'Cada sinal de pontuação tem uma função específica.',
  },
  {
    id: 'pt-match-g4-001',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a figura de linguagem ao seu exemplo:',
    options: ['Metáfora → "Um mar de pessoas"', 'Personificação → "O sol sorriu"', 'Hipérbole → "Choviam pedras"', 'Comparação → "Rápido como um relâmpago"'],
    correctAnswer: ['Metáfora → "Um mar de pessoas"', 'Personificação → "O sol sorriu"', 'Hipérbole → "Choviam pedras"', 'Comparação → "Rápido como um relâmpago"'],
    explanation: 'Cada exemplo ilustra uma figura de linguagem diferente.',
  },
  {
    id: 'pt-match-g4-002',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga o tempo verbal ao seu exemplo:',
    options: ['Presente → "Eu estudo"', 'Pretérito Perfeito → "Eu estudei"', 'Futuro do Presente → "Eu estudarei"', 'Pretérito Imperfeito → "Eu estudava"'],
    correctAnswer: ['Presente → "Eu estudo"', 'Pretérito Perfeito → "Eu estudei"', 'Futuro do Presente → "Eu estudarei"', 'Pretérito Imperfeito → "Eu estudava"'],
    explanation: 'Cada exemplo corresponde a um tempo verbal diferente.',
  },
  {
    id: 'pt-match-g4-003',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a expressão ao seu significado:',
    options: ['Chutar o balde → desistir', 'Pôr a mão na massa → trabalhar', 'Dar a volta por cima → recuperar', 'Estar entre a espada e a parede → dilemma'],
    correctAnswer: ['Chutar o balde → desistir', 'Pôr a mão na massa → trabalhar', 'Dar a volta por cima → recuperar', 'Estar entre a espada e a parede → dilemma'],
    explanation: 'São expressões idiomáticas do português.',
  },

  // ============================================
  // MATCHING QUESTIONS - MATEMATICA
  // ============================================
  {
    id: 'mat-match-g1-001',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o algarismo ao número por extenso:',
    options: ['3 → três', '7 → sete', '1 → um', '5 → cinco'],
    correctAnswer: ['3 → três', '7 → sete', '1 → um', '5 → cinco'],
    explanation: 'Cada algarismo corresponde ao seu número por extenso.',
  },
  {
    id: 'mat-match-g1-002',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a forma ao número de lados:',
    options: ['Triângulo → 3 lados', 'Quadrado → 4 lados', 'Pentágono → 5 lados', 'Hexágono → 6 lados'],
    correctAnswer: ['Triângulo → 3 lados', 'Quadrado → 4 lados', 'Pentágono → 5 lados', 'Hexágono → 6 lados'],
    explanation: 'Cada forma geométrica tem um número específico de lados.',
  },
  {
    id: 'mat-match-g2-001',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a operação ao seu resultado:',
    options: ['6 × 7 → 42', '8 × 5 → 40', '9 × 9 → 81', '7 × 6 → 42'],
    correctAnswer: ['6 × 7 → 42', '8 × 5 → 40', '9 × 9 → 81', '7 × 6 → 42'],
    explanation: 'Cada operação de multiplicação tem o seu resultado correto.',
  },
  {
    id: 'mat-match-g2-002',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a unidade de medida à sua correspondência:',
    options: ['1 metro → 100 centímetros', '1 hora → 60 minutos', '1 kg → 1000 gramas', '1 dia → 24 horas'],
    correctAnswer: ['1 metro → 100 centímetros', '1 hora → 60 minutos', '1 kg → 1000 gramas', '1 dia → 24 horas'],
    explanation: 'Cada unidade de medida tem uma correspondência exata.',
  },
  {
    id: 'mat-match-g3-001',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a fração à sua representação decimal:',
    options: ['1/2 → 0,5', '1/4 → 0,25', '3/4 → 0,75', '1/5 → 0,2'],
    correctAnswer: ['1/2 → 0,5', '1/4 → 0,25', '3/4 → 0,75', '1/5 → 0,2'],
    explanation: 'Cada fração pode ser convertida para um número decimal.',
  },
  {
    id: 'mat-match-g3-002',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a figura ao seu nome:',
    options: ['4 lados iguais → Quadrado', '4 lados com 2 pares iguais → Retângulo', '3 lados iguais → Triângulo equilátero', 'Todos os lados iguais e 4 cantos → Losango'],
    correctAnswer: ['4 lados iguais → Quadrado', '4 lados com 2 pares iguais → Retângulo', '3 lados iguais → Triângulo equilátero', 'Todos os lados iguais e 4 cantos → Losango'],
    explanation: 'Cada nome corresponde a uma propriedade geométrica.',
  },
  {
    id: 'mat-match-g4-001',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a fórmula à sua aplicação:',
    options: ['Perímetro = 4 × lado → Quadrado', 'Área = (base × altura)/2 → Triângulo', 'Perímetro = 2 × (c + l) → Retângulo', 'Área = c × l → Retângulo'],
    correctAnswer: ['Perímetro = 4 × lado → Quadrado', 'Área = (base × altura)/2 → Triângulo', 'Perímetro = 2 × (c + l) → Retângulo', 'Área = c × l → Retângulo'],
    explanation: 'Cada fórmula corresponde a uma medida geométrica.',
  },
  {
    id: 'mat-match-g4-002',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a unidade de medida ao que se mede:',
    options: ['Metro → comprimento', 'Quilograma → massa', 'Litro → capacidade', 'Grau → ângulo'],
    correctAnswer: ['Metro → comprimento', 'Quilograma → massa', 'Litro → capacidade', 'Grau → ângulo'],
    explanation: 'Cada unidade serve para medir uma grandeza diferente.',
  },

  // ============================================
  // MATCHING QUESTIONS - ESTUDO DO MEIO
  // ============================================
  {
    id: 'em-match-g1-001',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o animal ao som que faz:',
    options: ['Vaca → mu', 'Gato → mia', 'Cão → ladra', 'Galinha → cacareja'],
    correctAnswer: ['Vaca → mu', 'Gato → mia', 'Cão → ladra', 'Galinha → cacareja'],
    explanation: 'Cada animal tem um som característico.',
  },
  {
    id: 'em-match-g1-002',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o órgão ao sentido:',
    options: ['Olhos → visão', 'Ouvidos → audição', 'Nariz → olfato', 'Boca → paladar'],
    correctAnswer: ['Olhos → visão', 'Ouvidos → audição', 'Nariz → olfato', 'Boca → paladar'],
    explanation: 'Cada órgão está associado a um sentido.',
  },
  {
    id: 'em-match-g2-001',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a classe de animal às suas características:',
    options: ['Mamíferos → têm pelo e dão leite', 'Aves → têm penas e põem ovos', 'Répteis → têm escamas', 'Anfíbios → vivem na água e na terra'],
    correctAnswer: ['Mamíferos → têm pelo e dão leite', 'Aves → têm penas e põem ovos', 'Répteis → têm escamas', 'Anfíbios → vivem na água e na terra'],
    explanation: 'Cada classe de animal tem características únicas.',
  },
  {
    id: 'em-match-g2-002',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a parte da planta à sua função:',
    options: ['Raiz → absorve água', 'Caule → transporta seiva', 'Folha → faz fotossíntese', 'Flor → reprodução'],
    correctAnswer: ['Raiz → absorve água', 'Caule → transporta seiva', 'Folha → faz fotossíntese', 'Flor → reprodução'],
    explanation: 'Cada parte da planta tem uma função específica.',
  },
  {
    id: 'em-match-g3-001',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o planeta à sua característica:',
    options: ['Terra → planeta azul', 'Marte → planeta vermelho', 'Júpiter → maior planeta', 'Saturno → anéis'],
    correctAnswer: ['Terra → planeta azul', 'Marte → planeta vermelho', 'Júpiter → maior planeta', 'Saturno → anéis'],
    explanation: 'Cada planeta tem características que o distinguem.',
  },
  {
    id: 'em-match-g3-002',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o órgão do corpo humano à sua função:',
    options: ['Coração → bombear sangue', 'Pulmões → respirar', 'Fígado → filtrar toxinas', 'Cérebro → pensar'],
    correctAnswer: ['Coração → bombear sangue', 'Pulmões → respirar', 'Fígado → filtrar toxinas', 'Cérebro → pensar'],
    explanation: 'Cada órgão tem uma função vital no corpo.',
  },
  {
    id: 'em-match-g4-001',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga o tipo de energia renovável à sua fonte:',
    options: ['Solar → luz do sol', 'Eólica → ventos', 'Hidroeléctrica → água', 'Geotérmica → calor da terra'],
    correctAnswer: ['Solar → luz do sol', 'Eólica → ventos', 'Hidroeléctrica → água', 'Geotérmica → calor da terra'],
    explanation: 'Cada energia renovável tem uma fonte natural diferente.',
  },
  {
    id: 'em-match-g4-002',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a cor do reciclagem ao tipo de resíduo:',
    options: ['Azul → papel', 'Verde → vidro', 'Amarelo → plástico', 'Castanho → orgânico'],
    correctAnswer: ['Azul → papel', 'Verde → vidro', 'Amarelo → plástico', 'Castanho → orgânico'],
    explanation: 'Cada cor de caixa de reciclagem corresponde a um tipo de resíduo.',
  },
  {
    id: 'em-match-g4-003',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o planeta ao sua posição no sistema solar:',
    options: ['Mercúrio → 1º planeta', 'Vénus → 2º planeta', 'Terra → 3º planeta', 'Marte → 4º planeta'],
    correctAnswer: ['Mercúrio → 1º planeta', 'Vénus → 2º planeta', 'Terra → 3º planeta', 'Marte → 4º planeta'],
    explanation: 'Os planetas estão organizados por distância ao Sol.',
  },
];
