import { Question } from './index';

export const matchingQuestions: Question[] = [
  // ============================================
  // MATCHING QUESTIONS - PORTUGUES
  // ============================================
  {
    id: 'pt-match-g1-001',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a palavra ao seu género correto:',
    options: ['menino → masculino', 'menina → feminino', 'gato → masculino', 'casa → feminino'],
    correctAnswer: ['menino → masculino', 'menina → feminino', 'gato → masculino', 'casa → feminino'],
    explanation: 'Menino e gato são masculinos; menina e casa são femininos.',
  },
  {
    id: 'pt-match-g1-002',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a letra à vogal ou consoante:',
    options: ['A → vogal', 'B → consoante', 'E → vogal', 'F → consoante'],
    correctAnswer: ['A → vogal', 'B → consoante', 'E → vogal', 'F → consoante'],
    explanation: 'A e E são vogais; B e F são consoantes.',
  },
  {
    id: 'pt-match-g2-001',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o pronome pessoal à sua pessoa gramatical:',
    options: ['Eu → 1ª pessoa do singular', 'Tu → 2ª pessoa do singular', 'Ele → 3ª pessoa do singular', 'Nós → 1ª pessoa do plural'],
    correctAnswer: ['Eu → 1ª pessoa do singular', 'Tu → 2ª pessoa do singular', 'Ele → 3ª pessoa do singular', 'Nós → 1ª pessoa do plural'],
    explanation: 'Cada pronome corresponde a uma pessoa gramatical diferente.',
  },
  {
    id: 'pt-match-g2-002',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a palavra ao seu sinónimo:',
    options: ['alegre → feliz', 'triste → aborrecido', 'grande → enorme', 'bonito → lindo'],
    correctAnswer: ['alegre → feliz', 'triste → aborrecido', 'grande → enorme', 'bonito → lindo'],
    explanation: 'Cada par são sinónimos.',
  },
  {
    id: 'pt-match-g3-001',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o tipo de texto à sua descrição:',
    options: ['Narrativo → conta uma história', 'Informativo → transmite informação', 'Descritivo → descreve seres ou coisas', 'Dissuasivo → convence o leitor'],
    correctAnswer: ['Narrativo → conta uma história', 'Informativo → transmite informação', 'Descritivo → descreve seres ou coisas', 'Dissuasivo → convence o leitor'],
    explanation: 'Cada tipo de texto tem uma função comunicativa diferente.',
  },
  {
    id: 'pt-match-g3-002',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o sinal de pontuação à sua função:',
    options: ['Vírgula → separa elementos', 'Dois pontos → introduz fala', 'Ponto de interrogação → indica pergunta', 'Ponto e vírgula → pausa média'],
    correctAnswer: ['Vírgula → separa elementos', 'Dois pontos → introduz fala', 'Ponto de interrogação → indica pergunta', 'Ponto e vírgula → pausa média'],
    explanation: 'Cada sinal de pontuação tem uma função específica.',
  },
  {
    id: 'pt-match-g4-001',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a figura de linguagem ao seu exemplo:',
    options: ['Metáfora → "Um mar de pessoas"', 'Personificação → "O sol sorriu"', 'Hipérbole → "Choviam pedras"', 'Comparação → "Rápido como um relâmpago"'],
    correctAnswer: ['Metáfora → "Um mar de pessoas"', 'Personificação → "O sol sorriu"', 'Hipérbole → "Choviam pedras"', 'Comparação → "Rápido como um relâmpago"'],
    explanation: 'Cada exemplo ilustra uma figura de linguagem diferente.',
  },
  {
    id: 'pt-match-g4-002',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga o tempo verbal ao seu exemplo:',
    options: ['Presente → "Eu estudo"', 'Pretérito Perfeito → "Eu estudei"', 'Futuro do Presente → "Eu estudarei"', 'Pretérito Imperfeito → "Eu estudava"'],
    correctAnswer: ['Presente → "Eu estudo"', 'Pretérito Perfeito → "Eu estudei"', 'Futuro do Presente → "Eu estudarei"', 'Pretérito Imperfeito → "Eu estudava"'],
    explanation: 'Cada exemplo corresponde a um tempo verbal diferente.',
  },
  {
    id: 'pt-match-g4-003',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a expressão ao seu significado:',
    options: ['Chutar o balde → desistir', 'Pôr a mão na massa → trabalhar', 'Dar a volta por cima → recuperar', 'Estar entre a espada e a parede → dilemma'],
    correctAnswer: ['Chutar o balde → desistir', 'Pôr a mão na massa → trabalhar', 'Dar a volta por cima → recuperar', 'Estar entre a espada e a parede → dilemma'],
    explanation: 'São expressões idiomáticas do português.',
  },

  // ============================================
  // MATCHING QUESTIONS - MATEMATICA
  // ============================================
  {
    id: 'mat-match-g1-001',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o algarismo ao número por extenso:',
    options: ['3 → três', '7 → sete', '1 → um', '5 → cinco'],
    correctAnswer: ['3 → três', '7 → sete', '1 → um', '5 → cinco'],
    explanation: 'Cada algarismo corresponde ao seu número por extenso.',
  },
  {
    id: 'mat-match-g1-002',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a forma ao número de lados:',
    options: ['Triângulo → 3 lados', 'Quadrado → 4 lados', 'Pentágono → 5 lados', 'Hexágono → 6 lados'],
    correctAnswer: ['Triângulo → 3 lados', 'Quadrado → 4 lados', 'Pentágono → 5 lados', 'Hexágono → 6 lados'],
    explanation: 'Cada forma geométrica tem um número específico de lados.',
  },
  {
    id: 'mat-match-g2-001',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a operação ao seu resultado:',
    options: ['6 × 7 → 42', '8 × 5 → 40', '9 × 9 → 81', '7 × 6 → 42'],
    correctAnswer: ['6 × 7 → 42', '8 × 5 → 40', '9 × 9 → 81', '7 × 6 → 42'],
    explanation: 'Cada operação de multiplicação tem o seu resultado correto.',
  },
  {
    id: 'mat-match-g2-002',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a unidade de medida à sua correspondência:',
    options: ['1 metro → 100 centímetros', '1 hora → 60 minutos', '1 kg → 1000 gramas', '1 dia → 24 horas'],
    correctAnswer: ['1 metro → 100 centímetros', '1 hora → 60 minutos', '1 kg → 1000 gramas', '1 dia → 24 horas'],
    explanation: 'Cada unidade de medida tem uma correspondência exata.',
  },
  {
    id: 'mat-match-g3-001',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a fração à sua representação decimal:',
    options: ['1/2 → 0,5', '1/4 → 0,25', '3/4 → 0,75', '1/5 → 0,2'],
    correctAnswer: ['1/2 → 0,5', '1/4 → 0,25', '3/4 → 0,75', '1/5 → 0,2'],
    explanation: 'Cada fração pode ser convertida para um número decimal.',
  },
  {
    id: 'mat-match-g3-002',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a figura ao seu nome:',
    options: ['4 lados iguais → Quadrado', '4 lados com 2 pares iguais → Retângulo', '3 lados iguais → Triângulo equilátero', 'Todos os lados iguais e 4 cantos → Losango'],
    correctAnswer: ['4 lados iguais → Quadrado', '4 lados com 2 pares iguais → Retângulo', '3 lados iguais → Triângulo equilátero', 'Todos os lados iguais e 4 cantos → Losango'],
    explanation: 'Cada nome corresponde a uma propriedade geométrica.',
  },
  {
    id: 'mat-match-g4-001',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a fórmula à sua aplicação:',
    options: ['Perímetro = 4 × lado → Quadrado', 'Área = (base × altura)/2 → Triângulo', 'Perímetro = 2 × (c + l) → Retângulo', 'Área = c × l → Retângulo'],
    correctAnswer: ['Perímetro = 4 × lado → Quadrado', 'Área = (base × altura)/2 → Triângulo', 'Perímetro = 2 × (c + l) → Retângulo', 'Área = c × l → Retângulo'],
    explanation: 'Cada fórmula corresponde a uma medida geométrica.',
  },
  {
    id: 'mat-match-g4-002',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a unidade de medida ao que se mede:',
    options: ['Metro → comprimento', 'Quilograma → massa', 'Litro → capacidade', 'Grau → ângulo'],
    correctAnswer: ['Metro → comprimento', 'Quilograma → massa', 'Litro → capacidade', 'Grau → ângulo'],
    explanation: 'Cada unidade serve para medir uma grandeza diferente.',
  },

  // ============================================
  // MATCHING QUESTIONS - ESTUDO DO MEIO
  // ============================================
  {
    id: 'em-match-g1-001',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o animal ao som que faz:',
    options: ['Vaca → mu', 'Gato → mia', 'Cão → ladra', 'Galinha → cacareja'],
    correctAnswer: ['Vaca → mu', 'Gato → mia', 'Cão → ladra', 'Galinha → cacareja'],
    explanation: 'Cada animal tem um som característico.',
  },
  {
    id: 'em-match-g1-002',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o órgão ao sentido:',
    options: ['Olhos → visão', 'Ouvidos → audição', 'Nariz → olfato', 'Boca → paladar'],
    correctAnswer: ['Olhos → visão', 'Ouvidos → audição', 'Nariz → olfato', 'Boca → paladar'],
    explanation: 'Cada órgão está associado a um sentido.',
  },
  {
    id: 'em-match-g2-001',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a classe de animal às suas características:',
    options: ['Mamíferos → têm pelo e dão leite', 'Aves → têm penas e põem ovos', 'Répteis → têm escamas', 'Anfíbios → vivem na água e na terra'],
    correctAnswer: ['Mamíferos → têm pelo e dão leite', 'Aves → têm penas e põem ovos', 'Répteis → têm escamas', 'Anfíbios → vivem na água e na terra'],
    explanation: 'Cada classe de animal tem características únicas.',
  },
  {
    id: 'em-match-g2-002',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a parte da planta à sua função:',
    options: ['Raiz → absorve água', 'Caule → transporta seiva', 'Folha → faz fotossíntese', 'Flor → reprodução'],
    correctAnswer: ['Raiz → absorve água', 'Caule → transporta seiva', 'Folha → faz fotossíntese', 'Flor → reprodução'],
    explanation: 'Cada parte da planta tem uma função específica.',
  },
  {
    id: 'em-match-g3-001',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o planeta à sua característica:',
    options: ['Terra → planeta azul', 'Marte → planeta vermelho', 'Júpiter → maior planeta', 'Saturno → anéis'],
    correctAnswer: ['Terra → planeta azul', 'Marte → planeta vermelho', 'Júpiter → maior planeta', 'Saturno → anéis'],
    explanation: 'Cada planeta tem características que o distinguem.',
  },
  {
    id: 'em-match-g3-002',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o órgão do corpo humano à sua função:',
    options: ['Coração → bombear sangue', 'Pulmões → respirar', 'Fígado → filtrar toxinas', 'Cérebro → pensar'],
    correctAnswer: ['Coração → bombear sangue', 'Pulmões → respirar', 'Fígado → filtrar toxinas', 'Cérebro → pensar'],
    explanation: 'Cada órgão tem uma função vital no corpo.',
  },
  {
    id: 'em-match-g4-001',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga o tipo de energia renovável à sua fonte:',
    options: ['Solar → luz do sol', 'Eólica → ventos', 'Hidroeléctrica → água', 'Geotérmica → calor da terra'],
    correctAnswer: ['Solar → luz do sol', 'Eólica → ventos', 'Hidroeléctrica → água', 'Geotérmica → calor da terra'],
    explanation: 'Cada energia renovável tem uma fonte natural diferente.',
  },
  {
    id: 'em-match-g4-002',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a cor do reciclagem ao tipo de resíduo:',
    options: ['Azul → papel', 'Verde → vidro', 'Amarelo → plástico', 'Castanho → orgânico'],
    correctAnswer: ['Azul → papel', 'Verde → vidro', 'Amarelo → plástico', 'Castanho → orgânico'],
    explanation: 'Cada cor de caixa de reciclagem corresponde a um tipo de resíduo.',
  },
  {
    id: 'em-match-g4-003',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o planeta ao sua posição no sistema solar:',
    options: ['Mercúrio → 1º planeta', 'Vénus → 2º planeta', 'Terra → 3º planeta', 'Marte → 4º planeta'],
    correctAnswer: ['Mercúrio → 1º planeta', 'Vénus → 2º planeta', 'Terra → 3º planeta', 'Marte → 4º planeta'],
    explanation: 'Os planetas estão organizados por distância ao Sol.',
  },

  // ============================================
  // MATCHING QUESTIONS - PORTUGUES (NEW)
  // ============================================
  {
    id: 'pt-match-g1-003',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a palavra ao seu antónimo:',
    options: ['grande → pequeno', 'feliz → triste', 'alto → baixo', 'novo → velho'],
    correctAnswer: ['grande → pequeno', 'feliz → triste', 'alto → baixo', 'novo → velho'],
    explanation: 'Cada par de palavras são antónimos (opostos).',
  },
  {
    id: 'pt-match-g2-003',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o verbo à sua conjugação correta (1ª pessoa do singular):',
    options: ['Falar → eu falo', 'Comer → eu como', 'Dormir → eu durmo', 'Correr → eu corro'],
    correctAnswer: ['Falar → eu falo', 'Comer → eu como', 'Dormir → eu durmo', 'Correr → eu corro'],
    explanation: 'Cada verbo está conjugado corretamente na primeira pessoa do singular.',
  },
  {
    id: 'pt-match-g4-004',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga o tipo de texto à sua estrutura:',
    options: ['Carta → Saudação + Corpo + Despedida', 'Notícia → Lide + Desenvolvimento', 'Receita → Ingredientes + Preparação', 'Poema → Versos + Estrofes'],
    correctAnswer: ['Carta → Saudação + Corpo + Despedida', 'Notícia → Lide + Desenvolvimento', 'Receita → Ingredientes + Preparação', 'Poema → Versos + Estrofes'],
    explanation: 'Cada tipo de texto tem uma estrutura específica.',
  },

  // ============================================
  // MATCHING QUESTIONS - MATEMATICA (NEW)
  // ============================================
  {
    id: 'mat-match-g1-003',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a forma ao número de lados:',
    options: ['Círculo → 0 lados', 'Triângulo → 3 lados', 'Quadrilátero → 4 lados', 'Pentágono → 5 lados'],
    correctAnswer: ['Círculo → 0 lados', 'Triângulo → 3 lados', 'Quadrilátero → 4 lados', 'Pentágono → 5 lados'],
    explanation: 'Cada forma geométrica tem um número específico de lados.',
  },
  {
    id: 'mat-match-g3-003',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a unidade ao objeto que se mede:',
    options: ['Metro → comprimento de uma mesa', 'Quilograma → peso de um saco', 'Litro → capacidade de uma garrafa', 'Grau → abertura de um ângulo'],
    correctAnswer: ['Metro → comprimento de uma mesa', 'Quilograma → peso de um saco', 'Litro → capacidade de uma garrafa', 'Grau → abertura de um ângulo'],
    explanation: 'Cada unidade serve para medir um tipo de grandeza diferente.',
  },
  {
    id: 'mat-match-g4-003',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a percentagem ao seu significado:',
    options: ['50% → metade', '25% → um quarto', '100% → todo otodo', '10% → uma décima parte'],
    correctAnswer: ['50% → metade', '25% → um quarto', '100% → todo otodo', '10% → uma décima parte'],
    explanation: 'Cada percentagem representa uma fração diferente do todo.',
  },

  // ============================================
  // MATCHING QUESTIONS - ESTUDO DO MEIO (NEW)
  // ============================================
  {
    id: 'em-match-g1-003',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o animal ao seu habitat:',
    options: ['Peixe → água', 'Águia → céu', 'Tartaruga → terra', 'Rã → água e terra'],
    correctAnswer: ['Peixe → água', 'Águia → céu', 'Tartaruga → terra', 'Rã → água e terra'],
    explanation: 'Cada animal vive num habitat diferente.',
  },
  {
    id: 'em-match-g2-003',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o profissional ao seu local de trabalho:',
    options: ['Médico → hospital', 'Professor → escola', 'Bombeiro → quartel', 'Cozinheiro → restaurante'],
    correctAnswer: ['Médico → hospital', 'Professor → escola', 'Bombeiro → quartel', 'Cozinheiro → restaurante'],
    explanation: 'Cada profissional trabalha num local específico.',
  },
  {
    id: 'em-match-g3-003',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o aparelho do corpo à sua função:',
    options: ['Aparelho digestivo → digerir alimentos', 'Aparelho respiratório → respirar', 'Aparelho circulatório → bombear sangue', 'Aparelho nervoso → controlar o corpo'],
    correctAnswer: ['Aparelho digestivo → digerir alimentos', 'Aparelho respiratório → respirar', 'Aparelho circulatório → bombear sangue', 'Aparelho nervoso → controlar o corpo'],
    explanation: 'Cada aparelho do corpo tem uma função vital.',
  },
  {
    id: 'em-match-g4-004',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga o tipo de energia à sua fonte:',
    options: ['Fóssil → petróleo', 'Renovável → sol', 'Nuclear → urânio', 'Hidráulica → água'],
    correctAnswer: ['Fóssil → petróleo', 'Renovável → sol', 'Nuclear → urânio', 'Hidráulica → água'],
    explanation: 'Cada tipo de energia tem uma fonte diferente.',
  },

  // ============================================
  // MATCHING QUESTIONS - PORTUGUES (MORE)
  // ============================================
  {
    id: 'pt-match-g1-004',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a palavra ao seu sinónimo:',
    options: ['feliz → contente', 'bonito → belo', 'rápido → veloz', 'triste → infeliz'],
    correctAnswer: ['feliz → contente', 'bonito → belo', 'rápido → veloz', 'triste → infeliz'],
    explanation: 'Cada par são sinónimos.',
  },
  {
    id: 'pt-match-g2-004',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o provérbio ao seu significado:',
    options: ['Água mole em pedra dura tanto bate até que fura → persistência vence tudo', 'Quem semeia ventos colhe tempestades → más ações trazem más consequências', 'Mais vale tarde do que nunca → é melhor fazer algo tarde do que nunca fazer', 'Cada um sabe de si e Deus sabe de todos → cada pessoa conhece os seus próprios problemas'],
    correctAnswer: ['Água mole em pedra dura tanto bate até que fura → persistência vence tudo', 'Quem semeia ventos colhe tempestades → más ações trazem más consequências', 'Mais vale tarde do que nunca → é melhor fazer algo tarde do que nunca fazer', 'Cada um sabe de si e Deus sabe de todos → cada pessoa conhece os seus próprios problemas'],
    explanation: 'Cada provérbio transmite uma lição de sabedoria popular.',
  },
  {
    id: 'pt-match-g3-004',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a palavra à sua definição:',
    options: ['Biblioteca → lugar onde se guardam livros', 'Dicionário → livro que explica significados', 'Atlas → livro de mapas', 'Enciclopédia → coleção de artigos sobre vários temas'],
    correctAnswer: ['Biblioteca → lugar onde se guardam livros', 'Dicionário → livro que explica significados', 'Atlas → livro de mapas', 'Enciclopédia → coleção de artigos sobre vários temas'],
    explanation: 'Cada palavra tem uma definição específica.',
  },
  {
    id: 'pt-match-g4-005',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a classe de palavra ao seu exemplo:',
    options: ['Adjetivo → belo', 'Advérbio → rapidamente', 'Pronome → ela', 'Preposição → sobre'],
    correctAnswer: ['Adjetivo → belo', 'Advérbio → rapidamente', 'Pronome → ela', 'Preposição → sobre'],
    explanation: 'Cada exemplo pertence a uma classe gramatical diferente.',
  },
  {
    id: 'pt-match-g4-006',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a figura de estilo à sua definição:',
    options: ['Anáfora → repetição de palavras', 'Ironia → dizer o contrário do que se pensa', 'Eufemismo → suavizar uma expressão', 'Onomatopeia → imitar sons da natureza'],
    correctAnswer: ['Anáfora → repetição de palavras', 'Ironia → dizer o contrário do que se pensa', 'Eufemismo → suavizar uma expressão', 'Onomatopeia → imitar sons da natureza'],
    explanation: 'Cada figura de estilo tem uma função expressiva diferente.',
  },
  {
    id: 'pt-match-g2-005',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a palavra ao seu antónimo:',
    options: ['quente → frio', 'claro → escuro', 'doce → amargo', 'forte → fraco'],
    correctAnswer: ['quente → frio', 'claro → escuro', 'doce → amargo', 'forte → fraco'],
    explanation: 'Cada par de palavras são antónimos (opostos).',
  },
  {
    id: 'pt-match-g3-005',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o provérbio ao seu significado:',
    options: ['Quem tudo quer nada tem → a ganância leva à perda', 'Lágrimas não trazem de volta o que se foi → chorar não resolve os problemas', 'Devagar se vai ao longe → com calma e persistência alcançam-se grandes objetivos', 'Melhor só do que mal acompanhado → é preferível estar sozinho do que com más companhias'],
    correctAnswer: ['Quem tudo quer nada tem → a ganância leva à perda', 'Lágrimas não trazem de volta o que se foi → chorar não resolve os problemas', 'Devagar se vai ao longe → com calma e persistência alcançam-se grandes objetivos', 'Melhor só do que mal acompanhado → é preferível estar sozinho do que com más companhias'],
    explanation: 'Os provérbios transmitem sabedoria popular.',
  },

  // ============================================
  // MATCHING QUESTIONS - MATEMATICA (MORE)
  // ============================================
  {
    id: 'mat-match-g1-004',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o número ao seu dobro:',
    options: ['2 → 4', '3 → 6', '5 → 10', '4 → 8'],
    correctAnswer: ['2 → 4', '3 → 6', '5 → 10', '4 → 8'],
    explanation: 'O dobro de um número é o número multiplicado por 2.',
  },
  {
    id: 'mat-match-g2-003',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o problema à operação correta:',
    options: ['Tenho 12 maçãs e dou 5 → 12 - 5 = 7', 'Compro 3 pacotes de 8 bolachas → 3 × 8 = 24', 'Tenho 24 lápis para 6 alunos → 24 ÷ 6 = 4', 'Tinha 10 euros e recebi mais 7 → 10 + 7 = 17'],
    correctAnswer: ['Tenho 12 maçãs e dou 5 → 12 - 5 = 7', 'Compro 3 pacotes de 8 bolachas → 3 × 8 = 24', 'Tenho 24 lápis para 6 alunos → 24 ÷ 6 = 4', 'Tinha 10 euros e recebi mais 7 → 10 + 7 = 17'],
    explanation: 'Cada problema corresponde à operação matemática que o resolve.',
  },
  {
    id: 'mat-match-g3-004',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a fração ao seu decimal:',
    options: ['1/10 → 0,1', '2/5 → 0,4', '3/5 → 0,6', '1/8 → 0,125'],
    correctAnswer: ['1/10 → 0,1', '2/5 → 0,4', '3/5 → 0,6', '1/8 → 0,125'],
    explanation: 'Cada fração pode ser representada como um número decimal.',
  },
  {
    id: 'mat-match-g4-004',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a medida de área à figura correspondente:',
    options: ['Área do quadrado → lado × lado', 'Área do retângulo → comprimento × largura', 'Área do triângulo → (base × altura) ÷ 2', 'Área do círculo → π × raio²'],
    correctAnswer: ['Área do quadrado → lado × lado', 'Área do retângulo → comprimento × largura', 'Área do triângulo → (base × altura) ÷ 2', 'Área do círculo → π × raio²'],
    explanation: 'Cada figura geométrica tem uma fórmula específica para calcular a sua área.',
  },
  {
    id: 'mat-match-g2-004',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a figura ao seu nome:',
    options: ['3 lados iguais → triângulo equilátero', '4 lados iguais → quadrado', 'formato de bola → círculo', 'formato de ovo → oval'],
    correctAnswer: ['3 lados iguais → triângulo equilátero', '4 lados iguais → quadrado', 'formato de bola → círculo', 'formato de ovo → oval'],
    explanation: 'Cada propriedade descreve uma figura geométrica.',
  },
  {
    id: 'mat-match-g3-005',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a unidade à sua conversão:',
    options: ['1 km → 1000 metros', '1 tonelada → 1000 kg', '1 litro → 1000 ml', '1 século → 100 anos'],
    correctAnswer: ['1 km → 1000 metros', '1 tonelada → 1000 kg', '1 litro → 1000 ml', '1 século → 100 anos'],
    explanation: 'Cada unidade de medida tem uma relação de conversão específica.',
  },

  // ============================================
  // MATCHING QUESTIONS - ESTUDO DO MEIO (MORE)
  // ============================================
  {
    id: 'em-match-g1-004',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o órgão à sua função principal:',
    options: ['Coração → bombear sangue', 'Pulmões → respirar', 'Estômago → digerir comida', 'Cérebro → pensar'],
    correctAnswer: ['Coração → bombear sangue', 'Pulmões → respirar', 'Estômago → digerir comida', 'Cérebro → pensar'],
    explanation: 'Cada órgão tem uma função vital no corpo.',
  },
  {
    id: 'em-match-g2-004',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o fenómeno natural à sua explicação:',
    options: ['Arco-íris → luz solar refractada em gotas de chuva', 'Terramoto → movimento das placas tectónicas', 'Marés → atração gravitacional da Lua', 'Raio → descarga elétrica entre nuvens'],
    correctAnswer: ['Arco-íris → luz solar refractada em gotas de chuva', 'Terramoto → movimento das placas tectónicas', 'Marés → atração gravitacional da Lua', 'Raio → descarga elétrica entre nuvens'],
    explanation: 'Cada fenómeno natural tem uma explicação científica.',
  },
  {
    id: 'em-match-g3-004',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o monumento português à sua cidade:',
    options: ['Torre de Belém → Lisboa', 'Torre dos Clérigos → Porto', 'Universidade → Coimbra', 'Castelo de São Jorge → Lisboa'],
    correctAnswer: ['Torre de Belém → Lisboa', 'Torre dos Clérigos → Porto', 'Universidade → Coimbra', 'Castelo de São Jorge → Lisboa'],
    explanation: 'Cada monumento está localizado numa cidade portuguesa.',
  },
  {
    id: 'em-match-g4-005',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga o tipo de poluição à sua fonte:',
    options: ['Poluição do ar → gases dos carros e fábricas', 'Poluição da água → esgotos e resíduos químicos', 'Poluição sonora → barulho intenso do trânsito', 'Poluição do solo → lixo e pesticidas'],
    correctAnswer: ['Poluição do ar → gases dos carros e fábricas', 'Poluição da água → esgotos e resíduos químicos', 'Poluição sonora → barulho intenso do trânsito', 'Poluição do solo → lixo e pesticidas'],
    explanation: 'Cada tipo de poluição é causado por fontes específicas.',
  },
  {
    id: 'em-match-g2-005',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga o sentido ao seu órgão:',
    options: ['Visão → olhos', 'Audição → ouvidos', 'Olfato → nariz', 'Paladar → língua'],
    correctAnswer: ['Visão → olhos', 'Audição → ouvidos', 'Olfato → nariz', 'Paladar → língua'],
    explanation: 'Cada sentido está associado a um órgão específico.',
  },
  {
    id: 'em-match-g3-005',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Matching',
    difficulty: 'normal',
    type: 'matching',
    question: 'Liga a doença à sua prevenção:',
    options: ['Gripe → vacina contra vírus', 'Dores nos dentes → lavar os dentes duas vezes ao dia', 'Insolação → evitar exposição ao sol forte', 'Intoxicação alimentar → lavar bem os alimentos'],
    correctAnswer: ['Gripe → vacina contra vírus', 'Dores nos dentes → lavar os dentes duas vezes ao dia', 'Insolação → evitar exposição ao sol forte', 'Intoxicação alimentar → lavar bem os alimentos'],
    explanation: 'Cada doença pode ser prevenida com cuidados específicos.',
  },
  {
    id: 'em-match-g4-006',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga o tipo de ecossistema ao seu exemplo:',
    options: ['Floresta tropical → Amazonas', 'Deserto → Saara', 'Recife de coral → Grande Barreira', 'Tundra → Região Ártica'],
    correctAnswer: ['Floresta tropical → Amazonas', 'Deserto → Saara', 'Recife de coral → Grande Barreira', 'Tundra → Região Ártica'],
    explanation: 'Cada ecossistema tem exemplos característicos no planeta.',
  },
  {
    id: 'mat-match-g4-005',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Matching',
    difficulty: 'hard',
    type: 'matching',
    question: 'Liga a unidade de volume à situação de uso:',
    options: ['Litro → capacidade de uma garrafa', 'Mililitro → dose de um xarope', 'Centilitro → volume de um copo', 'Decligrama → raramente usado'],
    correctAnswer: ['Litro → capacidade de uma garrafa', 'Mililitro → dose de um xarope', 'Centilitro → volume de um copo', 'Decligrama → raramente usado'],
    explanation: 'Cada unidade de volume é adequada para situações diferentes.',
  },
  {
    id: 'pt-match-g1-005',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga o artigo ao género correto:',
    options: ['O → masculino singular', 'A → feminino singular', 'Os → masculino plural', 'As → feminino plural'],
    correctAnswer: ['O → masculino singular', 'A → feminino singular', 'Os → masculino plural', 'As → feminino plural'],
    explanation: 'Cada artigo corresponde a um género e número.',
  },
  {
    id: 'em-match-g1-005',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Matching',
    difficulty: 'easy',
    type: 'matching',
    question: 'Liga a estação do ano ao que acontece:',
    options: ['Primavera → flores aparecem', 'Veraão → muito calor', 'Outono → folhas caem', 'Inverno → frio e neve'],
    correctAnswer: ['Primavera → flores aparecem', 'Veraão → muito calor', 'Outono → folhas caem', 'Inverno → frio e neve'],
    explanation: 'Cada estação do ano tem características próprias.',
  },
];
