import { Question } from './index';

export const matematicaQuestions: Question[] = [
  // ============================================
  // MATEMATICA - GRADE 1
  // ============================================
  {
    id: 'mat-g1-001',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 3 + 4?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '7',
    explanation: '3 + 4 = 7.',
  },
  {
    id: 'mat-g1-002',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 10 - 3?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '7',
    explanation: '10 - 3 = 7.',
  },
  {
    id: 'mat-g1-003',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Contagem',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que número vem depois do 15?',
    options: ['14', '16', '17', '13'],
    correctAnswer: '16',
    explanation: 'O número que segue o 15 é o 16.',
  },
  {
    id: 'mat-g1-004',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'fill_blank',
    question: '5 + _ = 9',
    correctAnswer: '4',
    explanation: '5 + 4 = 9.',
  },
  {
    id: 'mat-g1-005',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos lados tem um triângulo?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'Um triângulo tem 3 lados.',
  },
  {
    id: 'mat-g1-006',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é o número por extenso do algarismo 7?',
    options: ['Cinco', 'Seis', 'Sete', 'Oito'],
    correctAnswer: 'Sete',
    explanation: 'O algarismo 7 escreve-se "sete".',
  },
  {
    id: 'mat-g1-007',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 2 + 2 + 2?',
    options: ['4', '5', '6', '7'],
    correctAnswer: '6',
    explanation: '2 + 2 + 2 = 6.',
  },
  {
    id: 'mat-g1-008',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Comparacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é maior: 8 ou 6?',
    options: ['6', '8', 'São iguais', 'Nenhuma'],
    correctAnswer: '8',
    explanation: '8 é maior que 6.',
  },
  {
    id: 'mat-g1-009',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'true_false',
    question: '9 - 5 = 4',
    correctAnswer: 'true',
    explanation: '9 - 5 = 4 é correto.',
  },
  {
    id: 'mat-g1-010',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos lados tem um quadrado?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '4',
    explanation: 'Um quadrado tem 4 lados iguais.',
  },
  {
    id: 'mat-g1-011',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 8 + 5?',
    options: ['12', '13', '14', '15'],
    correctAnswer: '13',
    explanation: '8 + 5 = 13.',
  },
  {
    id: 'mat-g1-012',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 14 - 6?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: '14 - 6 = 8.',
  },
  {
    id: 'mat-g1-013',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual forma tem lados curvos e nenhum canto?',
    options: ['Triângulo', 'Quadrado', 'Círculo', 'Retângulo'],
    correctAnswer: 'Círculo',
    explanation: 'O círculo tem lados curvos e nenhum canto.',
  },
  {
    id: 'mat-g1-014',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'O número 10 é formado por _ dezena(s).',
    correctAnswer: '1',
    explanation: 'O número 10 tem 1 dezena.',
  },
  {
    id: 'mat-g1-015',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'true_false',
    question: '7 + 3 = 10',
    correctAnswer: 'true',
    explanation: '7 + 3 = 10 está correto.',
  },
  {
    id: 'mat-g1-016',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Comparacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é menor: 12 ou 21?',
    options: ['12', '21', 'São iguais', 'Nenhuma'],
    correctAnswer: '12',
    explanation: '12 é menor que 21.',
  },
  {
    id: 'mat-g1-017',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Contagem',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que número vem antes do 10?',
    options: ['8', '9', '11', '12'],
    correctAnswer: '9',
    explanation: 'O número antes de 10 é o 9.',
  },
  {
    id: 'mat-g1-018',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'true_false',
    question: 'Um retângulo tem 4 lados.',
    correctAnswer: 'true',
    explanation: 'Um retângulo tem 4 lados, sendo 2 pares de lados iguais.',
  },
  {
    id: 'mat-g1-019',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas unidades tem o número 7?',
    options: ['7', '1', '10', '70'],
    correctAnswer: '7',
    explanation: 'O número 7 tem 7 unidades.',
  },
  {
    id: 'mat-g1-020',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'fill_blank',
    question: '12 - _ = 8',
    correctAnswer: '4',
    explanation: '12 - 4 = 8.',
  },
  {
    id: 'mat-g1-021',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 9 + 6?',
    options: ['13', '14', '15', '16'],
    correctAnswer: '15',
    explanation: '9 + 6 = 15.',
  },
  {
    id: 'mat-g1-022',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 15 - 7?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: '15 - 7 = 8.',
  },
  {
    id: 'mat-g1-023',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Soma com Transporte',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 8 + 5?',
    options: ['12', '13', '14', '15'],
    correctAnswer: '13',
    explanation: '8 + 5 = 13 (transportamos 1 para a dezena).',
  },
  {
    id: 'mat-g1-024',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Subtracao com Emprestimo',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 13 - 5?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: '13 - 5 = 8 (fazemos empréstimo da dezena).',
  },
  {
    id: 'mat-g1-025',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Figuras Solidas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que figura sólida tem todas as faces iguais e quadradas?',
    options: ['Esfera', 'Cubo', 'Cone', 'Cilindro'],
    correctAnswer: 'Cubo',
    explanation: 'O cubo tem 6 faces quadradas e iguais.',
  },
  {
    id: 'mat-g1-026',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Figuras Solidas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que figura sólida é redonda como uma bola?',
    options: ['Cubo', 'Cilindro', 'Esfera', 'Cone'],
    correctAnswer: 'Esfera',
    explanation: 'A esfera é redonda como uma bola.',
  },
  {
    id: 'mat-g1-027',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Graficos Simples',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Num gráfico de barras, que representa a barra mais alta?',
    options: ['O menor valor', 'O maior valor', 'A média', 'O valor zero'],
    correctAnswer: 'O maior valor',
    explanation: 'A barra mais alta representa o maior valor.',
  },
  {
    id: 'mat-g1-028',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'O número 20 é formado por _ dezena(s).',
    correctAnswer: '2',
    explanation: 'O número 20 tem 2 dezenas.',
  },
  {
    id: 'mat-g1-029',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'fill_blank',
    question: '7 + _ = 12',
    correctAnswer: '5',
    explanation: '7 + 5 = 12.',
  },
  {
    id: 'mat-g1-030',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos cantos tem um triângulo?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'Um triângulo tem 3 cantos (vértices).',
  },
  {
    id: 'mat-g1-031',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Comparacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é maior: 15 ou 18?',
    options: ['15', '18', 'São iguais', 'Nenhuma'],
    correctAnswer: '18',
    explanation: '18 é maior que 15.',
  },
  {
    id: 'mat-g1-032',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Contagem',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Conte de 2 em 2: 2, 4, 6, _, 10',
    options: ['7', '8', '9', '11'],
    correctAnswer: '8',
    explanation: 'A sequência de 2 em 2 é: 2, 4, 6, 8, 10.',
  },

  // ============================================
  // MATEMATICA - GRADE 2
  // ============================================
  {
    id: 'mat-g2-001',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 25 + 37?',
    options: ['52', '62', '72', '82'],
    correctAnswer: '62',
    explanation: '25 + 37 = 62.',
  },
  {
    id: 'mat-g2-002',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '3 × 4 = _',
    correctAnswer: '12',
    explanation: '3 × 4 = 12.',
  },
  {
    id: 'mat-g2-003',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos cantos tem um retângulo?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '4',
    explanation: 'Um retângulo tem 4 cantos (vértices).',
  },
  {
    id: 'mat-g2-004',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 100 - 45?',
    options: ['45', '55', '65', '75'],
    correctAnswer: '55',
    explanation: '100 - 45 = 55.',
  },
  {
    id: 'mat-g2-005',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: '5 × 6 = ?',
    options: ['25', '30', '35', '20'],
    correctAnswer: '30',
    explanation: '5 × 6 = 30.',
  },
  {
    id: 'mat-g2-006',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos centímetros tem 1 metro?',
    options: ['10', '50', '100', '1000'],
    correctAnswer: '100',
    explanation: '1 metro = 100 centímetros.',
  },
  {
    id: 'mat-g2-007',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '8 × 7 = _',
    correctAnswer: '56',
    explanation: '8 × 7 = 56.',
  },
  {
    id: 'mat-g2-008',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Maria tem 12 rebuçados e deu 5 ao João. Quantos rebuçados tem Maria agora?',
    options: ['5', '6', '7', '17'],
    correctAnswer: '7',
    explanation: '12 - 5 = 7 rebuçados.',
  },
  {
    id: 'mat-g2-009',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número que fica entre o 29 e o 31?',
    options: ['28', '30', '32', '29'],
    correctAnswer: '30',
    explanation: 'O número entre 29 e 31 é 30.',
  },
  {
    id: 'mat-g2-010',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'true_false',
    question: '9 × 3 = 27',
    correctAnswer: 'true',
    explanation: '9 × 3 = 27 está correto.',
  },
  {
    id: 'mat-g2-011',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 68 + 45?',
    options: ['103', '113', '123', '133'],
    correctAnswer: '113',
    explanation: '68 + 45 = 113.',
  },
  {
    id: 'mat-g2-012',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '7 × _ = 42',
    correctAnswer: '6',
    explanation: '7 × 6 = 42.',
  },
  {
    id: 'mat-g2-013',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número ímpar entre 10 e 14?',
    options: ['10', '11', '12', '14'],
    correctAnswer: '11',
    explanation: '11 é o único número ímpar entre 10 e 14.',
  },
  {
    id: 'mat-g2-014',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Formas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual forma tem 6 faces iguais?',
    options: ['Cubo', 'Esfera', 'Cone', 'Cilindro'],
    correctAnswer: 'Cubo',
    explanation: 'O cubo tem 6 faces quadradas e iguais.',
  },
  {
    id: 'mat-g2-015',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'true_false',
    question: '1 hora = 60 minutos.',
    correctAnswer: 'true',
    explanation: 'Uma hora tem exatamente 60 minutos.',
  },
  {
    id: 'mat-g2-016',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 9 × 9?',
    options: ['72', '81', '91', '99'],
    correctAnswer: '81',
    explanation: '9 × 9 = 81.',
  },
  {
    id: 'mat-g2-017',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'João tem 8 anos e a irmã tem o dobro. Quantos anos tem a irmã?',
    options: ['12', '14', '16', '18'],
    correctAnswer: '16',
    explanation: '8 × 2 = 16 anos.',
  },
  {
    id: 'mat-g2-018',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos eixos de simetria tem um quadrado?',
    options: ['1', '2', '4', '8'],
    correctAnswer: '4',
    explanation: 'O quadrado tem 4 eixos de simetria.',
  },
  {
    id: 'mat-g2-019',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '5 dezenas e 3 unidades = _',
    correctAnswer: '53',
    explanation: '5 dezenas (50) + 3 unidades (3) = 53.',
  },
  {
    id: 'mat-g2-020',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: '6 × 8 = ?',
    options: ['42', '48', '54', '56'],
    correctAnswer: '48',
    explanation: '6 × 8 = 48.',
  },
  {
    id: 'mat-g2-021',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Duizia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos objectos tem numa dúzia?',
    options: ['6', '10', '12', '24'],
    correctAnswer: '12',
    explanation: 'Uma dúzia tem 12 objectos.',
  },
  {
    id: 'mat-g2-022',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Duizia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos objectos tem em meia dúzia?',
    options: ['3', '5', '6', '12'],
    correctAnswer: '6',
    explanation: 'Meia dúzia é metade de uma dúzia: 12 ÷ 2 = 6.',
  },
  {
    id: 'mat-g2-023',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Duizia',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '3 dúzias = _ objectos.',
    correctAnswer: '36',
    explanation: '3 × 12 = 36 objectos.',
  },
  {
    id: 'mat-g2-024',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que tipo de retas nunca se cruzam?',
    options: ['Convergentes', 'Paralelas', 'Perpendiculares', 'Concorrentes'],
    correctAnswer: 'Paralelas',
    explanation: 'As retas paralelas mantêm a mesma distância e nunca se cruzam.',
  },
  {
    id: 'mat-g2-025',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que tipo de retas se cruzam formando 90°?',
    options: ['Paralelas', 'Convergentes', 'Perpendiculares', 'Concorrentes'],
    correctAnswer: 'Perpendiculares',
    explanation: 'As retas perpendiculares cruzam-se formando ângulos de 90°.',
  },
  {
    id: 'mat-g2-026',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '4 × 9 = _',
    correctAnswer: '36',
    explanation: '4 × 9 = 36.',
  },
  {
    id: 'mat-g2-027',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 200 - 87?',
    options: ['113', '123', '133', '143'],
    correctAnswer: '113',
    explanation: '200 - 87 = 113.',
  },
  {
    id: 'mat-g2-028',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número par entre 45 e 51?',
    options: ['45', '47', '48', '51'],
    correctAnswer: '48',
    explanation: '48 é o único número par entre 45 e 51.',
  },
  {
    id: 'mat-g2-029',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos quilogramas tem 5000 gramas?',
    options: ['5', '50', '500', '5000'],
    correctAnswer: '5',
    explanation: '5000 g = 5 kg.',
  },
  {
    id: 'mat-g2-030',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ana tem 24 lápis e dá metade à Maria. Quantos lápis fica Ana?',
    options: ['6', '10', '12', '18'],
    correctAnswer: '12',
    explanation: '24 ÷ 2 = 12 lápis.',
  },
  {
    id: 'mat-g2-031',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'true_false',
    question: '7 × 8 = 56',
    correctAnswer: 'true',
    explanation: '7 × 8 = 56 está correto.',
  },
  {
    id: 'mat-g2-032',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Formas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual forma sólida tem 2 faces circulares?',
    options: ['Cubo', 'Esfera', 'Cilindro', 'Pirâmide'],
    correctAnswer: 'Cilindro',
    explanation: 'O cilindro tem 2 faces circulares (base e topo).',
  },

  // ============================================
  // MATEMATICA - GRADE 3
  // ============================================
  {
    id: 'mat-g3-001',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 156 + 278?',
    options: ['424', '434', '444', '454'],
    correctAnswer: '434',
    explanation: '156 + 278 = 434.',
  },
  {
    id: 'mat-g3-002',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 48 ÷ 6?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: '48 ÷ 6 = 8.',
  },
  {
    id: 'mat-g3-003',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Fracoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que fração representa metade de um todo?',
    options: ['1/3', '1/2', '1/4', '2/3'],
    correctAnswer: '1/2',
    explanation: 'Metade é representada pela fração 1/2.',
  },
  {
    id: 'mat-g3-004',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos graus tem um ângulo reto?',
    options: ['45°', '60°', '90°', '180°'],
    correctAnswer: '90°',
    explanation: 'Um ângulo reto mede exatamente 90 graus.',
  },
  {
    id: 'mat-g3-005',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos quilogramas tem 1 tonelada?',
    options: ['100', '500', '1000', '10000'],
    correctAnswer: '1000',
    explanation: '1 tonelada = 1000 quilogramas.',
  },
  {
    id: 'mat-g3-006',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Pedro comprou 3 cadernos a 150$ cada. Quanto gastou no total?',
    options: ['350$', '400$', '450$', '500$'],
    correctAnswer: '450$',
    explanation: '3 × 150$ = 450$.',
  },
  {
    id: 'mat-g3-007',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'O número 356 tem _ centenas, _ dezenas e _ unidades.',
    correctAnswer: '3,5,6',
    explanation: '356 = 3 centenas + 5 dezenas + 6 unidades.',
  },
  {
    id: 'mat-g3-008',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Perimetros',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o perímetro de um quadrado com 5 cm de lado?',
    options: ['10 cm', '15 cm', '20 cm', '25 cm'],
    correctAnswer: '20 cm',
    explanation: 'Perímetro = 4 × 5 cm = 20 cm.',
  },
  {
    id: 'mat-g3-009',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '12 × 9 = _',
    correctAnswer: '108',
    explanation: '12 × 9 = 108.',
  },
  {
    id: 'mat-g3-010',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'true_false',
    question: '250 + 350 = 600',
    correctAnswer: 'true',
    explanation: '250 + 350 = 600 está correto.',
  },
  {
    id: 'mat-g3-011',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Fracoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual fração é equivalente a 1/2?',
    options: ['2/3', '2/4', '3/4', '1/3'],
    correctAnswer: '2/4',
    explanation: '2/4 = 1/2 (podemos simplificar dividindo por 2).',
  },
  {
    id: 'mat-g3-012',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '72 ÷ 8 = _',
    correctAnswer: '9',
    explanation: '72 ÷ 8 = 9.',
  },
  {
    id: 'mat-g3-013',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos minutos tem 2 horas?',
    options: ['60', '90', '100', '120'],
    correctAnswer: '120',
    explanation: '2 horas × 60 minutos = 120 minutos.',
  },
  {
    id: 'mat-g3-014',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos triângulos formam um losango?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'Um losango pode ser dividido em 2 triângulos retângulos.',
  },
  {
    id: 'mat-g3-015',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ana comprou 4 caixas de lápis com 12 lápis cada. Quantos lápis tem no total?',
    options: ['36', '42', '48', '52'],
    correctAnswer: '48',
    explanation: '4 × 12 = 48 lápis.',
  },
  {
    id: 'mat-g3-016',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Area',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a área de um quadrado com 4 cm de lado?',
    options: ['8 cm²', '12 cm²', '16 cm²', '20 cm²'],
    correctAnswer: '16 cm²',
    explanation: 'Área = 4 × 4 = 16 cm².',
  },
  {
    id: 'mat-g3-017',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o dobro de 45?',
    options: ['80', '85', '90', '95'],
    correctAnswer: '90',
    explanation: '45 × 2 = 90.',
  },
  {
    id: 'mat-g3-018',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '156 - _ = 89',
    correctAnswer: '67',
    explanation: '156 - 67 = 89.',
  },
  {
    id: 'mat-g3-019',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'true_false',
    question: '15 × 6 = 90',
    correctAnswer: 'true',
    explanation: '15 × 6 = 90 está correto.',
  },
  {
    id: 'mat-g3-020',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos mililitros tem 1 litro?',
    options: ['100', '500', '1000', '10000'],
    correctAnswer: '1000',
    explanation: '1 litro = 1000 mililitros.',
  },
  {
    id: 'mat-g3-021',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeros Romanos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número romano para 5?',
    options: ['I', 'IV', 'V', 'VI'],
    correctAnswer: 'V',
    explanation: 'V representa o número 5 em números romanos.',
  },
  {
    id: 'mat-g3-022',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeros Romanos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número romano para 10?',
    options: ['V', 'X', 'L', 'C'],
    correctAnswer: 'X',
    explanation: 'X representa o número 10 em números romanos.',
  },
  {
    id: 'mat-g3-023',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeros Romanos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número romano para 50?',
    options: ['X', 'V', 'L', 'C'],
    correctAnswer: 'L',
    explanation: 'L representa o número 50 em números romanos.',
  },
  {
    id: 'mat-g3-024',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Simetria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos eixos de simetria tem um triângulo equilátero?',
    options: ['1', '2', '3', '6'],
    correctAnswer: '3',
    explanation: 'Um triângulo equilátero tem 3 eixos de simetria.',
  },
  {
    id: 'mat-g3-025',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Simetria',
    difficulty: 'normal',
    type: 'true_false',
    question: 'Um círculo tem infinitos eixos de simetria.',
    correctAnswer: 'true',
    explanation: 'Um círculo tem infinitos eixos de simetria passando pelo centro.',
  },
  {
    id: 'mat-g3-026',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Coordenadas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Numa grelha de coordenadas, onde está o ponto (0,0)?',
    options: ['Canto superior direito', 'Centro', 'Origem', 'Fundo esquerdo'],
    correctAnswer: 'Origem',
    explanation: 'O ponto (0,0) chama-se origem e situa-se no canto inferior esquerdo.',
  },
  {
    id: 'mat-g3-027',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Moda e Media',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a moda dos números: 2, 3, 3, 5, 7?',
    options: ['2', '3', '5', '7'],
    correctAnswer: '3',
    explanation: 'A moda é o número que mais se repete: 3 aparece 2 vezes.',
  },
  {
    id: 'mat-g3-028',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Moda e Media',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a média dos números: 4, 6, 8?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '6',
    explanation: 'Média = (4 + 6 + 8) ÷ 3 = 18 ÷ 3 = 6.',
  },
  {
    id: 'mat-g3-029',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Fracoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual fração representa um quarto de um todo?',
    options: ['1/2', '1/3', '1/4', '1/5'],
    correctAnswer: '1/4',
    explanation: 'Um quarto é representado pela fração 1/4.',
  },
  {
    id: 'mat-g3-030',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '324 + _ = 500',
    correctAnswer: '176',
    explanation: '500 - 324 = 176.',
  },
  {
    id: 'mat-g3-031',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 63 ÷ 9?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '7',
    explanation: '63 ÷ 9 = 7.',
  },
  {
    id: 'mat-g3-032',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Perimetros',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'O perímetro de um rectângulo com 6 cm e 4 cm é _ cm.',
    correctAnswer: '20',
    explanation: 'Perímetro = 2 × (6 + 4) = 20 cm.',
  },

  // ============================================
  // MATEMATICA - GRADE 4
  // ============================================
  {
    id: 'mat-g4-001',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Aritmetica',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quanto é 1234 + 5678?',
    options: ['6812', '6912', '7012', '7112'],
    correctAnswer: '6912',
    explanation: '1234 + 5678 = 6912.',
  },
  {
    id: 'mat-g4-002',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Fracoes',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o resultado de 1/4 + 1/4?',
    options: ['1/2', '2/8', '2/4', '1/8'],
    correctAnswer: '1/2',
    explanation: '1/4 + 1/4 = 2/4 = 1/2.',
  },
  {
    id: 'mat-g4-003',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Geometria',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quantos triângulos tem numa estrela de 5 pontas?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'Uma estrela de 5 pontas tem 5 triângulos.',
  },
  {
    id: 'mat-g4-004',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ana tem o triplo da idade de Pedro. Se Pedro tem 8 anos, quantos anos tem Ana?',
    options: ['16', '24', '21', '18'],
    correctAnswer: '24',
    explanation: '3 × 8 = 24 anos.',
  },
  {
    id: 'mat-g4-005',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Decimal',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 3,5 + 2,7?',
    options: ['5,2', '6,2', '7,2', '8,2'],
    correctAnswer: '6,2',
    explanation: '3,5 + 2,7 = 6,2.',
  },
  {
    id: 'mat-g4-006',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Area',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a área de um retângulo com 8 cm de comprimento e 5 cm de largura?',
    options: ['13 cm²', '30 cm²', '40 cm²', '45 cm²'],
    correctAnswer: '40 cm²',
    explanation: 'Área = 8 × 5 = 40 cm².',
  },
  {
    id: 'mat-g4-007',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Multiplicacao',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '25 × 12 = _',
    correctAnswer: '300',
    explanation: '25 × 12 = 300.',
  },
  {
    id: 'mat-g4-008',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Um comboio parte às 14h30 e chega ao destino às 16h45. Quanto tempo durou a viagem?',
    options: ['1h15', '2h15', '2h30', '3h15'],
    correctAnswer: '2h15',
    explanation: 'Das 14h30 às 16h45 são 2 horas e 15 minutos.',
  },
  {
    id: 'mat-g4-009',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Divisao',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '144 ÷ 12 = _',
    correctAnswer: '12',
    explanation: '144 ÷ 12 = 12.',
  },
  {
    id: 'mat-g4-010',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número par entre o 17 e o 21?',
    options: ['17', '18', '19', '20'],
    correctAnswer: '18',
    explanation: 'Os números pares entre 17 e 21 são 18 e 20. O primeiro é 18.',
  },
  {
    id: 'mat-g4-011',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Decimal',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '6,8 - 3,5 = _',
    correctAnswer: '3,3',
    explanation: '6,8 - 3,5 = 3,3.',
  },
  {
    id: 'mat-g4-012',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Fracoes',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o resultado de 3/4 - 1/4?',
    options: ['1/2', '2/4', '2/8', '3/8'],
    correctAnswer: '1/2',
    explanation: '3/4 - 1/4 = 2/4 = 1/2.',
  },
  {
    id: 'mat-g4-013',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Perimetros',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o perímetro de um retângulo com 7 cm de comprimento e 3 cm de largura?',
    options: ['10 cm', '14 cm', '20 cm', '21 cm'],
    correctAnswer: '20 cm',
    explanation: 'Perímetro = 2 × (7 + 3) = 20 cm.',
  },
  {
    id: 'mat-g4-014',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Multiplicacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quanto é 156 × 3?',
    options: ['458', '468', '478', '488'],
    correctAnswer: '468',
    explanation: '156 × 3 = 468.',
  },
  {
    id: 'mat-g4-015',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Um pacote tem 24 lápis. Se distribuirmos por 6 alunos, quantos lápis recebe cada um?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '4',
    explanation: '24 ÷ 6 = 4 lápis por aluno.',
  },
  {
    id: 'mat-g4-016',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Area',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'A área de um triângulo com base 10 cm e altura 6 cm é _ cm².',
    correctAnswer: '30',
    explanation: 'Área = (10 × 6) / 2 = 30 cm².',
  },
  {
    id: 'mat-g4-017',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o triplo de 27?',
    options: ['54', '72', '81', '90'],
    correctAnswer: '81',
    explanation: '27 × 3 = 81.',
  },
  {
    id: 'mat-g4-018',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Aritmetica',
    difficulty: 'hard',
    type: 'true_false',
    question: '245 + 378 = 623',
    correctAnswer: 'true',
    explanation: '245 + 378 = 623 está correto.',
  },
  {
    id: 'mat-g4-019',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Divisao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quanto é 225 ÷ 5?',
    options: ['40', '45', '50', '55'],
    correctAnswer: '45',
    explanation: '225 ÷ 5 = 45.',
  },
  {
    id: 'mat-g4-020',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Geometria',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quantos eixos de simetria tem um retângulo (que não é quadrado)?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'Um retângulo tem 2 eixos de simetria.',
  },
  {
    id: 'mat-g4-021',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Numeracao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o número que tem 3 milhares, 5 centenas e 7 unidades?',
    options: ['3570', '3507', '3057', '5370'],
    correctAnswer: '3507',
    explanation: '3000 + 500 + 7 = 3507.',
  },
  {
    id: 'mat-g4-022',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Numeracao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o predecessor de 1000?',
    options: ['999', '1001', '990', '1010'],
    correctAnswer: '999',
    explanation: 'O predecessor de 1000 é 1000 - 1 = 999.',
  },
  {
    id: 'mat-g4-023',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Arredondamentos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Arredonde 367 à centena mais próxima.',
    options: ['300', '350', '400', '370'],
    correctAnswer: '400',
    explanation: '367 fica mais perto de 400 (diferença de 33) do que de 300 (diferença de 67).',
  },
  {
    id: 'mat-g4-024',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Arredondamentos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Arredonde 245 à dezena mais próxima.',
    options: ['200', '240', '250', '300'],
    correctAnswer: '250',
    explanation: '245 fica mais perto de 250 (diferença de 5) do que de 240 (diferença de 5, mas por convenção arredonda-se para cima).',
  },
  {
    id: 'mat-g4-025',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Proporcionalidade',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Se 3 canetas custam 1,50€, quanto custam 5 canetas?',
    options: ['2,00€', '2,50€', '3,00€', '1,50€'],
    correctAnswer: '2,50€',
    explanation: '1 caneta custa 1,50 ÷ 3 = 0,50€. 5 canetas custam 5 × 0,50 = 2,50€.',
  },
  {
    id: 'mat-g4-026',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Probabilidades',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ao lançar um dado justo, qual a probabilidade de sair 6?',
    options: ['1/2', '1/3', '1/4', '1/6'],
    correctAnswer: '1/6',
    explanation: 'Um dado tem 6 faces iguais, por isso a probabilidade de sair 6 é 1/6.',
  },
  {
    id: 'mat-g4-027',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Probabilidades',
    difficulty: 'hard',
    type: 'true_false',
    question: 'Ao lançar uma moeda, a probabilidade de sair cara é 50%.',
    correctAnswer: 'true',
    explanation: 'Uma moeda tem 2 faces, por isso a probabilidade de cara é 1/2 = 50%.',
  },
  {
    id: 'mat-g4-028',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Proporcionalidade',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'Se 4 pessoas gastam 20€, 6 pessoas gastam _€.',
    correctAnswer: '30',
    explanation: 'Proporção: 20€ ÷ 4 = 5€ por pessoa. 6 × 5 = 30€.',
  },
  {
    id: 'mat-g4-029',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Decimal',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o resultado de 4,5 × 2?',
    options: ['6,5', '8,5', '9,0', '9,5'],
    correctAnswer: '9,0',
    explanation: '4,5 × 2 = 9,0.',
  },
  {
    id: 'mat-g4-030',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Fracoes',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o resultado de 2/5 + 1/5?',
    options: ['3/10', '3/5', '2/10', '1/5'],
    correctAnswer: '3/5',
    explanation: '2/5 + 1/5 = 3/5 (mesmo denominador, somam-se os numeradores).',
  },
  {
    id: 'mat-g4-031',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Aritmetica',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '5000 - _ = 2345',
    correctAnswer: '2655',
    explanation: '5000 - 2345 = 2655.',
  },
  {
    id: 'mat-g4-032',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Multiplicacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quanto é 45 × 11?',
    options: ['485', '495', '505', '515'],
    correctAnswer: '495',
    explanation: '45 × 11 = 495.',
  },

  // ============================================
  // MATEMATICA - GRADE 1 (NEW QUESTIONS)
  // ============================================
  {
    id: 'mat-g1-033',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Problemas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Maria tem 5 maçãs e comprou mais 3. Quantas maçãs tem agora?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: '5 + 3 = 8 maçãs.',
  },
  {
    id: 'mat-g1-034',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Problemas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'João tem 10 rebuçados e deu 4 ao amigo. Quantos rebuçados tem João?',
    options: ['4', '5', '6', '7'],
    correctAnswer: '6',
    explanation: '10 - 4 = 6 rebuçados.',
  },
  {
    id: 'mat-g1-035',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Figuras Solidas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que figura sólida tem uma base circular e um vértice?',
    options: ['Cilindro', 'Esfera', 'Cone', 'Prisma'],
    correctAnswer: 'Cone',
    explanation: 'O cone tem uma base circular e um vértice (ponta).',
  },
  {
    id: 'mat-g1-036',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Figuras Solidas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que sólido se assemelha a uma caixa de presentes?',
    options: ['Esfera', 'Cone', 'Cubo', 'Cilindro'],
    correctAnswer: 'Cubo',
    explanation: 'O cubo assemelha-se a uma caixa com faces quadradas.',
  },
  {
    id: 'mat-g1-037',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'fill_blank',
    question: '18 - _ = 12',
    correctAnswer: '6',
    explanation: '18 - 6 = 12.',
  },
  {
    id: 'mat-g1-038',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Contagem',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Conte de 5 em 5: 5, 10, 15, _, 25',
    options: ['18', '20', '22', '23'],
    correctAnswer: '20',
    explanation: 'A sequência de 5 em 5 é: 5, 10, 15, 20, 25.',
  },
  {
    id: 'mat-g1-039',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é o número que tem 2 dezenas e 4 unidades?',
    options: ['24', '42', '224', '204'],
    correctAnswer: '24',
    explanation: '2 dezenas (20) + 4 unidades (4) = 24.',
  },
  {
    id: 'mat-g1-040',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Comparacao',
    difficulty: 'easy',
    type: 'true_false',
    question: '23 é maior que 32.',
    correctAnswer: 'false',
    explanation: '23 é menor que 32.',
  },

  // ============================================
  // MATEMATICA - GRADE 2 (NEW QUESTIONS)
  // ============================================
  {
    id: 'mat-g2-033',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas com Multiplicacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Há 4 filas de cadeiras e cada fila tem 6 cadeiras. Quantas cadeiras há no total?',
    options: ['10', '20', '24', '28'],
    correctAnswer: '24',
    explanation: '4 × 6 = 24 cadeiras.',
  },
  {
    id: 'mat-g2-034',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Comprimento',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a unidade adequada para medir o comprimento de um lápis?',
    options: ['Metro', 'Quilómetro', 'Centímetro', 'Milímetro'],
    correctAnswer: 'Centímetro',
    explanation: 'O comprimento de um lápis mede-se em centímetros (aprox. 15 cm).',
  },
  {
    id: 'mat-g2-035',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '9 × 6 = _',
    correctAnswer: '54',
    explanation: '9 × 6 = 54.',
  },
  {
    id: 'mat-g2-036',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ana tem 3 pacotes de 8 bolachas. Quantas bolachas tem no total?',
    options: ['11', '24', '27', '32'],
    correctAnswer: '24',
    explanation: '3 × 8 = 24 bolachas.',
  },
  {
    id: 'mat-g2-037',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos metros tem 300 centímetros?',
    options: ['3', '30', '300', '3000'],
    correctAnswer: '3',
    explanation: '300 cm = 3 m (dividir por 100).',
  },
  {
    id: 'mat-g2-038',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '150 + _ = 200',
    correctAnswer: '50',
    explanation: '200 - 150 = 50.',
  },
  {
    id: 'mat-g2-039',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número ímpar entre 50 e 56?',
    options: ['50', '52', '53', '56'],
    correctAnswer: '53',
    explanation: '53 é o único número ímpar entre 50 e 56.',
  },
  {
    id: 'mat-g2-040',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'true_false',
    question: '8 × 7 = 54',
    correctAnswer: 'false',
    explanation: '8 × 7 = 56, não 54.',
  },

  // ============================================
  // MATEMATICA - GRADE 3 (NEW QUESTIONS)
  // ============================================
  {
    id: 'mat-g3-033',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Fracoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual fração é equivalente a 2/6?',
    options: ['1/2', '1/3', '1/4', '2/3'],
    correctAnswer: '1/3',
    explanation: '2/6 = 1/3 (podemos simplificar dividindo por 2).',
  },
  {
    id: 'mat-g3-034',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Perimetros',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'O perímetro de um triângulo com lados de 5 cm, 5 cm e 5 cm é _ cm.',
    correctAnswer: '15',
    explanation: 'Perímetro = 5 + 5 + 5 = 15 cm.',
  },
  {
    id: 'mat-g3-035',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Um comboio parte às 9h15 e chega às 11h45. Quanto tempo durou a viagem?',
    options: ['2h30', '2h45', '3h00', '3h15'],
    correctAnswer: '2h30',
    explanation: 'Das 9h15 às 11h45 são 2 horas e 30 minutos.',
  },
  {
    id: 'mat-g3-036',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Area',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a área de um retângulo com 7 cm de comprimento e 3 cm de largura?',
    options: ['10 cm²', '21 cm²', '24 cm²', '28 cm²'],
    correctAnswer: '21 cm²',
    explanation: 'Área = 7 × 3 = 21 cm².',
  },
  {
    id: 'mat-g3-037',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '81 ÷ 9 = _',
    correctAnswer: '9',
    explanation: '81 ÷ 9 = 9.',
  },
  {
    id: 'mat-g3-038',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 14 × 5?',
    options: ['60', '65', '70', '75'],
    correctAnswer: '70',
    explanation: '14 × 5 = 70.',
  },
  {
    id: 'mat-g3-039',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o predecessor de 500?',
    options: ['499', '501', '490', '510'],
    correctAnswer: '499',
    explanation: 'O predecessor de 500 é 500 - 1 = 499.',
  },
  {
    id: 'mat-g3-040',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'true_false',
    question: '350 - 175 = 175',
    correctAnswer: 'true',
    explanation: '350 - 175 = 175 está correto.',
  },

  // ============================================
  // MATEMATICA - GRADE 4 (NEW QUESTIONS)
  // ============================================
  {
    id: 'mat-g4-033',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Percentagens',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é 25% de 80?',
    options: ['15', '20', '25', '30'],
    correctAnswer: '20',
    explanation: '25% de 80 = 80 × 0,25 = 20.',
  },
  {
    id: 'mat-g4-034',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Area',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'A área de um círculo com raio 3 cm e π = 3,14 é _ cm².',
    correctAnswer: '28,26',
    explanation: 'Área = π × r² = 3,14 × 3² = 3,14 × 9 = 28,26 cm².',
  },
  {
    id: 'mat-g4-035',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Probabilidades',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ao lançar uma moeda 2 vezes, qual a probabilidade de sair 2 caras?',
    options: ['1/2', '1/3', '1/4', '1/6'],
    correctAnswer: '1/4',
    explanation: 'A probabilidade de 2 caras é 1/2 × 1/2 = 1/4.',
  },
  {
    id: 'mat-g4-036',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Proporcionalidade',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Se 5 kg de fruta custam 7,50€, quanto custam 8 kg?',
    options: ['10,00€', '12,00€', '15,00€', '12,50€'],
    correctAnswer: '12,00€',
    explanation: '1 kg custa 7,50 ÷ 5 = 1,50€. 8 kg custam 8 × 1,50 = 12,00€.',
  },
  {
    id: 'mat-g4-037',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Fracoes',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o resultado de 5/8 - 3/8?',
    options: ['1/4', '2/8', '1/2', '3/4'],
    correctAnswer: '1/4',
    explanation: '5/8 - 3/8 = 2/8 = 1/4.',
  },
  {
    id: 'mat-g4-038',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Decimal',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '2,5 × 4 = _',
    correctAnswer: '10,0',
    explanation: '2,5 × 4 = 10,0.',
  },
  {
    id: 'mat-g4-039',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Perimetros',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'O perímetro de um losango com 6 cm de lado é _ cm.',
    correctAnswer: '24',
    explanation: 'Perímetro = 4 × 6 = 24 cm.',
  },
  {
    id: 'mat-g4-040',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ana tem o triplo da idade de Pedro e João tem 2 anos a mais que Ana. Se Pedro tem 9 anos, quantos anos tem João?',
    options: ['27', '29', '30', '28'],
    correctAnswer: '29',
    explanation: 'Ana tem 3 × 9 = 27 anos. João tem 27 + 2 = 29 anos.',
  },

  // ============================================
  // MATEMATICA - GRADE 1 (MORE)
  // ============================================
  {
    id: 'mat-g1-041',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Estimativas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é a estimativa mais próxima de 19 + 22?',
    options: ['30', '40', '50', '60'],
    correctAnswer: '40',
    explanation: '19 + 22 = 41, que está mais próximo de 40 do que de 50.',
  },
  {
    id: 'mat-g1-042',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Resolução de Problemas em 2 Passos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'João tem 5 euros. Compra um lápis por 2 euros e outro por 1 euro. Quanto sobra?',
    options: ['1 euro', '2 euros', '3 euros', '4 euros'],
    correctAnswer: '2 euros',
    explanation: 'Gastou 2 + 1 = 3 euros. 5 - 3 = 2 euros sobram.',
  },
  {
    id: 'mat-g1-043',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Estimativas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Uma estimativa de 23 + 31 é aproximadamente:',
    options: ['40', '50', '60', '70'],
    correctAnswer: '50',
    explanation: '23 + 31 = 54, a estimativa mais próxima é 50.',
  },
  {
    id: 'mat-g1-044',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Resolução de Problemas em 2 Passos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Maria tem 12 rebuçados. Dá 3 ao João e 4 à Ana. Quantos rebuçados tem?',
    options: ['3', '5', '6', '8'],
    correctAnswer: '5',
    explanation: 'Deu 3 + 4 = 7. 12 - 7 = 5 rebuçados.',
  },

  // ============================================
  // MATEMATICA - GRADE 2 (MORE)
  // ============================================
  {
    id: 'mat-g2-041',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Estimativas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a estimativa mais próxima de 245 + 178:',
    options: ['300', '350', '420', '520'],
    correctAnswer: '420',
    explanation: '245 + 178 = 423. A estimativa mais próxima é 420.',
  },
  {
    id: 'mat-g2-042',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Resolução de Problemas em 2 Passos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ana comprou 3 canetas a 150 cêntimos cada e uma borracha a 50 cêntimos. Quanto gastou?',
    options: ['400 cêntimos', '450 cêntimos', '500 cêntimos', '550 cêntimos'],
    correctAnswer: '500 cêntimos',
    explanation: '3 × 150 = 450. 450 + 50 = 500 cêntimos.',
  },
  {
    id: 'mat-g2-043',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Divisão com Resto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ao dividir 13 por 5, qual é o resto?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '3',
    explanation: '13 ÷ 5 = 2 com resto 3. Porque 2 × 5 = 10 e 13 - 10 = 3.',
  },
  {
    id: 'mat-g2-044',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Divisão com Resto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ao dividir 17 por 4, qual é o quociente?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '4',
    explanation: '17 ÷ 4 = 4 com resto 1. O quociente é 4.',
  },

  // ============================================
  // MATEMATICA - GRADE 3 (MORE)
  // ============================================
  {
    id: 'mat-g3-041',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Estimativas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a estimativa à centena mais próxima de 673?',
    options: ['600', '650', '700', '750'],
    correctAnswer: '700',
    explanation: '673 está a 73 unidades de 600 e a 27 unidades de 700. 700 é mais próxima.',
  },
  {
    id: 'mat-g3-042',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Resolução de Problemas em 2 Passos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Luís tem 120 euros. Comprou um livro por 35 euros e outro por 28 euros. Quanto sobra?',
    options: ['47 euros', '57 euros', '67 euros', '77 euros'],
    correctAnswer: '57 euros',
    explanation: 'Gastou 35 + 28 = 63 euros. 120 - 63 = 57 euros sobram.',
  },
  {
    id: 'mat-g3-043',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisão com Resto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ao dividir 50 por 7, qual é o resto?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '1',
    explanation: '50 ÷ 7 = 7 com resto 1. Porque 7 × 7 = 49 e 50 - 49 = 1.',
  },
  {
    id: 'mat-g3-044',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisão com Resto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: '7 chocolates para 3 crianças. Quantos chocolates recebe cada criança e quantos sobram?',
    options: ['2 cada, sobra 1', '1 cada, sobra 4', '3 cada, sobra 0', '2 cada, sobra 0'],
    correctAnswer: '2 cada, sobra 1',
    explanation: '7 ÷ 3 = 2 cada, resto 1.',
  },

  // ============================================
  // MATEMATICA - GRADE 4 (MORE)
  // ============================================
  {
    id: 'mat-g4-041',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Estimativas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Estime o resultado de 489 × 3 arredondando o primeiro número à centena:',
    options: ['1200', '1300', '1500', '1700'],
    correctAnswer: '1500',
    explanation: '489 ≈ 500. 500 × 3 = 1500.',
  },
  {
    id: 'mat-g4-042',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Resolução de Problemas em 2 Passos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Pedro comprou 5 cadernos a 220 cêntimos cada e 3 lápis a 80 cêntimos cada. Quanto gastou no total?',
    options: ['1100 cêntimos', '1240 cêntimos', '1340 cêntimos', '1400 cêntimos'],
    correctAnswer: '1340 cêntimos',
    explanation: '5 × 220 = 1100. 3 × 80 = 240. 1100 + 240 = 1340 cêntimos.',
  },
  {
    id: 'mat-g4-043',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Divisão com Resto',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ao dividir 157 por 12, qual é o quociente?',
    options: ['12', '13', '14', '15'],
    correctAnswer: '13',
    explanation: '157 ÷ 12 = 13 com resto 1. Porque 12 × 13 = 156.',
  },
  {
    id: 'mat-g4-044',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Divisão com Resto',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: '25 livros para 6 alunos. Quantos livros cada e quantos sobram?',
    options: ['4 cada, sobra 1', '3 cada, sobra 7', '5 cada, sobra 0', '4 cada, sobra 2'],
    correctAnswer: '4 cada, sobra 1',
    explanation: '25 ÷ 6 = 4 cada, com resto 1.',
  },
  {
    id: 'mat-g1-045',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Estimativas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: '14 + 8 está mais próximo de:',
    options: ['10', '20', '30', '40'],
    correctAnswer: '20',
    explanation: '14 + 8 = 22. Está mais próximo de 20 do que de 30.',
  },
  {
    id: 'mat-g2-045',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Resolução de Problemas em 2 Passos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Pedro comprou 4 caixas de lápis com 6 lápis cada. Deu 5 lápis ao João. Quantos lápis ficou Pedro?',
    options: ['15', '17', '19', '24'],
    correctAnswer: '19',
    explanation: '4 × 6 = 24. 24 - 5 = 19 lápis.',
  },
  {
    id: 'mat-g3-045',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Estimativas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Estime o resultado de 512 - 189 arredondando à centena:',
    options: ['300', '320', '350', '400'],
    correctAnswer: '300',
    explanation: '512 ≈ 500 e 189 ≈ 200. 500 - 200 = 300.',
  },
  {
    id: 'mat-g4-045',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Estimativas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Estime 8,7 × 4,1 arredondando:',
    options: ['30', '35', '40', '45'],
    correctAnswer: '35',
    explanation: '8,7 ≈ 9 e 4,1 ≈ 4. 9 × 4 = 36 ≈ 35.',
  },

  // ============================================
  // MATEMATICA - EXPANSAO (GRADES 1-4)
  // ============================================
  {
    id: 'mat-exp-001',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 6 + 7?',
    options: ['11', '12', '13', '14'],
    correctAnswer: '13',
    explanation: '6 + 7 = 13.',
  },
  {
    id: 'mat-exp-002',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'fill_blank',
    question: '11 - _ = 5',
    correctAnswer: '6',
    explanation: '11 - 6 = 5.',
  },
  {
    id: 'mat-exp-003',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '7 × 9 = _',
    correctAnswer: '63',
    explanation: '7 × 9 = 63.',
  },
  {
    id: 'mat-exp-004',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Pedro tem 15 selos e Ana tem o triplo. Quantos selos tem Ana?',
    options: ['30', '35', '40', '45'],
    correctAnswer: '45',
    explanation: '15 × 3 = 45 selos.',
  },
  {
    id: 'mat-exp-005',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Fracoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual fração é equivalente a 3/6?',
    options: ['1/2', '1/3', '2/3', '1/4'],
    correctAnswer: '1/2',
    explanation: '3/6 = 1/2 (simplificando por 3).',
  },
  {
    id: 'mat-exp-006',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Perimetros',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'O perímetro de um triângulo com lados 3 cm, 4 cm e 5 cm é _ cm.',
    correctAnswer: '12',
    explanation: '3 + 4 + 5 = 12 cm.',
  },
  {
    id: 'mat-exp-007',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeros Romanos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número romano para 100?',
    options: ['L', 'C', 'D', 'M'],
    correctAnswer: 'C',
    explanation: 'C representa 100 em números romanos.',
  },
  {
    id: 'mat-exp-008',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Decimal',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '7,5 - 2,8 = _',
    correctAnswer: '4,7',
    explanation: '7,5 - 2,8 = 4,7.',
  },
  {
    id: 'mat-exp-009',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Area',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a área de um triângulo com base 8 cm e altura 5 cm?',
    options: ['13 cm²', '20 cm²', '40 cm²', '45 cm²'],
    correctAnswer: '20 cm²',
    explanation: 'Área = (8 × 5) / 2 = 20 cm².',
  },
  {
    id: 'mat-exp-010',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Proporcionalidade',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Se 2 metros de tecido custam 6€, quanto custam 5 metros?',
    options: ['12€', '15€', '18€', '20€'],
    correctAnswer: '15€',
    explanation: '1 metro custa 3€. 5 metros custam 15€.',
  },
  {
    id: 'mat-exp-011',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que forma tem 5 lados?',
    options: ['Quadrado', 'Pentágono', 'Hexágono', 'Triângulo'],
    correctAnswer: 'Pentágono',
    explanation: 'Um pentágono tem 5 lados.',
  },
  {
    id: 'mat-exp-012',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'true_false',
    question: '6 × 7 = 42',
    correctAnswer: 'true',
    explanation: '6 × 7 = 42 está correto.',
  },
  {
    id: 'mat-exp-013',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '96 ÷ 8 = _',
    correctAnswer: '12',
    explanation: '96 ÷ 8 = 12.',
  },
  {
    id: 'mat-exp-014',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Percentagens',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '50% de 60 = _',
    correctAnswer: '30',
    explanation: '50% de 60 = 60 × 0,5 = 30.',
  },
  {
    id: 'mat-exp-015',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Comparacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é menor: 25 ou 52?',
    options: ['25', '52', 'São iguais', 'Nenhuma'],
    correctAnswer: '25',
    explanation: '25 é menor que 52.',
  },
  {
    id: 'mat-exp-016',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos minutos tem 3 horas?',
    options: ['90', '120', '150', '180'],
    correctAnswer: '180',
    explanation: '3 × 60 = 180 minutos.',
  },
  {
    id: 'mat-exp-017',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Area',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a área de um quadrado com 6 cm de lado?',
    options: ['12 cm²', '24 cm²', '36 cm²', '48 cm²'],
    correctAnswer: '36 cm²',
    explanation: '6 × 6 = 36 cm².',
  },
  {
    id: 'mat-exp-018',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Multiplicacao',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '35 × 13 = _',
    correctAnswer: '455',
    explanation: '35 × 13 = 455.',
  },
];
