import { Question } from './index';

export const matematicaQuestions: Question[] = [
  // ============================================
  // MATEMATICA - GRADE 1
  // ============================================
  {
    id: 'mat-g1-001',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 3 + 4?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '7',
    explanation: '3 + 4 = 7.',
  },
  {
    id: 'mat-g1-002',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 10 - 3?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '7',
    explanation: '10 - 3 = 7.',
  },
  {
    id: 'mat-g1-003',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Contagem',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que número vem depois do 15?',
    options: ['14', '16', '17', '13'],
    correctAnswer: '16',
    explanation: 'O número que segue o 15 é o 16.',
  },
  {
    id: 'mat-g1-004',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'fill_blank',
    question: '5 + _ = 9',
    correctAnswer: '4',
    explanation: '5 + 4 = 9.',
  },
  {
    id: 'mat-g1-005',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos lados tem um triângulo?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'Um triângulo tem 3 lados.',
  },
  {
    id: 'mat-g1-006',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é o número por extenso do algarismo 7?',
    options: ['Cinco', 'Seis', 'Sete', 'Oito'],
    correctAnswer: 'Sete',
    explanation: 'O algarismo 7 escreve-se "sete".',
  },
  {
    id: 'mat-g1-007',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 2 + 2 + 2?',
    options: ['4', '5', '6', '7'],
    correctAnswer: '6',
    explanation: '2 + 2 + 2 = 6.',
  },
  {
    id: 'mat-g1-008',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Comparacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é maior: 8 ou 6?',
    options: ['6', '8', 'São iguais', 'Nenhuma'],
    correctAnswer: '8',
    explanation: '8 é maior que 6.',
  },
  {
    id: 'mat-g1-009',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'true_false',
    question: '9 - 5 = 4',
    correctAnswer: 'true',
    explanation: '9 - 5 = 4 é correto.',
  },
  {
    id: 'mat-g1-010',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos lados tem um quadrado?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '4',
    explanation: 'Um quadrado tem 4 lados iguais.',
  },
  {
    id: 'mat-g1-011',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 8 + 5?',
    options: ['12', '13', '14', '15'],
    correctAnswer: '13',
    explanation: '8 + 5 = 13.',
  },
  {
    id: 'mat-g1-012',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 14 - 6?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: '14 - 6 = 8.',
  },
  {
    id: 'mat-g1-013',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual forma tem lados curvos e nenhum canto?',
    options: ['Triângulo', 'Quadrado', 'Círculo', 'Retângulo'],
    correctAnswer: 'Círculo',
    explanation: 'O círculo tem lados curvos e nenhum canto.',
  },
  {
    id: 'mat-g1-014',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'O número 10 é formado por _ dezena(s).',
    correctAnswer: '1',
    explanation: 'O número 10 tem 1 dezena.',
  },
  {
    id: 'mat-g1-015',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'true_false',
    question: '7 + 3 = 10',
    correctAnswer: 'true',
    explanation: '7 + 3 = 10 está correto.',
  },
  {
    id: 'mat-g1-016',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Comparacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é menor: 12 ou 21?',
    options: ['12', '21', 'São iguais', 'Nenhuma'],
    correctAnswer: '12',
    explanation: '12 é menor que 21.',
  },
  {
    id: 'mat-g1-017',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Contagem',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que número vem antes do 10?',
    options: ['8', '9', '11', '12'],
    correctAnswer: '9',
    explanation: 'O número antes de 10 é o 9.',
  },
  {
    id: 'mat-g1-018',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'true_false',
    question: 'Um retângulo tem 4 lados.',
    correctAnswer: 'true',
    explanation: 'Um retângulo tem 4 lados, sendo 2 pares de lados iguais.',
  },
  {
    id: 'mat-g1-019',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas unidades tem o número 7?',
    options: ['7', '1', '10', '70'],
    correctAnswer: '7',
    explanation: 'O número 7 tem 7 unidades.',
  },
  {
    id: 'mat-g1-020',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'fill_blank',
    question: '12 - _ = 8',
    correctAnswer: '4',
    explanation: '12 - 4 = 8.',
  },

  // ============================================
  // MATEMATICA - GRADE 2
  // ============================================
  {
    id: 'mat-g2-001',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 25 + 37?',
    options: ['52', '62', '72', '82'],
    correctAnswer: '62',
    explanation: '25 + 37 = 62.',
  },
  {
    id: 'mat-g2-002',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '3 × 4 = _',
    correctAnswer: '12',
    explanation: '3 × 4 = 12.',
  },
  {
    id: 'mat-g2-003',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos cantos tem um retângulo?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '4',
    explanation: 'Um retângulo tem 4 cantos (vértices).',
  },
  {
    id: 'mat-g2-004',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 100 - 45?',
    options: ['45', '55', '65', '75'],
    correctAnswer: '55',
    explanation: '100 - 45 = 55.',
  },
  {
    id: 'mat-g2-005',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: '5 × 6 = ?',
    options: ['25', '30', '35', '20'],
    correctAnswer: '30',
    explanation: '5 × 6 = 30.',
  },
  {
    id: 'mat-g2-006',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos centímetros tem 1 metro?',
    options: ['10', '50', '100', '1000'],
    correctAnswer: '100',
    explanation: '1 metro = 100 centímetros.',
  },
  {
    id: 'mat-g2-007',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '8 × 7 = _',
    correctAnswer: '56',
    explanation: '8 × 7 = 56.',
  },
  {
    id: 'mat-g2-008',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Maria tem 12 rebuçados e deu 5 ao João. Quantos rebuçados tem Maria agora?',
    options: ['5', '6', '7', '17'],
    correctAnswer: '7',
    explanation: '12 - 5 = 7 rebuçados.',
  },
  {
    id: 'mat-g2-009',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número que fica entre o 29 e o 31?',
    options: ['28', '30', '32', '29'],
    correctAnswer: '30',
    explanation: 'O número entre 29 e 31 é 30.',
  },
  {
    id: 'mat-g2-010',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'true_false',
    question: '9 × 3 = 27',
    correctAnswer: 'true',
    explanation: '9 × 3 = 27 está correto.',
  },
  {
    id: 'mat-g2-011',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 68 + 45?',
    options: ['103', '113', '123', '133'],
    correctAnswer: '113',
    explanation: '68 + 45 = 113.',
  },
  {
    id: 'mat-g2-012',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '7 × _ = 42',
    correctAnswer: '6',
    explanation: '7 × 6 = 42.',
  },
  {
    id: 'mat-g2-013',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número ímpar entre 10 e 14?',
    options: ['10', '11', '12', '14'],
    correctAnswer: '11',
    explanation: '11 é o único número ímpar entre 10 e 14.',
  },
  {
    id: 'mat-g2-014',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Formas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual forma tem 6 faces iguais?',
    options: ['Cubo', 'Esfera', 'Cone', 'Cilindro'],
    correctAnswer: 'Cubo',
    explanation: 'O cubo tem 6 faces quadradas e iguais.',
  },
  {
    id: 'mat-g2-015',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'true_false',
    question: '1 hora = 60 minutos.',
    correctAnswer: 'true',
    explanation: 'Uma hora tem exatamente 60 minutos.',
  },
  {
    id: 'mat-g2-016',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 9 × 9?',
    options: ['72', '81', '91', '99'],
    correctAnswer: '81',
    explanation: '9 × 9 = 81.',
  },
  {
    id: 'mat-g2-017',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'João tem 8 anos e a irmã tem o dobro. Quantos anos tem a irmã?',
    options: ['12', '14', '16', '18'],
    correctAnswer: '16',
    explanation: '8 × 2 = 16 anos.',
  },
  {
    id: 'mat-g2-018',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos eixos de simetria tem um quadrado?',
    options: ['1', '2', '4', '8'],
    correctAnswer: '4',
    explanation: 'O quadrado tem 4 eixos de simetria.',
  },
  {
    id: 'mat-g2-019',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '5 dezenas e 3 unidades = _',
    correctAnswer: '53',
    explanation: '5 dezenas (50) + 3 unidades (3) = 53.',
  },
  {
    id: 'mat-g2-020',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: '6 × 8 = ?',
    options: ['42', '48', '54', '56'],
    correctAnswer: '48',
    explanation: '6 × 8 = 48.',
  },

  // ============================================
  // MATEMATICA - GRADE 3
  // ============================================
  {
    id: 'mat-g3-001',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 156 + 278?',
    options: ['424', '434', '444', '454'],
    correctAnswer: '434',
    explanation: '156 + 278 = 434.',
  },
  {
    id: 'mat-g3-002',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 48 ÷ 6?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: '48 ÷ 6 = 8.',
  },
  {
    id: 'mat-g3-003',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Fracoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que fração representa metade de um todo?',
    options: ['1/3', '1/2', '1/4', '2/3'],
    correctAnswer: '1/2',
    explanation: 'Metade é representada pela fração 1/2.',
  },
  {
    id: 'mat-g3-004',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos graus tem um ângulo reto?',
    options: ['45°', '60°', '90°', '180°'],
    correctAnswer: '90°',
    explanation: 'Um ângulo reto mede exatamente 90 graus.',
  },
  {
    id: 'mat-g3-005',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos quilogramas tem 1 tonelada?',
    options: ['100', '500', '1000', '10000'],
    correctAnswer: '1000',
    explanation: '1 tonelada = 1000 quilogramas.',
  },
  {
    id: 'mat-g3-006',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Pedro comprou 3 cadernos a 150$ cada. Quanto gastou no total?',
    options: ['350$', '400$', '450$', '500$'],
    correctAnswer: '450$',
    explanation: '3 × 150$ = 450$.',
  },
  {
    id: 'mat-g3-007',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'O número 356 tem _ centenas, _ dezenas e _ unidades.',
    correctAnswer: '3,5,6',
    explanation: '356 = 3 centenas + 5 dezenas + 6 unidades.',
  },
  {
    id: 'mat-g3-008',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Perimetros',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o perímetro de um quadrado com 5 cm de lado?',
    options: ['10 cm', '15 cm', '20 cm', '25 cm'],
    correctAnswer: '20 cm',
    explanation: 'Perímetro = 4 × 5 cm = 20 cm.',
  },
  {
    id: 'mat-g3-009',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '12 × 9 = _',
    correctAnswer: '108',
    explanation: '12 × 9 = 108.',
  },
  {
    id: 'mat-g3-010',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'true_false',
    question: '250 + 350 = 600',
    correctAnswer: 'true',
    explanation: '250 + 350 = 600 está correto.',
  },
  {
    id: 'mat-g3-011',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Fracoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual fração é equivalente a 1/2?',
    options: ['2/3', '2/4', '3/4', '1/3'],
    correctAnswer: '2/4',
    explanation: '2/4 = 1/2 (podemos simplificar dividindo por 2).',
  },
  {
    id: 'mat-g3-012',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '72 ÷ 8 = _',
    correctAnswer: '9',
    explanation: '72 ÷ 8 = 9.',
  },
  {
    id: 'mat-g3-013',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos minutos tem 2 horas?',
    options: ['60', '90', '100', '120'],
    correctAnswer: '120',
    explanation: '2 horas × 60 minutos = 120 minutos.',
  },
  {
    id: 'mat-g3-014',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos triângulos formam um losango?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'Um losango pode ser dividido em 2 triângulos retângulos.',
  },
  {
    id: 'mat-g3-015',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ana comprou 4 caixas de lápis com 12 lápis cada. Quantos lápis tem no total?',
    options: ['36', '42', '48', '52'],
    correctAnswer: '48',
    explanation: '4 × 12 = 48 lápis.',
  },
  {
    id: 'mat-g3-016',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Area',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a área de um quadrado com 4 cm de lado?',
    options: ['8 cm²', '12 cm²', '16 cm²', '20 cm²'],
    correctAnswer: '16 cm²',
    explanation: 'Área = 4 × 4 = 16 cm².',
  },
  {
    id: 'mat-g3-017',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o dobro de 45?',
    options: ['80', '85', '90', '95'],
    correctAnswer: '90',
    explanation: '45 × 2 = 90.',
  },
  {
    id: 'mat-g3-018',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '156 - _ = 89',
    correctAnswer: '67',
    explanation: '156 - 67 = 89.',
  },
  {
    id: 'mat-g3-019',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'true_false',
    question: '15 × 6 = 90',
    correctAnswer: 'true',
    explanation: '15 × 6 = 90 está correto.',
  },
  {
    id: 'mat-g3-020',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos mililitros tem 1 litro?',
    options: ['100', '500', '1000', '10000'],
    correctAnswer: '1000',
    explanation: '1 litro = 1000 mililitros.',
  },

  // ============================================
  // MATEMATICA - GRADE 4
  // ============================================
  {
    id: 'mat-g4-001',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Aritmetica',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quanto é 1234 + 5678?',
    options: ['6812', '6912', '7012', '7112'],
    correctAnswer: '6912',
    explanation: '1234 + 5678 = 6912.',
  },
  {
    id: 'mat-g4-002',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Fracoes',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o resultado de 1/4 + 1/4?',
    options: ['1/2', '2/8', '2/4', '1/8'],
    correctAnswer: '1/2',
    explanation: '1/4 + 1/4 = 2/4 = 1/2.',
  },
  {
    id: 'mat-g4-003',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Geometria',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quantos triângulos tem numa estrela de 5 pontas?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'Uma estrela de 5 pontas tem 5 triângulos.',
  },
  {
    id: 'mat-g4-004',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ana tem o triplo da idade de Pedro. Se Pedro tem 8 anos, quantos anos tem Ana?',
    options: ['16', '24', '21', '18'],
    correctAnswer: '24',
    explanation: '3 × 8 = 24 anos.',
  },
  {
    id: 'mat-g4-005',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Decimal',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 3,5 + 2,7?',
    options: ['5,2', '6,2', '7,2', '8,2'],
    correctAnswer: '6,2',
    explanation: '3,5 + 2,7 = 6,2.',
  },
  {
    id: 'mat-g4-006',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Area',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a área de um retângulo com 8 cm de comprimento e 5 cm de largura?',
    options: ['13 cm²', '30 cm²', '40 cm²', '45 cm²'],
    correctAnswer: '40 cm²',
    explanation: 'Área = 8 × 5 = 40 cm².',
  },
  {
    id: 'mat-g4-007',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Multiplicacao',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '25 × 12 = _',
    correctAnswer: '300',
    explanation: '25 × 12 = 300.',
  },
  {
    id: 'mat-g4-008',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Um comboio parte às 14h30 e chega ao destino às 16h45. Quanto tempo durou a viagem?',
    options: ['1h15', '2h15', '2h30', '3h15'],
    correctAnswer: '2h15',
    explanation: 'Das 14h30 às 16h45 são 2 horas e 15 minutos.',
  },
  {
    id: 'mat-g4-009',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Divisao',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '144 ÷ 12 = _',
    correctAnswer: '12',
    explanation: '144 ÷ 12 = 12.',
  },
  {
    id: 'mat-g4-010',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número par entre o 17 e o 21?',
    options: ['17', '18', '19', '20'],
    correctAnswer: '18',
    explanation: 'Os números pares entre 17 e 21 são 18 e 20. O primeiro é 18.',
  },
  {
    id: 'mat-g4-011',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Decimal',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '6,8 - 3,5 = _',
    correctAnswer: '3,3',
    explanation: '6,8 - 3,5 = 3,3.',
  },
  {
    id: 'mat-g4-012',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Fracoes',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o resultado de 3/4 - 1/4?',
    options: ['1/2', '2/4', '2/8', '3/8'],
    correctAnswer: '1/2',
    explanation: '3/4 - 1/4 = 2/4 = 1/2.',
  },
  {
    id: 'mat-g4-013',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Perimetros',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o perímetro de um retângulo com 7 cm de comprimento e 3 cm de largura?',
    options: ['10 cm', '14 cm', '20 cm', '21 cm'],
    correctAnswer: '20 cm',
    explanation: 'Perímetro = 2 × (7 + 3) = 20 cm.',
  },
  {
    id: 'mat-g4-014',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Multiplicacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quanto é 156 × 3?',
    options: ['458', '468', '478', '488'],
    correctAnswer: '468',
    explanation: '156 × 3 = 468.',
  },
  {
    id: 'mat-g4-015',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Um pacote tem 24 lápis. Se distribuirmos por 6 alunos, quantos lápis recebe cada um?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '4',
    explanation: '24 ÷ 6 = 4 lápis por aluno.',
  },
  {
    id: 'mat-g4-016',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Area',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'A área de um triângulo com base 10 cm e altura 6 cm é _ cm².',
    correctAnswer: '30',
    explanation: 'Área = (10 × 6) / 2 = 30 cm².',
  },
  {
    id: 'mat-g4-017',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o triplo de 27?',
    options: ['54', '72', '81', '90'],
    correctAnswer: '81',
    explanation: '27 × 3 = 81.',
  },
  {
    id: 'mat-g4-018',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Aritmetica',
    difficulty: 'hard',
    type: 'true_false',
    question: '245 + 378 = 623',
    correctAnswer: 'true',
    explanation: '245 + 378 = 623 está correto.',
  },
  {
    id: 'mat-g4-019',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Divisao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quanto é 225 ÷ 5?',
    options: ['40', '45', '50', '55'],
    correctAnswer: '45',
    explanation: '225 ÷ 5 = 45.',
  },
  {
    id: 'mat-g4-020',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Geometria',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quantos eixos de simetria tem um retângulo (que não é quadrado)?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'Um retângulo tem 2 eixos de simetria.',
  },
];
