import { Question } from './index';

export const portuguesQuestions: Question[] = [
  // ============================================
  // PORTUGUES - GRADE 1
  // ============================================
  {
    id: 'pt-g1-001',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas vogais tem o alfabeto português?',
    options: ['3', '5', '7', '6'],
    correctAnswer: '5',
    explanation: 'O alfabeto português tem 5 vogais: A, E, I, O, U.',
  },
  {
    id: 'pt-g1-002',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'A, E, I, O, _',
    correctAnswer: 'U',
    explanation: 'A última vogal é o U.',
  },
  {
    id: 'pt-g1-003',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Consoantes',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual das seguintes é uma consoante?',
    options: ['A', 'B', 'I', 'O'],
    correctAnswer: 'B',
    explanation: 'B é uma consoante. A, I e O são vogais.',
  },
  {
    id: 'pt-g1-004',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas sílabas tem a palavra "maçã"?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'Ma-çã tem 2 sílabas.',
  },
  {
    id: 'pt-g1-005',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a divisão em sílabas da palavra "borboleta"?',
    options: ['bor-bo-le-ta', 'borb-o-le-ta', 'bor-bo-let-a', 'bo-rbo-le-ta'],
    correctAnswer: 'bor-bo-le-ta',
    explanation: 'Bor-bo-le-ta tem 4 sílabas.',
  },
  {
    id: 'pt-g1-006',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Palavras',
    difficulty: 'easy',
    type: 'true_false',
    question: 'A palavra "casa" tem 4 letras.',
    correctAnswer: 'true',
    explanation: 'C-A-S-A = 4 letras.',
  },
  {
    id: 'pt-g1-007',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é a vogal que está na palavra "sol"?',
    options: ['A', 'E', 'I', 'O'],
    correctAnswer: 'O',
    explanation: 'A palavra "sol" tem a vogal O.',
  },
  {
    id: 'pt-g1-008',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Palavras',
    difficulty: 'easy',
    type: 'true_false',
    question: 'A palavra "amor" começa com uma vogal.',
    correctAnswer: 'true',
    explanation: 'A palavra "amor" começa com A, que é uma vogal.',
  },
  {
    id: 'pt-g1-009',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Consoantes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantas consoantes tem a palavra "mãe"?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'M-Ã-E: M e ã são as letras, mas M é consoante e ã é vogal. A palavra tem 2 consoantes (M e a segunda letra é vogal).',
  },
  {
    id: 'pt-g1-010',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Pontuacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que sinal de pontuação usamos no final de uma frase que é uma pergunta?',
    options: ['Ponto', 'Vírgula', 'Ponto de interrogação', 'Ponto e vírgula'],
    correctAnswer: 'Ponto de interrogação',
    explanation: 'As frases de pergunta terminam com ponto de interrogação (?).',
  },
  {
    id: 'pt-g1-011',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Genero',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é o género da palavra "menina"?',
    options: ['Masculino', 'Feminino', 'Neutro', 'Plural'],
    correctAnswer: 'Feminino',
    explanation: '"Menina" é uma palavra do género feminino.',
  },
  {
    id: 'pt-g1-012',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Numero',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é o plural de "gato"?',
    options: ['gatos', 'gatos', 'gatoes', 'gata'],
    correctAnswer: 'gatos',
    explanation: 'O plural de "gato" é "gatos".',
  },
  {
    id: 'pt-g1-013',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Artigos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual artigo usamos antes de "menino"?',
    options: ['A', 'O', 'As', 'Um'],
    correctAnswer: 'O',
    explanation: '"Menino" é masculino singular, por isso usamos "o".',
  },
  {
    id: 'pt-g1-014',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Preposicoes',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'O gato está _ mesa.',
    correctAnswer: 'em',
    explanation: 'A preposição correta é "em": o gato está em cima da mesa.',
  },
  {
    id: 'pt-g1-015',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Verbos',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'Nós _ (correr) no parque.',
    correctAnswer: 'corremos',
    explanation: 'Nós corremos é a primeira pessoa do plural do presente do indicativo.',
  },
  {
    id: 'pt-g1-016',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Pronomes',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual pronome completa: _ sou aluno.',
    options: ['Tu', 'Eu', 'Ele', 'Nós'],
    correctAnswer: 'Eu',
    explanation: 'Na primeira pessoa do singular, usamos "Eu".',
  },
  {
    id: 'pt-g1-017',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Consoantes',
    difficulty: 'easy',
    type: 'true_false',
    question: 'A letra "S" é uma consoante.',
    correctAnswer: 'true',
    explanation: 'S é uma consoante, não é uma vogal.',
  },
  {
    id: 'pt-g1-018',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas sílabas tem a palavra "escola"?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'Es-co-la tem 3 sílabas.',
  },
  {
    id: 'pt-g1-019',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Adjetivos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual adjetivo descreve o tamanho: "O elefante é _"?',
    options: ['Bonito', 'Grande', 'Rápido', 'Azul'],
    correctAnswer: 'Grande',
    explanation: '"Grande" é um adjetivo que descreve o tamanho.',
  },
  {
    id: 'pt-g1-020',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Conjuncoes',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que conjunção usamos para juntar ideias: "Eu gosto de leite _ de sumo"?',
    options: ['Mas', 'E', 'Ou', 'Porque'],
    correctAnswer: 'E',
    explanation: '"E" é uma conjunção aditiva que junta ideias.',
  },

  // ============================================
  // PORTUGUES - GRADE 2
  // ============================================
  {
    id: 'pt-g2-001',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual das palavras abaixo tem um ditongo?',
    options: ['casa', 'leite', 'amor', 'sol'],
    correctAnswer: 'leite',
    explanation: 'Leite tem o ditongo "ei".',
  },
  {
    id: 'pt-g2-002',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Acentuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'A palavra "café" é acentuada em qual sílaba?',
    options: ['Primeira', 'Segunda', 'Última', 'Penúltima'],
    correctAnswer: 'Última',
    explanation: 'Ca-FÉ é acentuada na última sílaba.',
  },
  {
    id: 'pt-g2-003',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Genero e Numero',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o plural de "cão"?',
    options: ['cãos', 'cães', 'cões', 'cãos'],
    correctAnswer: 'cães',
    explanation: 'O plural de "cão" é "cães".',
  },
  {
    id: 'pt-g2-004',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Eu _ (comer) uma maçã. (presente do indicativo)',
    correctAnswer: 'como',
    explanation: 'Eu como é a primeira pessoa do singular do presente do indicativo do verbo comer.',
  },
  {
    id: 'pt-g2-005',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Artigos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual artigo está correto: _ gato dormiu?',
    options: ['O', 'A', 'Os', 'As'],
    correctAnswer: 'O',
    explanation: 'Gato é masculino singular, por isso usamos "o".',
  },
  {
    id: 'pt-g2-006',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Adjetivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Na frase "O menino é alto", qual é o adjetivo?',
    options: ['menino', 'alto', 'é', 'O'],
    correctAnswer: 'alto',
    explanation: '"Alto" é o adjetivo que descreve o menino.',
  },
  {
    id: 'pt-g2-007',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A palavra "pão" tem um ditongo nasal.',
    correctAnswer: 'true',
    explanation: '"ão" é um ditongo nasal.',
  },
  {
    id: 'pt-g2-008',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que sinal usamos para separar enumerações numa frase?',
    options: ['Ponto', 'Vírgula', 'Dois pontos', 'Ponto e vírgula'],
    correctAnswer: 'Vírgula',
    explanation: 'A vírgula separa elementos numa enumeração.',
  },
  {
    id: 'pt-g2-009',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Nós _ (brincar) no parque. (presente do indicativo)',
    correctAnswer: 'brincamos',
    explanation: 'Nós brincamos é a primeira pessoa do plural do presente do indicativo.',
  },
  {
    id: 'pt-g2-010',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Pronomes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o pronome pessoal correto: _ estou a estudar?',
    options: ['Tu', 'Eu', 'Ele', 'Nós'],
    correctAnswer: 'Eu',
    explanation: 'Na primeira pessoa do singular, usamos "Eu".',
  },
  {
    id: 'pt-g2-011',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Substantivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual substantivo é coletivo de "peixes"?',
    options: ['Cardume', 'Alcateia', 'Bando', 'Manada'],
    correctAnswer: 'Cardume',
    explanation: 'Cardume é o coletivo de peixes.',
  },
  {
    id: 'pt-g2-012',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Tu _ (falar) português. (presente do indicativo)',
    correctAnswer: 'falas',
    explanation: 'Tu falas é a segunda pessoa do singular do presente do indicativo.',
  },
  {
    id: 'pt-g2-013',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual palavra tem o ditongo "ou"?',
    options: ['casa', 'ouro', 'mesa', 'livro'],
    correctAnswer: 'ouro',
    explanation: 'A palavra "ouro" tem o ditongo "ou".',
  },
  {
    id: 'pt-g2-014',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Adverbios',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "Ela canta bem", que tipo de advérbio é "bem"?',
    options: ['Lugar', 'Tempo', 'Modo', 'Quantidade'],
    correctAnswer: 'Modo',
    explanation: '"Bem" é um advérbio de modo.',
  },
  {
    id: 'pt-g2-015',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Preposicoes',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Vou _ escola todos os dias.',
    correctAnswer: 'à',
    explanation: 'A preposição "a" contrai-se com o artigo "a" formando "à".',
  },
  {
    id: 'pt-g2-016',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual verbo completa: "Nós _ livros todos os dias"?',
    options: ['leio', 'leem', 'leemos', 'leia'],
    correctAnswer: 'leemos',
    explanation: 'Nós leemos é a conjugação correta no presente do indicativo.',
  },
  {
    id: 'pt-g2-017',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Acentuacao',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A palavra "lápis" tem acento.',
    correctAnswer: 'true',
    explanation: 'Lápis tem acento no "a" porque é palavra oxítona terminada em "i".',
  },
  {
    id: 'pt-g2-018',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Palavras',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o radical da palavra "bonita"?',
    options: ['bonit', 'bonita', 'boni', 'ta'],
    correctAnswer: 'bonit',
    explanation: 'O radical de "bonita" é "bonit".',
  },
  {
    id: 'pt-g2-019',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Conjuncoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que conjunção indica causa: "Estou cansado _ não dormi bem"?',
    options: ['Mas', 'Porque', 'Então', 'Embora'],
    correctAnswer: 'Porque',
    explanation: '"Porque" indica a causa ou razão.',
  },
  {
    id: 'pt-g2-020',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Genero e Numero',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o feminino de "actor"?',
    options: ['actriz', 'actora', 'actoressa', 'actora'],
    correctAnswer: 'actriz',
    explanation: 'O feminino de "actor" é "actriz".',
  },

  // ============================================
  // PORTUGUES - GRADE 3
  // ============================================
  {
    id: 'pt-g3-001',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual está escrito corretamente?',
    options: ['Excessão', 'Exceção', 'Exeção', 'Exceçao'],
    correctAnswer: 'Exceção',
    explanation: 'A forma correta é "exceção".',
  },
  {
    id: 'pt-g3-002',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Tempos Verbais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "Ontem eu estudei", que tempo verbal é "estudei"?',
    options: ['Presente', 'Pretérito Perfeito', 'Pretérito Imperfeito', 'Futuro'],
    correctAnswer: 'Pretérito Perfeito',
    explanation: '"Estudei" está no pretérito perfeito do indicativo.',
  },
  {
    id: 'pt-g3-003',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Conjunções',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual conjunção indica oposição?',
    options: ['E', 'Mas', 'Porque', 'Então'],
    correctAnswer: 'Mas',
    explanation: '"Mas" é uma conjunção adversativa que indica oposição.',
  },
  {
    id: 'pt-g3-004',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Substantivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o coletivo de "lobos"?',
    options: ['Alcateia', 'Manada', 'Bando', 'Cardume'],
    correctAnswer: 'Alcateia',
    explanation: 'O coletivo de lobos é "alcateia".',
  },
  {
    id: 'pt-g3-005',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Compreensao de Leitura',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num texto narrativo, quem conta a história?',
    options: ['O narrador', 'O autor', 'O leitor', 'O personagem'],
    correctAnswer: 'O narrador',
    explanation: 'O narrador é quem conta a história no texto narrativo.',
  },
  {
    id: 'pt-g3-006',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Ele _ (ir) à escola todos os dias. (presente do indicativo)',
    correctAnswer: 'vai',
    explanation: 'Ele vai é a terceira pessoa do singular do presente do indicativo do verbo ir.',
  },
  {
    id: 'pt-g3-007',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Adverbios',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "Ele correu rapidamente", que tipo de advérbio é "rapidamente"?',
    options: ['Advérbio de lugar', 'Advérbio de tempo', 'Advérbio de modo', 'Advérbio de quantidade'],
    correctAnswer: 'Advérbio de modo',
    explanation: '"Rapidamente" é um advérbio de modo, pois indica como a ação foi realizada.',
  },
  {
    id: 'pt-g3-008',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O menino jogou a bola", qual é o sujeito?',
    options: ['O menino', 'jogou', 'a bola', 'O menino jogou'],
    correctAnswer: 'O menino',
    explanation: 'O sujeito é quem pratica a ação: "O menino".',
  },
  {
    id: 'pt-g3-009',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Genero e Numero',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o feminino de "herói"?',
    options: ['heroia', 'heroína', 'heroia', 'heroína'],
    correctAnswer: 'heroína',
    explanation: 'O feminino de "herói" é "heroína".',
  },
  {
    id: 'pt-g3-010',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que sinal de pontuação usamos para indicar uma pausa longa?',
    options: ['Vírgula', 'Ponto e vírgula', 'Ponto final', 'Dois pontos'],
    correctAnswer: 'Ponto e vírgula',
    explanation: 'O ponto e vírgula indica uma pausa mais longa que a vírgula.',
  },
  {
    id: 'pt-g3-011',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Substantivos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'A coragem é uma _ (qualidade/defeito) humana.',
    correctAnswer: 'qualidade',
    explanation: 'A coragem é uma qualidade humana positiva.',
  },
  {
    id: 'pt-g3-012',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual palavra está escrita corretamente?',
    options: ['Acontecimento', 'Acontecimento', 'Acontecimento', 'Acontecimento'],
    correctAnswer: 'Acontecimento',
    explanation: 'A forma correta é "acontecimento".',
  },
  {
    id: 'pt-g3-013',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Vocês _ (trabalhar) muito. (presente do indicativo)',
    correctAnswer: 'trabalham',
    explanation: 'Vocês trabalham é a terceira pessoa do plural do presente do indicativo.',
  },
  {
    id: 'pt-g3-014',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Compreensao de Leitura',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é o tema de um texto?',
    options: ['O título', 'A ideia principal', 'O autor', 'O número de páginas'],
    correctAnswer: 'A ideia principal',
    explanation: 'O tema é a ideia principal ou assunto do texto.',
  },
  {
    id: 'pt-g3-015',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Tipos de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual tipo de texto relata factos reais?',
    options: ['Texto narrativo', 'Texto informativo', 'Texto poético', 'Texto descritivo'],
    correctAnswer: 'Texto informativo',
    explanation: 'O texto informativo relata factos reais e objectivos.',
  },
  {
    id: 'pt-g3-016',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Adjetivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o grau comparativo de "bonito"?',
    options: ['Mais bonito', 'Boníssimo', 'Bonito', 'Bem bonito'],
    correctAnswer: 'Mais bonito',
    explanation: 'O grau comparativo de superioridade é "mais bonito".',
  },
  {
    id: 'pt-g3-017',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A vírgula pode ser usada para isolar uma palavra enfática.',
    correctAnswer: 'true',
    explanation: 'Sim, a vírgula isola palavras ou expressões enfáticas na frase.',
  },
  {
    id: 'pt-g3-018',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Conjunções',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual conjunção indica consequência: "Choveu, _ fiquei em casa"?',
    options: ['Mas', 'Embora', 'Portanto', 'Porque'],
    correctAnswer: 'Portanto',
    explanation: '"Portanto" indica consequência ou conclusão.',
  },
  {
    id: 'pt-g3-019',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Que tempo verbal é "Eu tinha estudado"?',
    options: ['Pretérito Perfeito', 'Pretérito Mais-que-perfeito', 'Pretérito Imperfeito', 'Futuro do Pretérito'],
    correctAnswer: 'Pretérito Mais-que-perfeito',
    explanation: '"Tinha estudado" está no pretérito mais-que-perfeito do indicativo.',
  },
  {
    id: 'pt-g3-020',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O livro está na mesa", que complemento é "na mesa"?',
    options: ['Complemento direto', 'Complemento indireto', 'Adjunto adverbial', 'Predicativo'],
    correctAnswer: 'Adjunto adverbial',
    explanation: '"Na mesa" é um adjunto adverbial de lugar.',
  },

  // ============================================
  // PORTUGUES - GRADE 4
  // ============================================
  {
    id: 'pt-g4-001',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O sol sorriu", que figura de linguagem é usada?',
    options: ['Metáfora', 'Comparação', 'Personificação', 'Hipérbole'],
    correctAnswer: 'Personificação',
    explanation: 'O sol não pode sorrir verdadeiramente. Dar características humanas a seres inanimados é personificação.',
  },
  {
    id: 'pt-g4-002',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Verbos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Em "Se eu tivesse estudado, teria passado", que modo verbal é usado?',
    options: ['Indicativo', 'Subjuntivo', 'Imperativo', 'Condicional'],
    correctAnswer: 'Subjuntivo',
    explanation: 'O verbo "tivesse" está no pretérito imperfeito do subjuntivo.',
  },
  {
    id: 'pt-g4-003',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Redacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a estrutura correta de uma introdução de texto dissertativo?',
    options: ['Tese + argumentos', 'Argumentos + conclusão', 'Tese + contextualização', 'Contextualização + tese'],
    correctAnswer: 'Contextualização + tese',
    explanation: 'A introdução deve contextualizar o tema e apresentar a tese.',
  },
  {
    id: 'pt-g4-004',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Expressoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que significa a expressão "chutar o balde"?',
    options: ['Jogar futebol', 'Desistir de tudo', 'Correr muito', 'Estar feliz'],
    correctAnswer: 'Desistir de tudo',
    explanation: '"Chutar o balde" significa desistir ou perder a paciência.',
  },
  {
    id: 'pt-g4-005',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Pontuacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Em "Maria disse: \"Estou cansada.\"", que sinal de pontuação usamos antes de começar a fala?',
    options: ['Vírgula', 'Dois pontos', 'Ponto e vírgula', 'Ponto'],
    correctAnswer: 'Dois pontos',
    explanation: 'Antes de começar uma fala direta, usamos dois pontos.',
  },
  {
    id: 'pt-g4-006',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sinonimos e Antonimos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o sinónimo de "alegre"?',
    options: ['Triste', 'Feliz', 'Cansado', 'Bravo'],
    correctAnswer: 'Feliz',
    explanation: '"Alegre" e "feliz" são sinónimos.',
  },
  {
    id: 'pt-g4-007',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O gato preto dormiu no sofá", qual é o adjunto adnominal?',
    options: ['O gato', 'preto', 'dormiu', 'no sofá'],
    correctAnswer: 'preto',
    explanation: '"Preto" é um adjunto adnominal que modifica o substantivo "gato".',
  },
  {
    id: 'pt-g4-008',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Tempos Verbais',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'Quando eu _ (ter) 18 anos, vou tirar a carta. (futuro do subjuntivo)',
    correctAnswer: 'tiver',
    explanation: 'No futuro do subjuntivo, usamos "tiver" (quando eu tiver).',
  },
  {
    id: 'pt-g4-009',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual está escrito corretamente?',
    options: ['Houve', 'ouve', 'Houvi', 'ouvi'],
    correctAnswer: 'Houve',
    explanation: 'O verbo haver no pretérito perfeito é "houve" com H.',
  },
  {
    id: 'pt-g4-010',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na expressão "Um mar de pessoas", que figura de linguagem é usada?',
    options: ['Hipérbole', 'Metáfora', 'Personificação', 'Onomatopeia'],
    correctAnswer: 'Metáfora',
    explanation: 'Comparar o número de pessoas a um mar é uma metáfora.',
  },
  {
    id: 'pt-g4-011',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sinonimos e Antonimos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o antónimo de "escuro"?',
    options: ['Claro', 'Preto', 'Bonito', 'Pequeno'],
    correctAnswer: 'Claro',
    explanation: 'O antónimo de "escuro" é "claro".',
  },
  {
    id: 'pt-g4-012',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Verbos',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'Se eu _ (saber) a resposta, teria dito. (pretérito imperfeito do subjuntivo)',
    correctAnswer: 'soubesse',
    explanation: 'O pretérito imperfeito do subjuntivo do verbo "saber" é "soubesse".',
  },
  {
    id: 'pt-g4-013',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Tipos de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual tipo de texto pretende convencer o leitor?',
    options: ['Informativo', 'Narrativo', 'Dissuasivo', 'Descritivo'],
    correctAnswer: 'Dissuasivo',
    explanation: 'O texto dissuasivo pretende convencer ou influenciar o leitor.',
  },
  {
    id: 'pt-g4-014',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Expressoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que significa "estar com a língua presa"?',
    options: ['Estar doente', 'Não conseguir falar', 'Estar com fome', 'Estar cansado'],
    correctAnswer: 'Não conseguir falar',
    explanation: 'Estar com a língua presa significa não conseguir falar.',
  },
  {
    id: 'pt-g4-015',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Ortografia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual palavra usa "x" corretamente?',
    options: ['Excesso', 'Excessivo', 'Excessar', 'Excessão'],
    correctAnswer: 'Excessivo',
    explanation: 'A forma correta é "excessivo" com "ss" e não "x".',
  },
  {
    id: 'pt-g4-016',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "Ontem choveu muito", que classe de palavra é "ontem"?',
    options: ['Substantivo', 'Adjetivo', 'Advérbio', 'Verbo'],
    correctAnswer: 'Advérbio',
    explanation: '"Ontem" é um advérbio de tempo.',
  },
  {
    id: 'pt-g4-017',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na expressão "Choviam pedras", que figura de linguagem é usada?',
    options: ['Metáfora', 'Hipérbole', 'Comparação', 'Ironia'],
    correctAnswer: 'Hipérbole',
    explanation: 'Exagerar dizendo que "choviam pedras" é uma hipérbole.',
  },
  {
    id: 'pt-g4-018',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Redacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Numa dissertação argumentativa, a conclusão deve:',
    options: ['Apresentar novos argumentos', 'Repetir a introdução', 'Retomar a tese e sintetizar', 'Fazer perguntas'],
    correctAnswer: 'Retomar a tese e sintetizar',
    explanation: 'A conclusão retoma a tese e sintetiza os argumentos apresentados.',
  },
  {
    id: 'pt-g4-019',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Conjunções',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual conjunção indica condição: "_ estudares, passarás no exame"?',
    options: ['Porque', 'Embora', 'Se', 'Mas'],
    correctAnswer: 'Se',
    explanation: '"Se" é uma conjunção condicional que indica uma condição.',
  },
  {
    id: 'pt-g4-020',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Tempos Verbais',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'Nós _ (ir) ao cinema amanhã. (futuro do indicativo)',
    correctAnswer: 'iremos',
    explanation: 'A primeira pessoa do plural do futuro do indicativo do verbo "ir" é "iremos".',
  },
];
