import { Question } from './index';

export const portuguesQuestions: Question[] = [
  // ============================================
  // PORTUGUES - GRADE 1
  // ============================================
  {
    id: 'pt-g1-001',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas vogais tem o alfabeto português?',
    options: ['3', '5', '7', '6'],
    correctAnswer: '5',
    explanation: 'O alfabeto português tem 5 vogais: A, E, I, O, U.',
  },
  {
    id: 'pt-g1-002',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'A, E, I, O, _',
    correctAnswer: 'U',
    explanation: 'A última vogal é o U.',
  },
  {
    id: 'pt-g1-003',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Consoantes',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual das seguintes é uma consoante?',
    options: ['A', 'B', 'I', 'O'],
    correctAnswer: 'B',
    explanation: 'B é uma consoante. A, I e O são vogais.',
  },
  {
    id: 'pt-g1-004',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas sílabas tem a palavra "maçã"?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'Ma-çã tem 2 sílabas.',
  },
  {
    id: 'pt-g1-005',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a divisão em sílabas da palavra "borboleta"?',
    options: ['bor-bo-le-ta', 'borb-o-le-ta', 'bor-bo-let-a', 'bo-rbo-le-ta'],
    correctAnswer: 'bor-bo-le-ta',
    explanation: 'Bor-bo-le-ta tem 4 sílabas.',
  },
  {
    id: 'pt-g1-006',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Palavras',
    difficulty: 'easy',
    type: 'true_false',
    question: 'A palavra "casa" tem 4 letras.',
    correctAnswer: 'true',
    explanation: 'C-A-S-A = 4 letras.',
  },
  {
    id: 'pt-g1-007',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é a vogal que está na palavra "sol"?',
    options: ['A', 'E', 'I', 'O'],
    correctAnswer: 'O',
    explanation: 'A palavra "sol" tem a vogal O.',
  },
  {
    id: 'pt-g1-008',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Palavras',
    difficulty: 'easy',
    type: 'true_false',
    question: 'A palavra "amor" começa com uma vogal.',
    correctAnswer: 'true',
    explanation: 'A palavra "amor" começa com A, que é uma vogal.',
  },
  {
    id: 'pt-g1-009',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Consoantes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantas consoantes tem a palavra "mãe"?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'M-Ã-E: M e ã são as letras, mas M é consoante e ã é vogal. A palavra tem 2 consoantes (M e a segunda letra é vogal).',
  },
  {
    id: 'pt-g1-010',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Pontuacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que sinal de pontuação usamos no final de uma frase que é uma pergunta?',
    options: ['Ponto', 'Vírgula', 'Ponto de interrogação', 'Ponto e vírgula'],
    correctAnswer: 'Ponto de interrogação',
    explanation: 'As frases de pergunta terminam com ponto de interrogação (?).',
  },
  {
    id: 'pt-g1-011',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Genero',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é o género da palavra "menina"?',
    options: ['Masculino', 'Feminino', 'Neutro', 'Plural'],
    correctAnswer: 'Feminino',
    explanation: '"Menina" é uma palavra do género feminino.',
  },
  {
    id: 'pt-g1-012',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Numero',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é o plural de "gato"?',
    options: ['gatos', 'gato', 'gatoes', 'gata'],
    correctAnswer: 'gatos',
    explanation: 'O plural de "gato" é "gatos".',
  },
  {
    id: 'pt-g1-013',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Artigos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual artigo usamos antes de "menino"?',
    options: ['A', 'O', 'As', 'Um'],
    correctAnswer: 'O',
    explanation: '"Menino" é masculino singular, por isso usamos "o".',
  },
  {
    id: 'pt-g1-014',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Preposicoes',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'O gato está _ mesa.',
    correctAnswer: 'em',
    explanation: 'A preposição correta é "em": o gato está em cima da mesa.',
  },
  {
    id: 'pt-g1-015',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Verbos',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'Nós _ (correr) no parque.',
    correctAnswer: 'corremos',
    explanation: 'Nós corremos é a primeira pessoa do plural do presente do indicativo.',
  },
  {
    id: 'pt-g1-016',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Pronomes',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual pronome completa: _ sou aluno.',
    options: ['Tu', 'Eu', 'Ele', 'Nós'],
    correctAnswer: 'Eu',
    explanation: 'Na primeira pessoa do singular, usamos "Eu".',
  },
  {
    id: 'pt-g1-017',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Consoantes',
    difficulty: 'easy',
    type: 'true_false',
    question: 'A letra "S" é uma consoante.',
    correctAnswer: 'true',
    explanation: 'S é uma consoante, não é uma vogal.',
  },
  {
    id: 'pt-g1-018',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas sílabas tem a palavra "escola"?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'Es-co-la tem 3 sílabas.',
  },
  {
    id: 'pt-g1-019',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Adjetivos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual adjetivo descreve o tamanho: "O elefante é _"?',
    options: ['Bonito', 'Grande', 'Rápido', 'Azul'],
    correctAnswer: 'Grande',
    explanation: '"Grande" é um adjetivo que descreve o tamanho.',
  },
  {
    id: 'pt-g1-020',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Conjuncoes',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que conjunção usamos para juntar ideias: "Eu gosto de leite _ de sumo"?',
    options: ['Mas', 'E', 'Ou', 'Porque'],
    correctAnswer: 'E',
    explanation: '"E" é uma conjunção aditiva que junta ideias.',
  },
  {
    id: 'pt-g1-021',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Rimas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual das palavras rimam com "sol"?',
    options: ['colher', 'farol', 'jardim', 'mesa'],
    correctAnswer: 'farol',
    explanation: '"Sol" e "farol" rimam porque terminam em "-ol".',
  },
  {
    id: 'pt-g1-022',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Rimas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que palavra rimam com "casa"?',
    options: ['livro', 'passa', 'gato', 'pato'],
    correctAnswer: 'passa',
    explanation: '"Casa" e "passa" rimam porque terminam em "-a".',
  },
  {
    id: 'pt-g1-023',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas sílabas tem a palavra "borboleta"?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '4',
    explanation: 'Bor-bo-le-ta tem 4 sílabas.',
  },
  {
    id: 'pt-g1-024',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'A palavra "terra" tem _ sílabas.',
    correctAnswer: '2',
    explanation: 'Ter-ra tem 2 sílabas.',
  },
  {
    id: 'pt-g1-025',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Leitura',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Na frase "O gato dormiu no sofá", o que o gato fez?',
    options: ['Comeu', 'Dormiu', 'Correu', 'Cantou'],
    correctAnswer: 'Dormiu',
    explanation: 'Na frase, o gato dormiu no sofá.',
  },
  {
    id: 'pt-g1-026',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Leitura',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Na frase "A menina comeu a maçã", quem comeu?',
    options: ['O menino', 'A menina', 'O gato', 'O cão'],
    correctAnswer: 'A menina',
    explanation: 'A menina é quem comeu a maçã.',
  },
  {
    id: 'pt-g1-027',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Pontuacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que sinal colocamos no final de uma frase que é uma afirmação?',
    options: ['Ponto de interrogação', 'Ponto de exclamação', 'Ponto final', 'Vírgula'],
    correctAnswer: 'Ponto final',
    explanation: 'As frases afirmativas terminam com ponto final (.).',
  },
  {
    id: 'pt-g1-028',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Verbos',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'Tu _ (jogar) bola no parque. (presente do indicativo)',
    correctAnswer: 'jogas',
    explanation: 'Tu jogas é a segunda pessoa do singular do presente do indicativo.',
  },
  {
    id: 'pt-g1-029',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Pronomes',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual pronome completa: _ é a minha mãe.',
    options: ['Ele', 'Tu', 'Ela', 'Nós'],
    correctAnswer: 'Ela',
    explanation: 'Na terceira pessoa do singular feminino, usamos "Ela".',
  },
  {
    id: 'pt-g1-030',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Aliteracoes',
    difficulty: 'easy',
    type: 'true_false',
    question: 'Na frase "O peixe pescou para Pedro", há uma aliteração.',
    correctAnswer: 'true',
    explanation: 'A aliteração é a repetição de sons consonantais: "p" em peixe, pescou, para, Pedro.',
  },
  {
    id: 'pt-g1-031',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Rimas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que palavra NÃO rima com "lua"?',
    options: ['nua', 'mã', 'chuva', 'rua'],
    correctAnswer: 'mã',
    explanation: '"Mã" não rima com "lua" porque termina em som diferente.',
  },
  {
    id: 'pt-g1-032',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Leitura',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Na frase "Choveu muito ontem", que tempo fazia?',
    options: ['Sol', 'Chuvoso', 'Nublado', 'Neve'],
    correctAnswer: 'Chuvoso',
    explanation: 'Se choveu muito, o tempo estava chuvoso.',
  },

  // ============================================
  // PORTUGUES - GRADE 2
  // ============================================
  {
    id: 'pt-g2-001',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual das palavras abaixo tem um ditongo?',
    options: ['casa', 'leite', 'amor', 'sol'],
    correctAnswer: 'leite',
    explanation: 'Leite tem o ditongo "ei".',
  },
  {
    id: 'pt-g2-002',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Acentuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'A palavra "café" é acentuada em qual sílaba?',
    options: ['Primeira', 'Segunda', 'Última', 'Penúltima'],
    correctAnswer: 'Última',
    explanation: 'Ca-FÉ é acentuada na última sílaba.',
  },
  {
    id: 'pt-g2-003',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Genero e Numero',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o plural de "cão"?',
    options: ['cãos', 'cães', 'cões', 'cãos'],
    correctAnswer: 'cães',
    explanation: 'O plural de "cão" é "cães".',
  },
  {
    id: 'pt-g2-004',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Eu _ (comer) uma maçã. (presente do indicativo)',
    correctAnswer: 'como',
    explanation: 'Eu como é a primeira pessoa do singular do presente do indicativo do verbo comer.',
  },
  {
    id: 'pt-g2-005',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Artigos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual artigo está correto: _ gato dormiu?',
    options: ['O', 'A', 'Os', 'As'],
    correctAnswer: 'O',
    explanation: 'Gato é masculino singular, por isso usamos "o".',
  },
  {
    id: 'pt-g2-006',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Adjetivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Na frase "O menino é alto", qual é o adjetivo?',
    options: ['menino', 'alto', 'é', 'O'],
    correctAnswer: 'alto',
    explanation: '"Alto" é o adjetivo que descreve o menino.',
  },
  {
    id: 'pt-g2-007',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A palavra "pão" tem um ditongo nasal.',
    correctAnswer: 'true',
    explanation: '"ão" é um ditongo nasal.',
  },
  {
    id: 'pt-g2-008',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que sinal usamos para separar enumerações numa frase?',
    options: ['Ponto', 'Vírgula', 'Dois pontos', 'Ponto e vírgula'],
    correctAnswer: 'Vírgula',
    explanation: 'A vírgula separa elementos numa enumeração.',
  },
  {
    id: 'pt-g2-009',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Nós _ (brincar) no parque. (presente do indicativo)',
    correctAnswer: 'brincamos',
    explanation: 'Nós brincamos é a primeira pessoa do plural do presente do indicativo.',
  },
  {
    id: 'pt-g2-010',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Pronomes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o pronome pessoal correto: _ estou a estudar?',
    options: ['Tu', 'Eu', 'Ele', 'Nós'],
    correctAnswer: 'Eu',
    explanation: 'Na primeira pessoa do singular, usamos "Eu".',
  },
  {
    id: 'pt-g2-011',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Substantivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual substantivo é coletivo de "peixes"?',
    options: ['Cardume', 'Alcateia', 'Bando', 'Manada'],
    correctAnswer: 'Cardume',
    explanation: 'Cardume é o coletivo de peixes.',
  },
  {
    id: 'pt-g2-012',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Tu _ (falar) português. (presente do indicativo)',
    correctAnswer: 'falas',
    explanation: 'Tu falas é a segunda pessoa do singular do presente do indicativo.',
  },
  {
    id: 'pt-g2-013',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual palavra tem o ditongo "ou"?',
    options: ['casa', 'ouro', 'mesa', 'livro'],
    correctAnswer: 'ouro',
    explanation: 'A palavra "ouro" tem o ditongo "ou".',
  },
  {
    id: 'pt-g2-014',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Adverbios',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "Ela canta bem", que tipo de advérbio é "bem"?',
    options: ['Lugar', 'Tempo', 'Modo', 'Quantidade'],
    correctAnswer: 'Modo',
    explanation: '"Bem" é um advérbio de modo.',
  },
  {
    id: 'pt-g2-015',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Preposicoes',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Vou _ escola todos os dias.',
    correctAnswer: 'à',
    explanation: 'A preposição "a" contrai-se com o artigo "a" formando "à".',
  },
  {
    id: 'pt-g2-016',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual verbo completa: "Nós _ livros todos os dias"?',
    options: ['leio', 'leem', 'leemos', 'leia'],
    correctAnswer: 'leemos',
    explanation: 'Nós leemos é a conjugação correta no presente do indicativo.',
  },
  {
    id: 'pt-g2-017',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Acentuacao',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A palavra "lápis" tem acento.',
    correctAnswer: 'true',
    explanation: 'Lápis tem acento no "a" porque é palavra oxítona terminada em "i".',
  },
  {
    id: 'pt-g2-018',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Palavras',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o radical da palavra "bonita"?',
    options: ['bonit', 'bonita', 'boni', 'ta'],
    correctAnswer: 'bonit',
    explanation: 'O radical de "bonita" é "bonit".',
  },
  {
    id: 'pt-g2-019',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Conjuncoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que conjunção indica causa: "Estou cansado _ não dormi bem"?',
    options: ['Mas', 'Porque', 'Então', 'Embora'],
    correctAnswer: 'Porque',
    explanation: '"Porque" indica a causa ou razão.',
  },
  {
    id: 'pt-g2-020',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Genero e Numero',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o feminino de "actor"?',
    options: ['actriz', 'actora', 'actoressa', 'atrizes'],
    correctAnswer: 'actriz',
    explanation: 'O feminino de "actor" é "actriz".',
  },
  {
    id: 'pt-g2-021',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Compreensao de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num texto, qual é o título?',
    options: ['O nome do autor', 'O nome do texto', 'A primeira frase', 'O último parágrafo'],
    correctAnswer: 'O nome do texto',
    explanation: 'O título é o nome que identifica o texto.',
  },
  {
    id: 'pt-g2-022',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Compreensao de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Na frase "O João e a Maria foram ao cinema", o que fizeram?',
    options: ['Foram à escola', 'Foram ao cinema', 'Foram ao parque', 'Foram à loja'],
    correctAnswer: 'Foram ao cinema',
    explanation: 'O texto diz que foram ao cinema.',
  },
  {
    id: 'pt-g2-023',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Escrita',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'O meu nome _ Pedro. (é/está)',
    correctAnswer: 'é',
    explanation: 'Usamos "é" para indicar identidade: O meu nome é Pedro.',
  },
  {
    id: 'pt-g2-024',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Escrita',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Nós _ uma árvore no jardim. (plantámos/plantamos)',
    correctAnswer: 'plantámos',
    explanation: 'No pretérito perfeito, o verbo "plantar" na 1ª pessoa do plural é "plantámos".',
  },
  {
    id: 'pt-g2-025',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Maiusculas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em que caso usamos maiúscula no meio de uma frase?',
    options: ['Antes de um substantivo', 'No início de um nome próprio', 'Antes de um adjetivo', 'Depois de uma vírgula'],
    correctAnswer: 'No início de um nome próprio',
    explanation: 'Os nomes próprios começam sempre com maiúscula.',
  },
  {
    id: 'pt-g2-026',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Maiusculas',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A palavra "portugal" deve começar com maiúscula.',
    correctAnswer: 'true',
    explanation: 'Portugal é um nome próprio (país) e deve começar com maiúscula.',
  },
  {
    id: 'pt-g2-027',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Eles _ (dormir) cedo ontem. (pretérito perfeito)',
    correctAnswer: 'dormiram',
    explanation: 'Eles dormiram é a 3ª pessoa do plural do pretérito perfeito.',
  },
  {
    id: 'pt-g2-028',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual palavra tem o ditongo "ai"?',
    options: ['caixa', 'mesa', 'livro', 'casa'],
    correctAnswer: 'caixa',
    explanation: 'A palavra "caixa" tem o ditongo "ai".',
  },
  {
    id: 'pt-g2-029',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Adjetivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o oposto de "quente"?',
    options: ['Frio', 'Grande', 'Bonito', 'Rápido'],
    correctAnswer: 'Frio',
    explanation: 'O antónimo de "quente" é "frio".',
  },
  {
    id: 'pt-g2-030',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Compreensao de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Numa história, quem são os personagens?',
    options: ['Os autores', 'Os lugares', 'As pessoas ou animais da história', 'Os capítulos'],
    correctAnswer: 'As pessoas ou animais da história',
    explanation: 'Os personagens são os seres que participam na história.',
  },
  {
    id: 'pt-g2-031',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que sinal usamos para indicar surpresa?',
    options: ['Ponto', 'Vírgula', 'Ponto de exclamação', 'Ponto de interrogação'],
    correctAnswer: 'Ponto de exclamação',
    explanation: 'O ponto de exclamação (!) indica surpresa ou exclamação.',
  },
  {
    id: 'pt-g2-032',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Conjuncoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que conjunção indica tempo: "Vou sair _ terminar o trabalho"?',
    options: ['Mas', 'Quando', 'Porque', 'Embora'],
    correctAnswer: 'Quando',
    explanation: '"Quando" é uma conjunção temporal que indica tempo.',
  },

  // ============================================
  // PORTUGUES - GRADE 3
  // ============================================
  {
    id: 'pt-g3-001',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual está escrito corretamente?',
    options: ['Excessão', 'Exceção', 'Exeção', 'Exceçao'],
    correctAnswer: 'Exceção',
    explanation: 'A forma correta é "exceção".',
  },
  {
    id: 'pt-g3-002',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Tempos Verbais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "Ontem eu estudei", que tempo verbal é "estudei"?',
    options: ['Presente', 'Pretérito Perfeito', 'Pretérito Imperfeito', 'Futuro'],
    correctAnswer: 'Pretérito Perfeito',
    explanation: '"Estudei" está no pretérito perfeito do indicativo.',
  },
  {
    id: 'pt-g3-003',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Conjunções',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual conjunção indica oposição?',
    options: ['E', 'Mas', 'Porque', 'Então'],
    correctAnswer: 'Mas',
    explanation: '"Mas" é uma conjunção adversativa que indica oposição.',
  },
  {
    id: 'pt-g3-004',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Substantivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o coletivo de "lobos"?',
    options: ['Alcateia', 'Manada', 'Bando', 'Cardume'],
    correctAnswer: 'Alcateia',
    explanation: 'O coletivo de lobos é "alcateia".',
  },
  {
    id: 'pt-g3-005',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Compreensao de Leitura',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num texto narrativo, quem conta a história?',
    options: ['O narrador', 'O autor', 'O leitor', 'O personagem'],
    correctAnswer: 'O narrador',
    explanation: 'O narrador é quem conta a história no texto narrativo.',
  },
  {
    id: 'pt-g3-006',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Ele _ (ir) à escola todos os dias. (presente do indicativo)',
    correctAnswer: 'vai',
    explanation: 'Ele vai é a terceira pessoa do singular do presente do indicativo do verbo ir.',
  },
  {
    id: 'pt-g3-007',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Adverbios',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "Ele correu rapidamente", que tipo de advérbio é "rapidamente"?',
    options: ['Advérbio de lugar', 'Advérbio de tempo', 'Advérbio de modo', 'Advérbio de quantidade'],
    correctAnswer: 'Advérbio de modo',
    explanation: '"Rapidamente" é um advérbio de modo, pois indica como a ação foi realizada.',
  },
  {
    id: 'pt-g3-008',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O menino jogou a bola", qual é o sujeito?',
    options: ['O menino', 'jogou', 'a bola', 'O menino jogou'],
    correctAnswer: 'O menino',
    explanation: 'O sujeito é quem pratica a ação: "O menino".',
  },
  {
    id: 'pt-g3-009',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Genero e Numero',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o feminino de "herói"?',
    options: ['heroia', 'heroína', 'heroico', 'heroica'],
    correctAnswer: 'heroína',
    explanation: 'O feminino de "herói" é "heroína".',
  },
  {
    id: 'pt-g3-010',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que sinal de pontuação usamos para indicar uma pausa longa?',
    options: ['Vírgula', 'Ponto e vírgula', 'Ponto final', 'Dois pontos'],
    correctAnswer: 'Ponto e vírgula',
    explanation: 'O ponto e vírgula indica uma pausa mais longa que a vírgula.',
  },
  {
    id: 'pt-g3-011',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Substantivos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'A coragem é uma _ (qualidade/defeito) humana.',
    correctAnswer: 'qualidade',
    explanation: 'A coragem é uma qualidade humana positiva.',
  },
  {
    id: 'pt-g3-012',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual palavra está escrita corretamente?',
    options: ['Acontecimento', 'Aconteimnto', 'Acoontecimento', 'Acontecimenot'],
    correctAnswer: 'Acontecimento',
    explanation: 'A forma correta é "acontecimento".',
  },
  {
    id: 'pt-g3-013',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Vocês _ (trabalhar) muito. (presente do indicativo)',
    correctAnswer: 'trabalham',
    explanation: 'Vocês trabalham é a terceira pessoa do plural do presente do indicativo.',
  },
  {
    id: 'pt-g3-014',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Compreensao de Leitura',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é o tema de um texto?',
    options: ['O título', 'A ideia principal', 'O autor', 'O número de páginas'],
    correctAnswer: 'A ideia principal',
    explanation: 'O tema é a ideia principal ou assunto do texto.',
  },
  {
    id: 'pt-g3-015',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Tipos de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual tipo de texto relata factos reais?',
    options: ['Texto narrativo', 'Texto informativo', 'Texto poético', 'Texto descritivo'],
    correctAnswer: 'Texto informativo',
    explanation: 'O texto informativo relata factos reais e objectivos.',
  },
  {
    id: 'pt-g3-016',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Adjetivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o grau comparativo de "bonito"?',
    options: ['Mais bonito', 'Boníssimo', 'Bonito', 'Bem bonito'],
    correctAnswer: 'Mais bonito',
    explanation: 'O grau comparativo de superioridade é "mais bonito".',
  },
  {
    id: 'pt-g3-017',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A vírgula pode ser usada para isolar uma palavra enfática.',
    correctAnswer: 'true',
    explanation: 'Sim, a vírgula isola palavras ou expressões enfáticas na frase.',
  },
  {
    id: 'pt-g3-018',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Conjunções',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual conjunção indica consequência: "Choveu, _ fiquei em casa"?',
    options: ['Mas', 'Embora', 'Portanto', 'Porque'],
    correctAnswer: 'Portanto',
    explanation: '"Portanto" indica consequência ou conclusão.',
  },
  {
    id: 'pt-g3-019',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Que tempo verbal é "Eu tinha estudado"?',
    options: ['Pretérito Perfeito', 'Pretérito Mais-que-perfeito', 'Pretérito Imperfeito', 'Futuro do Pretérito'],
    correctAnswer: 'Pretérito Mais-que-perfeito',
    explanation: '"Tinha estudado" está no pretérito mais-que-perfeito do indicativo.',
  },
  {
    id: 'pt-g3-020',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O livro está na mesa", que complemento é "na mesa"?',
    options: ['Complemento direto', 'Complemento indireto', 'Adjunto adverbial', 'Predicativo'],
    correctAnswer: 'Adjunto adverbial',
    explanation: '"Na mesa" é um adjunto adverbial de lugar.',
  },
  {
    id: 'pt-g3-021',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Leitura Expressiva',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ao ler em voz alta, devemos:',
    options: ['Ler o mais rápido possível', 'Ler com entoação e ritmo adequados', 'Não pausar nunca', 'Ler sempre em silêncio'],
    correctAnswer: 'Ler com entoação e ritmo adequados',
    explanation: 'A leitura expressiva requer entoação, ritmo e pausas adequados.',
  },
  {
    id: 'pt-g3-022',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Intenções do Autor',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quando um autor escreve "É proibido fumar!", qual é a sua intenção?',
    options: ['Informar', 'Narrar', 'Ordenar', 'Descrever'],
    correctAnswer: 'Ordenar',
    explanation: 'A frase expressa uma ordem ou proibição.',
  },
  {
    id: 'pt-g3-023',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Previsoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Ao ler o título "O Mistério da Casa Abandonada", que podemos prever que o texto será:',
    options: ['Uma receita', 'Uma história de mistério', 'Uma notícia de jornal', 'Uma lista de compras'],
    correctAnswer: 'Uma história de mistério',
    explanation: 'O título sugere um texto de mistério ou suspense.',
  },
  {
    id: 'pt-g3-024',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Conectores',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual conector indica adição: "Estudou muito, _ passou no exame"?',
    options: ['Mas', 'E', 'Porque', 'Embora'],
    correctAnswer: 'E',
    explanation: '"E" é um conector que indica adição de ideias.',
  },
  {
    id: 'pt-g3-025',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Conectores',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual conector indica oposição: "Choveu, _ saímos à mesma"?',
    options: ['Porque', 'Embora', 'Então', 'Portanto'],
    correctAnswer: 'Embora',
    explanation: '"Embora" indica concessão ou oposição.',
  },
  {
    id: 'pt-g3-026',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Leitura Expressiva',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que tipo de texto temos de ler com mais expressão?',
    options: ['Tabela de dados', 'Texto narrativo', 'Lista telefónica', 'Fórmula matemática'],
    correctAnswer: 'Texto narrativo',
    explanation: 'O texto narrativo beneficia de uma leitura mais expressiva.',
  },
  {
    id: 'pt-g3-027',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Compreensao de Leitura',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é o narrador omnisciente?',
    options: ['Um narrador que sabe tudo sobre a história', 'Um narrador personagem', 'Um narrador que não sabe nada', 'Um narrador que só ouve'],
    correctAnswer: 'Um narrador que sabe tudo sobre a história',
    explanation: 'O narrador omnisciente sabe tudo sobre os personagens e acontecimentos.',
  },
  {
    id: 'pt-g3-028',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Intenções do Autor',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quando um autor escreve "A poluição está a destruir o planeta", qual é a sua intenção?',
    options: ['Entreter', 'Informar e alertar', 'Ensinhar uma receita', 'Descrever um lugar'],
    correctAnswer: 'Informar e alertar',
    explanation: 'O autor pretende informar e alertar sobre um problema ambiental.',
  },
  {
    id: 'pt-g3-029',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Previsoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num texto que começa "Era uma vez numa floresta distante...", que género literário esperamos?',
    options: ['Notícia', 'Conto de fadas', 'Artigo de opinião', 'Relatório'],
    correctAnswer: 'Conto de fadas',
    explanation: 'A expressão "Era uma vez" é típica dos contos de fadas.',
  },
  {
    id: 'pt-g3-030',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Tipos de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que tipo de texto pretende ensinar o leitor a fazer algo?',
    options: ['Texto narrativo', 'Texto instrucional', 'Texto poético', 'Texto descritivo'],
    correctAnswer: 'Texto instrucional',
    explanation: 'O texto instrucional tem como objetivo ensinar a realizar uma tarefa.',
  },
  {
    id: 'pt-g3-031',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Nós _ (poder) ir ao parque amanhã. (futuro do subjuntivo)',
    correctAnswer: 'pudermos',
    explanation: 'No futuro do subjuntivo, o verbo "poder" na 1ª pessoa do plural é "pudermos".',
  },
  {
    id: 'pt-g3-032',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual palavra está escrita corretamente?',
    options: ['Acolhimento', 'Acolhimento', 'Acolhimento', 'Acolhimento'],
    correctAnswer: 'Acolhimento',
    explanation: 'A forma correta é "acolhimento" com "nh".',
  },

  // ============================================
  // PORTUGUES - GRADE 4
  // ============================================
  {
    id: 'pt-g4-001',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O sol sorriu", que figura de linguagem é usada?',
    options: ['Metáfora', 'Comparação', 'Personificação', 'Hipérbole'],
    correctAnswer: 'Personificação',
    explanation: 'O sol não pode sorrir verdadeiramente. Dar características humanas a seres inanimados é personificação.',
  },
  {
    id: 'pt-g4-002',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Verbos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Em "Se eu tivesse estudado, teria passado", que modo verbal é usado?',
    options: ['Indicativo', 'Subjuntivo', 'Imperativo', 'Condicional'],
    correctAnswer: 'Subjuntivo',
    explanation: 'O verbo "tivesse" está no pretérito imperfeito do subjuntivo.',
  },
  {
    id: 'pt-g4-003',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Redacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a estrutura correta de uma introdução de texto dissertativo?',
    options: ['Tese + argumentos', 'Argumentos + conclusão', 'Tese + contextualização', 'Contextualização + tese'],
    correctAnswer: 'Contextualização + tese',
    explanation: 'A introdução deve contextualizar o tema e apresentar a tese.',
  },
  {
    id: 'pt-g4-004',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Expressoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que significa a expressão "chutar o balde"?',
    options: ['Jogar futebol', 'Desistir de tudo', 'Correr muito', 'Estar feliz'],
    correctAnswer: 'Desistir de tudo',
    explanation: '"Chutar o balde" significa desistir ou perder a paciência.',
  },
  {
    id: 'pt-g4-005',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Pontuacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Em "Maria disse: \"Estou cansada.\"", que sinal de pontuação usamos antes de começar a fala?',
    options: ['Vírgula', 'Dois pontos', 'Ponto e vírgula', 'Ponto'],
    correctAnswer: 'Dois pontos',
    explanation: 'Antes de começar uma fala direta, usamos dois pontos.',
  },
  {
    id: 'pt-g4-006',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sinonimos e Antonimos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o sinónimo de "alegre"?',
    options: ['Triste', 'Feliz', 'Cansado', 'Bravo'],
    correctAnswer: 'Feliz',
    explanation: '"Alegre" e "feliz" são sinónimos.',
  },
  {
    id: 'pt-g4-007',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O gato preto dormiu no sofá", qual é o adjunto adnominal?',
    options: ['O gato', 'preto', 'dormiu', 'no sofá'],
    correctAnswer: 'preto',
    explanation: '"Preto" é um adjunto adnominal que modifica o substantivo "gato".',
  },
  {
    id: 'pt-g4-008',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Tempos Verbais',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'Quando eu _ (ter) 18 anos, vou tirar a carta. (futuro do subjuntivo)',
    correctAnswer: 'tiver',
    explanation: 'No futuro do subjuntivo, usamos "tiver" (quando eu tiver).',
  },
  {
    id: 'pt-g4-009',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual está escrito corretamente?',
    options: ['Houve', 'ouve', 'Houvi', 'ouvi'],
    correctAnswer: 'Houve',
    explanation: 'O verbo haver no pretérito perfeito é "houve" com H.',
  },
  {
    id: 'pt-g4-010',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na expressão "Um mar de pessoas", que figura de linguagem é usada?',
    options: ['Hipérbole', 'Metáfora', 'Personificação', 'Onomatopeia'],
    correctAnswer: 'Metáfora',
    explanation: 'Comparar o número de pessoas a um mar é uma metáfora.',
  },
  {
    id: 'pt-g4-011',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sinonimos e Antonimos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o antónimo de "escuro"?',
    options: ['Claro', 'Preto', 'Bonito', 'Pequeno'],
    correctAnswer: 'Claro',
    explanation: 'O antónimo de "escuro" é "claro".',
  },
  {
    id: 'pt-g4-012',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Verbos',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'Se eu _ (saber) a resposta, teria dito. (pretérito imperfeito do subjuntivo)',
    correctAnswer: 'soubesse',
    explanation: 'O pretérito imperfeito do subjuntivo do verbo "saber" é "soubesse".',
  },
  {
    id: 'pt-g4-013',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Tipos de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual tipo de texto pretende convencer o leitor?',
    options: ['Informativo', 'Narrativo', 'Dissuasivo', 'Descritivo'],
    correctAnswer: 'Dissuasivo',
    explanation: 'O texto dissuasivo pretende convencer ou influenciar o leitor.',
  },
  {
    id: 'pt-g4-014',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Expressoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que significa "estar com a língua presa"?',
    options: ['Estar doente', 'Não conseguir falar', 'Estar com fome', 'Estar cansado'],
    correctAnswer: 'Não conseguir falar',
    explanation: 'Estar com a língua presa significa não conseguir falar.',
  },
  {
    id: 'pt-g4-015',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Ortografia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual palavra usa "x" corretamente?',
    options: ['Excesso', 'Excessivo', 'Excessar', 'Excessão'],
    correctAnswer: 'Excessivo',
    explanation: 'A forma correta é "excessivo" com "ss" e não "x".',
  },
  {
    id: 'pt-g4-016',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "Ontem choveu muito", que classe de palavra é "ontem"?',
    options: ['Substantivo', 'Adjetivo', 'Advérbio', 'Verbo'],
    correctAnswer: 'Advérbio',
    explanation: '"Ontem" é um advérbio de tempo.',
  },
  {
    id: 'pt-g4-017',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na expressão "Choviam pedras", que figura de linguagem é usada?',
    options: ['Metáfora', 'Hipérbole', 'Comparação', 'Ironia'],
    correctAnswer: 'Hipérbole',
    explanation: 'Exagerar dizendo que "choviam pedras" é uma hipérbole.',
  },
  {
    id: 'pt-g4-018',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Redacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Numa dissertação argumentativa, a conclusão deve:',
    options: ['Apresentar novos argumentos', 'Repetir a introdução', 'Retomar a tese e sintetizar', 'Fazer perguntas'],
    correctAnswer: 'Retomar a tese e sintetizar',
    explanation: 'A conclusão retoma a tese e sintetiza os argumentos apresentados.',
  },
  {
    id: 'pt-g4-019',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Conjunções',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual conjunção indica condição: "_ estudares, passarás no exame"?',
    options: ['Porque', 'Embora', 'Se', 'Mas'],
    correctAnswer: 'Se',
    explanation: '"Se" é uma conjunção condicional que indica uma condição.',
  },
  {
    id: 'pt-g4-020',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Tempos Verbais',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'Nós _ (ir) ao cinema amanhã. (futuro do indicativo)',
    correctAnswer: 'iremos',
    explanation: 'A primeira pessoa do plural do futuro do indicativo do verbo "ir" é "iremos".',
  },
  {
    id: 'pt-g4-021',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Texto de Opinião',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Num texto de opinião, o autor deve:',
    options: ['Apenas descrever factos', 'Argumentar e defender o seu ponto de vista', 'Contar uma história', 'Ensinar uma receita'],
    correctAnswer: 'Argumentar e defender o seu ponto de vista',
    explanation: 'O texto de opinião baseia-se em argumentos para defender uma posição.',
  },
  {
    id: 'pt-g4-022',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Carta/Convite',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num convite formal, devemos começar com:',
    options: ['"Oi"', '"Caro(a)"', '"Hey"', '"Olá pessoal"'],
    correctAnswer: '"Caro(a)"',
    explanation: 'Num convite formal, usamos "Caro(a)" ou "Exmo(a). Senhor(a)".',
  },
  {
    id: 'pt-g4-023',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Carta/Convite',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que informação é obrigatória num convite?',
    options: ['A cor da roupa', 'Data, hora e local do evento', 'O nome do presidente', 'A temperatura'],
    correctAnswer: 'Data, hora e local do evento',
    explanation: 'Todo convite deve indicar data, hora e local.',
  },
  {
    id: 'pt-g4-024',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Reescrita de Textos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ao reescrever um texto, devemos:',
    options: ['Copiar palavra por palavra', 'Manter a mesma ideia com palavras diferentes', 'Mudar o tema completamente', 'Apagar tudo e escrever novo'],
    correctAnswer: 'Manter a mesma ideia com palavras diferentes',
    explanation: 'A reescrita consiste em reformular o texto mantendo o significado.',
  },
  {
    id: 'pt-g4-025',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Reescrita de Textos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual frase está reescrita corretamente? Original: "O João é muito alto."',
    options: ['O João é muito alto.', 'O João é enorme.', 'O João é muito alto e bonito.', 'O João é baixo.'],
    correctAnswer: 'O João é enorme.',
    explanation: '"Enorme" reformula "muito alto" mantendo o significado.',
  },
  {
    id: 'pt-g4-026',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Voz Ativa/Passiva',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O menino comeu a maçã" (voz ativa), como fica na voz passiva?',
    options: ['A maçã comeu o menino', 'A maçã foi comida pelo menino', 'O menino foi comido pela maçã', 'A maçã é comida pelo menino'],
    correctAnswer: 'A maçã foi comida pelo menino',
    explanation: 'Na voz passiva, o objeto torna-se sujeito: A maçã foi comida pelo menino.',
  },
  {
    id: 'pt-g4-027',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Voz Ativa/Passiva',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "Os alunos fizeram os trabalhos", o sujeito da voz passiva seria:',
    options: ['Os alunos', 'Os trabalhos', 'A escola', 'O professor'],
    correctAnswer: 'Os trabalhos',
    explanation: 'Na voz passiva: "Os trabalhos foram feitos pelos alunos".',
  },
  {
    id: 'pt-g4-028',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Texto de Opinião',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual conector é mais adequado para introduzir uma contra-argumentação?',
    options: ['Além disso', 'No entanto', 'Por conseguinte', 'Em primeiro lugar'],
    correctAnswer: 'No entanto',
    explanation: '"No entanto" introduz uma contra-argumentação ou oposição.',
  },
  {
    id: 'pt-g4-029',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Carta/Convite',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Prezado Senhor, tenho o _ de convidá-lo para a nossa festa.',
    correctAnswer: 'prazer',
    explanation: 'A expressão formal correta é "tenho o prazer de convidá-lo".',
  },
  {
    id: 'pt-g4-030',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Reescrita de Textos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Que tipo de reescrita transforma um texto narrativo em informativo?',
    options: ['Manter todas as palavras', 'Mudar o ponto de vista e o estilo', 'Apenas mudar o título', 'Adicionar diálogos'],
    correctAnswer: 'Mudar o ponto de vista e o estilo',
    explanation: 'A reescrita de género requer mudanças de estilo, ponto de vista e estrutura.',
  },
  {
    id: 'pt-g4-031',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Voz Ativa/Passiva',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'A casa _ construída pelos operários. (voz passiva)',
    correctAnswer: 'foi',
    explanation: 'Na voz passiva com "ser" no pretérito perfeito: "A casa foi construída".',
  },
  {
    id: 'pt-g4-032',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na expressão "Fez um sol de rachar", que figura de linguagem é usada?',
    options: ['Metáfora', 'Hipérbole', 'Personificação', 'Onomatopeia'],
    correctAnswer: 'Hipérbole',
    explanation: 'Exagerar dizendo que o sol "racha" é uma hipérbole.',
  },

  // ============================================
  // PORTUGUES - GRADE 1 (NEW QUESTIONS)
  // ============================================
  {
    id: 'pt-g1-033',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Sequencia de Eventos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Na história "Os Três Porquinhos", o que acontece primeiro?',
    options: ['O lobo destrói a casa', 'Os porquinhos constroem casas', 'O porquinho mais novo chega', 'Os porquinhos fugiram'],
    correctAnswer: 'Os porquinhos constroem casas',
    explanation: 'Primeiro os porquinhos constroem as suas casas antes de o lobo chegar.',
  },
  {
    id: 'pt-g1-034',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Identificacao de Personagens',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Na frase "A Branca de Neve comeu a maçã envenenada", quem é a personagem principal?',
    options: ['O príncipe', 'A rainha má', 'Branca de Neve', 'O anão'],
    correctAnswer: 'Branca de Neve',
    explanation: 'Branca de Neve é a personagem principal desta história.',
  },
  {
    id: 'pt-g1-035',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Ortografia M/N antes de P/B',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual palavra está escrita corretamente?',
    options: ['Comprimento', 'Conprimento', 'Comprimento', 'Conprimento'],
    correctAnswer: 'Comprimento',
    explanation: 'Antes de P, usamos M: com-PRIMENTO.',
  },
  {
    id: 'pt-g1-036',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Ortografia M/N antes de P/B',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'A palavra "conta" written correctly is _.',
    correctAnswer: 'conta',
    explanation: 'Antes de B, usamos N: conTA.',
  },
  {
    id: 'pt-g1-037',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Leitura',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Na frase "O menino pegou no livro e abriu-o", o que o menino fez com o livro?',
    options: ['Comprou-o', 'Abriu-o', 'Guardou-o', 'Leu-o'],
    correctAnswer: 'Abriu-o',
    explanation: 'O menino abriu o livro.',
  },
  {
    id: 'pt-g1-038',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Verbos',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'Ela _ (ler) um livro ontem. (pretérito perfeito)',
    correctAnswer: 'leu',
    explanation: 'Ela leu é a terceira pessoa do singular do pretérito perfeito do verbo ler.',
  },
  {
    id: 'pt-g1-039',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Pontuacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que sinal de pontuação usamos quando alguém grita?',
    options: ['Ponto', 'Vírgula', 'Ponto de interrogação', 'Ponto de exclamação'],
    correctAnswer: 'Ponto de exclamação',
    explanation: 'O ponto de exclamação (!) é usado em frases que expressam emoção forte.',
  },

  // ============================================
  // PORTUGUES - GRADE 2 (NEW QUESTIONS)
  // ============================================
  {
    id: 'pt-g2-033',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Inferencia de Significado',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Na frase "Estava um frio que cortava", o que "cortava" significa?',
    options: ['Havia um frieiro', 'O frio era muito intenso', 'Havia uma faca', 'Estava a nevar'],
    correctAnswer: 'O frio era muito intenso',
    explanation: 'A expressão "frio que cortava" é uma figura que indica que o frio era muito intenso.',
  },
  {
    id: 'pt-g2-034',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Tema de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num texto que fala sobre a importância de reciclar, qual é o tema?',
    options: ['A vida nas cidades', 'A reciclagem e o ambiente', 'As fábricas', 'O lixo doméstico'],
    correctAnswer: 'A reciclagem e o ambiente',
    explanation: 'O tema principal é a importância da reciclagem para o ambiente.',
  },
  {
    id: 'pt-g2-035',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Escrita de Paragrafos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é um parágrafo?',
    options: ['Uma frase longa', 'Um conjunto de frases sobre uma ideia', 'Um capítulo de livro', 'Uma palavra'],
    correctAnswer: 'Um conjunto de frases sobre uma ideia',
    explanation: 'Um parágrafo é um bloco de texto que desenvolve uma ideia ou tema.',
  },
  {
    id: 'pt-g2-036',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Inferencia de Significado',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Na expressão "Fazer uma coceira", o que significa?',
    options: ['Estar com comichão', 'Incomodar alguém', 'Coçar o cabelo', 'Estar com frio'],
    correctAnswer: 'Incomodar alguém',
    explanation: '"Fazer coceira" é uma expressão que significa incomodar ou irritar alguém.',
  },
  {
    id: 'pt-g2-037',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Compreensao de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Numa notícia, onde se encontra a informação mais importante?',
    options: ['No último parágrafo', 'No primeiro parágrafo', 'No título apenas', 'Nas fotos'],
    correctAnswer: 'No primeiro parágrafo',
    explanation: 'Na notícia, a informação mais importante está no primeiro parágrafo (lide).',
  },
  {
    id: 'pt-g2-038',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Escrita',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Nós _ (jantar) ontem às oito. (pretérito perfeito)',
    correctAnswer: 'jantámos',
    explanation: 'No pretérito perfeito, nós jantámos.',
  },
  {
    id: 'pt-g2-039',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "O Pedro, o João e a Ana foram ao parque", por que se usam vírgulas?',
    options: ['Para separar os nomes', 'Porque há erros', 'Para fazer pausas longas', 'Não se usam vírgulas'],
    correctAnswer: 'Para separar os nomes',
    explanation: 'As vírgulas separam os elementos de uma enumeração (nomes).',
  },
  {
    id: 'pt-g2-040',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Tu _ (sair) de casa às oito. (presente do indicativo)',
    correctAnswer: 'saís',
    explanation: 'Tu saís é a segunda pessoa do singular do presente do indicativo do verbo sair.',
  },

  // ============================================
  // PORTUGUES - GRADE 3 (NEW QUESTIONS)
  // ============================================
  {
    id: 'pt-g3-033',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Analise de Texto Narrativo',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Numa história, qual é a parte onde o conflito se resolve?',
    options: ['Introdução', 'Nó', 'Desfecho', 'Clima'],
    correctAnswer: 'Desfecho',
    explanation: 'O desfecho é a parte final da história onde o conflito se resolve.',
  },
  {
    id: 'pt-g3-034',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Funcao de Conectores',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que conector indica tempo: "Quando cheguei, a aula já tinha começado"?',
    options: ['Mas', 'Quando', 'Porque', 'Então'],
    correctAnswer: 'Quando',
    explanation: '"Quando" é um conector temporal que indica o momento da ação.',
  },
  {
    id: 'pt-g3-035',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Reformulacao de Frases',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual frase reformula corretamente "O homem era alto"? Original: "Era um homem alto"',
    options: ['O homem era alto.', 'Um homem alto existia.', 'Havia um homem que era alto.', 'O alto homem era.'],
    correctAnswer: 'O homem era alto.',
    explanation: 'A frase reformulada mantém o significado original com estrutura diferente.',
  },
  {
    id: 'pt-g3-036',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Compreensao de Leitura',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num texto narrativo, o que é o clímax?',
    options: ['O início da história', 'O momento de maior tensão', 'O final feliz', 'A descrição do cenário'],
    correctAnswer: 'O momento de maior tensão',
    explanation: 'O clímax é o ponto de maior tensão ou conflito da história.',
  },
  {
    id: 'pt-g3-037',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Conjuncoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que conjunção indica uma alternativa: "Ou estudamos, _ perdemos a oportunidade"?',
    options: ['Mas', 'Ou', 'Porque', 'Embora'],
    correctAnswer: 'Ou',
    explanation: '"Ou" é uma conjunção alternativa que apresenta duas opções.',
  },
  {
    id: 'pt-g3-038',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual está escrito corretamente?',
    options: ['Frequência', 'Frequencia', 'Frequeência', 'Frequência'],
    correctAnswer: 'Frequência',
    explanation: 'A forma correta é "frequência" com "qu" antes de "e".',
  },
  {
    id: 'pt-g3-039',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Se eu _ (ter) tempo, vou ao cinema. (futuro do subjuntivo)',
    correctAnswer: 'tiver',
    explanation: 'No futuro do subjuntivo, o verbo ter na 1ª pessoa é "tiver".',
  },
  {
    id: 'pt-g3-040',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Tipos de Texto',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que tipo de texto tem rimas e versos?',
    options: ['Texto narrativo', 'Texto poético', 'Texto informativo', 'Texto argumentativo'],
    correctAnswer: 'Texto poético',
    explanation: 'O texto poético é caracterizado por rimas, versos e ritmo.',
  },

  // ============================================
  // PORTUGUES - GRADE 4 (NEW QUESTIONS)
  // ============================================
  {
    id: 'pt-g4-033',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Interpretacao de Texto de Opinião',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Num artigo de opinião, qual é o objetivo principal do autor?',
    options: ['Contar uma história', 'Defender um ponto de vista', 'Ensinar uma receita', 'Descrever um lugar'],
    correctAnswer: 'Defender um ponto de vista',
    explanation: 'O texto de opinião tem como objetivo persuadir o leitor sobre uma questão.',
  },
  {
    id: 'pt-g4-034',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Estrutura de Carta',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Como termina uma carta formal?',
    options: ['"Beijinhos"', '"Com os melhores cumprimentos"', '"Adeus"', '"Tudo de bom"'],
    correctAnswer: 'Com os melhores cumprimentos',
    explanation: 'As cartas formais terminam com fórmulas de cortesia como "Com os melhores cumprimentos".',
  },
  {
    id: 'pt-g4-035',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Revisao de Textos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ao revisar um texto, o que devemos verificar primeiro?',
    options: ['As cores das letras', 'A ortografia e a gramática', 'O tamanho da letra', 'O número de páginas'],
    correctAnswer: 'A ortografia e a gramática',
    explanation: 'A revisão deve começar pela correção ortográfica e gramatical.',
  },
  {
    id: 'pt-g4-036',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Texto de Opinião',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Numa dissertação argumentativa, os argumentos devem ser:',
    options: ['Inventados', 'Baseados em factos', 'Pessoais apenas', 'Repetidos'],
    correctAnswer: 'Baseados em factos',
    explanation: 'Os argumentos devem ser sustentados por factos e dados concretos.',
  },
  {
    id: 'pt-g4-037',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Carta/Convite',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num convite informal, que fórmula de abertura é adequada?',
    options: ['"Exmo(a). Senhor(a)"', '"Querido(a)"', '"Ilustríssimo(a)"', '"A quem interesse possa"'],
    correctAnswer: 'Querido(a)',
    explanation: 'Em contextos informais, usamos "Querido(a)" ou "Caro(a)".',
  },
  {
    id: 'pt-g4-038',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na expressão "Caiu uma torrente de águas", que figura de linguagem é usada?',
    options: ['Metáfora', 'Hipérbole', 'Personificação', 'Comparação'],
    correctAnswer: 'Hipérbole',
    explanation: 'Exagerar dizendo "torrente de águas" para chuva é uma hipérbole.',
  },
  {
    id: 'pt-g4-039',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Voz Ativa/Passiva',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'O trabalho _ entregue pelo aluno. (voz passiva)',
    correctAnswer: 'foi',
    explanation: 'Na voz passiva: "O trabalho foi entregue pelo aluno".',
  },
  {
    id: 'pt-g4-040',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "Ontem, o João comprou um livro novo", que termo é "Ontem"?',
    options: ['Sujeito', 'Predicado', 'Adjunto adverbial', 'Complemento'],
    correctAnswer: 'Adjunto adverbial',
    explanation: '"Ontem" é um adjunto adverbial de tempo.',
  },

  // ============================================
  // PORTUGUES - GRADE 1 (ESTIMATED MORE)
  // ============================================
  {
    id: 'pt-g1-040',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Texto Descritivo',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Um texto descritivo serve para:',
    options: ['Contar uma história', 'Descrever seres ou coisas', 'Dar instruções', 'Fazer perguntas'],
    correctAnswer: 'Descrever seres ou coisas',
    explanation: 'O texto descritivo tem como objetivo descrever seres, objetos ou lugares.',
  },
  {
    id: 'pt-g1-041',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Entrevista',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Numa entrevista, quem faz as perguntas?',
    options: ['O entrevistado', 'O entrevistador', 'O leitor', 'O escritor'],
    correctAnswer: 'O entrevistador',
    explanation: 'O entrevistador é quem pergunta; o entrevistado responde.',
  },
  {
    id: 'pt-g1-042',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Argumentação',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quando damos a nossa opinião, estamos a:',
    options: ['Calcular números', 'Argumentar e dar a nossa opinião', 'Dançar', 'Jogar'],
    correctAnswer: 'Argumentar e dar a nossa opinião',
    explanation: 'Argumentar é dar a nossa opinião e explicar porquê.',
  },
  {
    id: 'pt-g1-043',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Biografia',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Uma biografia conta a história de quê?',
    options: ['De um animal', 'Da vida de uma pessoa', 'De um planeta', 'De uma cidade'],
    correctAnswer: 'Da vida de uma pessoa',
    explanation: 'Uma biografia é um texto que conta a vida de alguém.',
  },

  // ============================================
  // PORTUGUES - GRADE 2 (MORE)
  // ============================================
  {
    id: 'pt-g2-041',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Texto Descritivo',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que informação NÃO aparece num texto descritivo?',
    options: ['Nome do objeto descrito', 'Características visuais', 'Diálogos entre personagens', 'Tamanho e formato'],
    correctAnswer: 'Diálogos entre personagens',
    explanation: 'O texto descritivo não tem diálogos, apenas descreve seres ou objetos.',
  },
  {
    id: 'pt-g2-042',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Notícia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Numa notícia, qual é a função do lide?',
    options: ['Contar uma piada', 'Dar a informação principal logo de início', 'Concluir o texto', 'Decorar a página'],
    correctAnswer: 'Dar a informação principal logo de início',
    explanation: 'O lide resume os factos principais da notícia.',
  },
  {
    id: 'pt-g2-043',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Entrevista',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Como se transcreve uma entrevista num texto?',
    options: ['Apenas com descrições', 'Com perguntas e respostas', 'Apenas com opiniões', 'Apenas com fotografias'],
    correctAnswer: 'Com perguntas e respostas',
    explanation: 'Uma entrevista transcrita apresenta as perguntas e as respostas.',
  },
  {
    id: 'pt-g2-044',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Argumentação',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Para argumentar bem, devemos:',
    options: ['Falar muito alto', 'Apresentar razões e exemplos', 'Ignorar o outro', 'Ficar calado'],
    correctAnswer: 'Apresentar razões e exemplos',
    explanation: 'Argumentar é apresentar razões e exemplos para defender a nossa opinião.',
  },

  // ============================================
  // PORTUGUES - GRADE 3 (MORE)
  // ============================================
  {
    id: 'pt-g3-041',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Texto Descritivo',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual tipo de texto é misturado frequentemente com descrição?',
    options: ['Texto de listas', 'Texto narrativo', 'Texto argumentativo', 'Texto informativo'],
    correctAnswer: 'Texto narrativo',
    explanation: 'Os textos narrativos frequentemente incluem descrições dos personagens e cenários.',
  },
  {
    id: 'pt-g3-042',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Biografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que informação aparece numa biografia?',
    options: ['Receitas de cozinha', 'Data de nascimento e acontecimentos importantes', 'Tabelas de números', 'Listas de produtos'],
    correctAnswer: 'Data de nascimento e acontecimentos importantes',
    explanation: 'A biografia apresenta a vida da pessoa com datas e acontecimentos.',
  },
  {
    id: 'pt-g3-043',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Notícia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Numa notícia, quem é a fonte da informação?',
    options: ['O autor do texto que investigou o facto', 'Apenas o leitor', 'O animal da história', 'O planeta Terra'],
    correctAnswer: 'O autor do texto que investigou o facto',
    explanation: 'O autor investiga os factos e escreve a notícia para informar o leitor.',
  },
  {
    id: 'pt-g3-044',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Argumentação',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Numa argumentação, a tese é:',
    options: ['A conclusão final', 'A ideia principal que se defende', 'O exemplo dado', 'A fotografia'],
    correctAnswer: 'A ideia principal que se defende',
    explanation: 'A tese é a ideia principal que o autor defende com argumentos.',
  },

  // ============================================
  // PORTUGUES - GRADE 4 (MORE)
  // ============================================
  {
    id: 'pt-g4-041',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Texto Descritivo',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Num texto descritivo, o que é fundamental para criar uma boa descrição?',
    options: ['Usar muitos números', 'Usar adjetivos e expressões sensoriais', 'Fazer perguntas', 'Reduzir o texto'],
    correctAnswer: 'Usar adjetivos e expressões sensoriais',
    explanation: 'A descrição rica usa adjetivos e referências aos cinco sentidos.',
  },
  {
    id: 'pt-g4-042',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Biografia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Uma biografia é um texto predominantemente:',
    options: ['Narrativo', 'Informativo', 'Argumentativo', 'Poético'],
    correctAnswer: 'Narrativo',
    explanation: 'A biografia narra os acontecimentos da vida de uma pessoa.',
  },
  {
    id: 'pt-g4-043',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Notícia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Numa notícia, o título deve:',
    options: ['Ser muito longo', 'Captar a atenção e resumir o facto', 'Ser uma pergunta', 'Ser uma despedida'],
    correctAnswer: 'Captar a atenção e resumir o facto',
    explanation: 'O título da notícia deve ser claro e chamar a atenção do leitor.',
  },
  {
    id: 'pt-g4-044',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Entrevista',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Numa entrevista, que tipo de perguntas são melhores?',
    options: ['Perguntas fechadas de sim/não', 'Perguntas abertas que permitem explicar', 'Perguntas com respostas sim apenas', 'Perguntas que insultam'],
    correctAnswer: 'Perguntas abertas que permitem explicar',
    explanation: 'Perguntas abertas permitem que o entrevistado dê respostas mais completas.',
  },
  {
    id: 'pt-g4-045',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Argumentação',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Numa redação argumentativa, o que deve vir após a introdução?',
    options: ['A conclusão', 'O desenvolvimento com argumentos', 'O título', 'Uma nova história'],
    correctAnswer: 'O desenvolvimento com argumentos',
    explanation: 'Após a introdução, o desenvolvimento apresenta os argumentos que sustentam a tese.',
  },
  {
    id: 'pt-g4-046',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Biografia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a diferença entre biografia e autobiografia?',
    options: ['Não há diferença', 'A autobiografia é escrita pela própria pessoa', 'A biografia é mais curta', 'As duas são iguais'],
    correctAnswer: 'A autobiografia é escrita pela própria pessoa',
    explanation: 'Na autobiografia, a pessoa escreve sobre a sua própria vida.',
  },
  {
    id: 'pt-g2-045',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Maiusculas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual destes nomes está escrito corretamente?',
    options: ['portugal', 'Portugal', 'PORTUGAL', 'portuGal'],
    correctAnswer: 'Portugal',
    explanation: 'Nome próprio começa com maiúscula: Portugal.',
  },
  {
    id: 'pt-g3-045',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Palavras',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o radical da palavra "esperança"?',
    options: ['esper', 'esperan', 'ança', 'es'],
    correctAnswer: 'esperan',
    explanation: 'O radical de "esperança" é "esperan". Esperança, esperançar.',
  },
  {
    id: 'pt-g4-047',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Expressoes',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que significa "ficar de bico" no português brasileiro?',
    options: ['Estar feliz', 'Ficar zangado ou amuado', 'Estar doente', 'Estar cansado'],
    correctAnswer: 'Ficar zangado ou amuado',
    explanation: '"Ficar de bico" significa ficar amuado ou zangado.',
  },
];
