'use server';

/**
 * @fileOverview Comprehensive question bank for MestreMiudo
 * Pre-seeded questions organized by subject, grade, and topic
 */

export type Subject = 'Portugues' | 'Matematica' | 'Estudo do Meio';
export type GradeLevel = 1 | 2 | 3 | 4;
export type Difficulty = 'easy' | 'normal' | 'hard';
export type QuestionType = 'multiple_choice' | 'fill_blank' | 'true_false' | 'matching';

export interface Question {
  id: string;
  subject: Subject;
  gradeLevel: GradeLevel;
  topic: string;
  difficulty: Difficulty;
  type: QuestionType;
  question: string;
  options?: string[];
  correctAnswer: string | string[];
  explanation: string;
}

const QUESTIONS: Question[] = [
  // ============================================
  // PORTUGUES - GRADE 1
  // ============================================
  {
    id: 'pt-g1-001',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas vogais tem o alfabeto português?',
    options: ['3', '5', '7', '6'],
    correctAnswer: '5',
    explanation: 'O alfabeto português tem 5 vogais: A, E, I, O, U.',
  },
  {
    id: 'pt-g1-002',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'fill_blank',
    question: 'A, E, I, O, _',
    correctAnswer: 'U',
    explanation: 'A última vogal é o U.',
  },
  {
    id: 'pt-g1-003',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Consoantes',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual das seguintes é uma consoante?',
    options: ['A', 'B', 'I', 'O'],
    correctAnswer: 'B',
    explanation: 'B é uma consoante. A, I e O são vogais.',
  },
  {
    id: 'pt-g1-004',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantas sílabas tem a palavra "maçã"?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'Ma-çã tem 2 sílabas.',
  },
  {
    id: 'pt-g1-005',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Silabas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a divisão em sílabas da palavra "borboleta"?',
    options: ['bor-bo-le-ta', 'borb-o-le-ta', 'bor-bo-let-a', 'bo-rbo-le-ta'],
    correctAnswer: 'bor-bo-le-ta',
    explanation: 'Bor-bo-le-ta tem 4 sílabas.',
  },
  {
    id: 'pt-g1-006',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Palavras',
    difficulty: 'easy',
    type: 'true_false',
    question: 'A palavra "casa" tem 4 letras.',
    correctAnswer: 'true',
    explanation: 'C-A-S-A = 4 letras.',
  },
  {
    id: 'pt-g1-007',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Vogais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é a vogal que está na palavra "sol"?',
    options: ['A', 'E', 'I', 'O'],
    correctAnswer: 'O',
    explanation: 'A palavra "sol" tem a vogal O.',
  },
  {
    id: 'pt-g1-008',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Palavras',
    difficulty: 'easy',
    type: 'true_false',
    question: 'A palavra "amor" começa com uma vogal.',
    correctAnswer: 'true',
    explanation: 'A palavra "amor" começa com A, que é uma vogal.',
  },
  {
    id: 'pt-g1-009',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Consoantes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantas consoantes tem a palavra "mãe"?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'M-Ã-E: M e ã são as letras, mas M é consoante e ã é vogal. A palavra tem 2 consoantes (M e a segunda letra é vogal).',
  },
  {
    id: 'pt-g1-010',
    subject: 'Portugues',
    gradeLevel: 1,
    topic: 'Pontuacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que sinal de pontuação usamos no final de uma frase que é uma pergunta?',
    options: ['Ponto', 'Vírgula', 'Ponto de interrogação', 'Ponto e vírgula'],
    correctAnswer: 'Ponto de interrogação',
    explanation: 'As frases de pergunta terminam com ponto de interrogação (?).',
  },

  // ============================================
  // PORTUGUES - GRADE 2
  // ============================================
  {
    id: 'pt-g2-001',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual das palavras abaixo tem um ditongo?',
    options: ['casa', 'leite', 'amor', 'sol'],
    correctAnswer: 'leite',
    explanation: 'Leite tem o ditongo "ei".',
  },
  {
    id: 'pt-g2-002',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Acentuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'A palavra "café" é acentuada em qual sílaba?',
    options: ['Primeira', 'Segunda', 'Última', 'Penúltima'],
    correctAnswer: 'Última',
    explanation: 'Ca-FÉ é acentuada na última sílaba.',
  },
  {
    id: 'pt-g2-003',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Genero e Numero',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o plural de "cão"?',
    options: ['cãos', 'cães', 'cões', 'cãos'],
    correctAnswer: 'cães',
    explanation: 'O plural de "cão" é "cães".',
  },
  {
    id: 'pt-g2-004',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Eu _ (comer) uma maçã. (presente do indicativo)',
    correctAnswer: 'como',
    explanation: 'Eu como é a primeira pessoa do singular do presente do indicativo do verbo comer.',
  },
  {
    id: 'pt-g2-005',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Artigos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual artigo está correto: _ gato dormiu?',
    options: ['O', 'A', 'Os', 'As'],
    correctAnswer: 'O',
    explanation: 'Gato é masculino singular, por isso usamos "o".',
  },
  {
    id: 'pt-g2-006',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Adjetivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Na frase "O menino é alto", qual é o adjetivo?',
    options: ['menino', 'alto', 'é', 'O'],
    correctAnswer: 'alto',
    explanation: '"Alto" é o adjetivo que descreve o menino.',
  },
  {
    id: 'pt-g2-007',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Ditongos',
    difficulty: 'normal',
    type: 'true_false',
    question: 'A palavra "pão" tem um ditongo nasal.',
    correctAnswer: 'true',
    explanation: '"ão" é um ditongo nasal.',
  },
  {
    id: 'pt-g2-008',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que sinal usamos para separar enumerações numa frase?',
    options: ['Ponto', 'Vírgula', 'Dois pontos', 'Ponto e vírgula'],
    correctAnswer: 'Vírgula',
    explanation: 'A vírgula separa elementos numa enumeração.',
  },
  {
    id: 'pt-g2-009',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Nós _ (brincar) no parque. (presente do indicativo)',
    correctAnswer: 'brincamos',
    explanation: 'Nós brincamos é a primeira pessoa do plural do presente do indicativo.',
  },
  {
    id: 'pt-g2-010',
    subject: 'Portugues',
    gradeLevel: 2,
    topic: 'Pronomes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o pronome pessoal correto: _ estou a estudar?',
    options: ['Tu', 'Eu', 'Ele', 'Nós'],
    correctAnswer: 'Eu',
    explanation: 'Na primeira pessoa do singular, usamos "Eu".',
  },

  // ============================================
  // PORTUGUES - GRADE 3
  // ============================================
  {
    id: 'pt-g3-001',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual está escrito corretamente?',
    options: ['Excessão', 'Exceção', 'Exeção', 'Exceçao'],
    correctAnswer: 'Exceção',
    explanation: 'A forma correta é "exceção".',
  },
  {
    id: 'pt-g3-002',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Tempos Verbais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "Ontem eu estudei", que tempo verbal é "estudei"?',
    options: ['Presente', 'Pretérito Perfeito', 'Pretérito Imperfeito', 'Futuro'],
    correctAnswer: 'Pretérito Perfeito',
    explanation: '"Estudei" está no pretérito perfeito do indicativo.',
  },
  {
    id: 'pt-g3-003',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Conjunções',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual conjunção indica oposição?',
    options: ['E', 'Mas', 'Porque', 'Então'],
    correctAnswer: 'Mas',
    explanation: '"Mas" é uma conjunção adversativa que indica oposição.',
  },
  {
    id: 'pt-g3-004',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Substantivos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o coletivo de "lobos"?',
    options: ['Alcateia', 'Manada', 'Bando', 'Cardume'],
    correctAnswer: 'Alcateia',
    explanation: 'O coletivo de lobos é "alcateia".',
  },
  {
    id: 'pt-g3-005',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Compreensao de Leitura',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Num texto narrativo, quem conta a história?',
    options: ['O narrador', 'O autor', 'O leitor', 'O personagem'],
    correctAnswer: 'O narrador',
    explanation: 'O narrador é quem conta a história no texto narrativo.',
  },
  {
    id: 'pt-g3-006',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Verbos',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'Ele _ (ir) à escola todos os dias. (presente do indicativo)',
    correctAnswer: 'vai',
    explanation: 'Ele vai é a terceira pessoa do singular do presente do indicativo do verbo ir.',
  },
  {
    id: 'pt-g3-007',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Adverbios',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Em "Ele correu rapidamente", que tipo de advérbio é "rapidamente"?',
    options: ['Advérbio de lugar', 'Advérbio de tempo', 'Advérbio de modo', 'Advérbio de quantidade'],
    correctAnswer: 'Advérbio de modo',
    explanation: '"Rapidamente" é um advérbio de modo, pois indica como a ação foi realizada.',
  },
  {
    id: 'pt-g3-008',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O menino jogou a bola", qual é o sujeito?',
    options: ['O menino', 'jogou', 'a bola', 'O menino jogou'],
    correctAnswer: 'O menino',
    explanation: 'O sujeito é quem pratica a ação: "O menino".',
  },
  {
    id: 'pt-g3-009',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Genero e Numero',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o feminino de "herói"?',
    options: ['heroia', 'heroína', 'heroia', 'heroína'],
    correctAnswer: 'heroína',
    explanation: 'O feminino de "herói" é "heroína".',
  },
  {
    id: 'pt-g3-010',
    subject: 'Portugues',
    gradeLevel: 3,
    topic: 'Pontuacao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que sinal de pontuação usamos para indicar uma pausa longa?',
    options: ['Vírgula', 'Ponto e vírgula', 'Ponto final', 'Dois pontos'],
    correctAnswer: 'Ponto e vírgula',
    explanation: 'O ponto e vírgula indica uma pausa mais longa que a vírgula.',
  },

  // ============================================
  // PORTUGUES - GRADE 4
  // ============================================
  {
    id: 'pt-g4-001',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O sol sorriu", que figura de linguagem é usada?',
    options: ['Metáfora', 'Comparação', 'Personificação', 'Hipérbole'],
    correctAnswer: 'Personificação',
    explanation: 'O sol não pode sorrir verdadeiramente. Dar características humanas a seres inanimados é personificação.',
  },
  {
    id: 'pt-g4-002',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Verbos',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Em "Se eu tivesse estudado, teria passado", que modo verbal é usado?',
    options: ['Indicativo', 'Subjuntivo', 'Imperativo', 'Condicional'],
    correctAnswer: 'Subjuntivo',
    explanation: 'O verbo "tivesse" está no pretérito imperfeito do subjuntivo.',
  },
  {
    id: 'pt-g4-003',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Redacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a estrutura correta de uma introdução de texto dissertativo?',
    options: ['Tese + argumentos', 'Argumentos + conclusão', 'Tese + contextualização', 'Contextualização + tese'],
    correctAnswer: 'Contextualização + tese',
    explanation: 'A introdução deve contextualizar o tema e apresentar a tese.',
  },
  {
    id: 'pt-g4-004',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Expressoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que significa a expressão "chutar o balde"?',
    options: ['Jogar futebol', 'Desistir de tudo', 'Correr muito', 'Estar feliz'],
    correctAnswer: 'Desistir de tudo',
    explanation: '"Chutar o balde" significa desistir ou perder a paciência.',
  },
  {
    id: 'pt-g4-005',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Pontuacao',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Em "Maria disse: \"Estou cansada.\"", que sinal de pontuação usamos antes de começar a fala?',
    options: ['Vírgula', 'Dois pontos', 'Ponto e vírgula', 'Ponto'],
    correctAnswer: 'Dois pontos',
    explanation: 'Antes de começar uma fala direta, usamos dois pontos.',
  },
  {
    id: 'pt-g4-006',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sinonimos e Antonimos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o sinónimo de "alegre"?',
    options: ['Triste', 'Feliz', 'Cansado', 'Bravo'],
    correctAnswer: 'Feliz',
    explanation: '"Alegre" e "feliz" são sinónimos.',
  },
  {
    id: 'pt-g4-007',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Sintaxe',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na frase "O gato preto dormiu no sofá", qual é o adjunto adnominal?',
    options: ['O gato', 'preto', 'dormiu', 'no sofá'],
    correctAnswer: 'preto',
    explanation: '"Preto" é um adjunto adnominal que modifica o substantivo "gato".',
  },
  {
    id: 'pt-g4-008',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Tempos Verbais',
    difficulty: 'hard',
    type: 'fill_blank',
    question: 'Quando eu _ (ter) 18 anos, vou tirar a carta. (futuro do subjuntivo)',
    correctAnswer: 'tiver',
    explanation: 'No futuro do subjuntivo, usamos "tiver" (quando eu tiver).',
  },
  {
    id: 'pt-g4-009',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Ortografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual está escrito corretamente?',
    options: ['Houve', 'ouve', 'Houvi', 'ouvi'],
    correctAnswer: 'Houve',
    explanation: 'O verbo haver no pretérito perfeito é "houve" com H.',
  },
  {
    id: 'pt-g4-010',
    subject: 'Portugues',
    gradeLevel: 4,
    topic: 'Figuras de Linguagem',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Na expressão "Um mar de pessoas", que figura de linguagem é usada?',
    options: ['Hipérbole', 'Metáfora', 'Personificação', 'Onomatopeia'],
    correctAnswer: 'Metáfora',
    explanation: 'Comparar o número de pessoas a um mar é uma metáfora.',
  },

  // ============================================
  // MATEMATICA - GRADE 1
  // ============================================
  {
    id: 'mat-g1-001',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 3 + 4?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '7',
    explanation: '3 + 4 = 7.',
  },
  {
    id: 'mat-g1-002',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 10 - 3?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '7',
    explanation: '10 - 3 = 7.',
  },
  {
    id: 'mat-g1-003',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Contagem',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Que número vem depois do 15?',
    options: ['14', '16', '17', '13'],
    correctAnswer: '16',
    explanation: 'O número que segue o 15 é o 16.',
  },
  {
    id: 'mat-g1-004',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'fill_blank',
    question: '5 + _ = 9',
    correctAnswer: '4',
    explanation: '5 + 4 = 9.',
  },
  {
    id: 'mat-g1-005',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos lados tem um triângulo?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'Um triângulo tem 3 lados.',
  },
  {
    id: 'mat-g1-006',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Numeracao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é o número por extenso do algarismo 7?',
    options: ['Cinco', 'Seis', 'Sete', 'Oito'],
    correctAnswer: 'Sete',
    explanation: 'O algarismo 7 escreve-se "sete".',
  },
  {
    id: 'mat-g1-007',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quanto é 2 + 2 + 2?',
    options: ['4', '5', '6', '7'],
    correctAnswer: '6',
    explanation: '2 + 2 + 2 = 6.',
  },
  {
    id: 'mat-g1-008',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Comparacao',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é maior: 8 ou 6?',
    options: ['6', '8', 'São iguais', 'Nenhuma'],
    correctAnswer: '8',
    explanation: '8 é maior que 6.',
  },
  {
    id: 'mat-g1-009',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Aritmetica',
    difficulty: 'easy',
    type: 'true_false',
    question: '9 - 5 = 4',
    correctAnswer: 'true',
    explanation: '9 - 5 = 4 é correto.',
  },
  {
    id: 'mat-g1-010',
    subject: 'Matematica',
    gradeLevel: 1,
    topic: 'Formas',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos lados tem um quadrado?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '4',
    explanation: 'Um quadrado tem 4 lados iguais.',
  },

  // ============================================
  // MATEMATICA - GRADE 2
  // ============================================
  {
    id: 'mat-g2-001',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 25 + 37?',
    options: ['52', '62', '72', '82'],
    correctAnswer: '62',
    explanation: '25 + 37 = 62.',
  },
  {
    id: 'mat-g2-002',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '3 × 4 = _',
    correctAnswer: '12',
    explanation: '3 × 4 = 12.',
  },
  {
    id: 'mat-g2-003',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos cantos tem um retângulo?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '4',
    explanation: 'Um retângulo tem 4 cantos (vértices).',
  },
  {
    id: 'mat-g2-004',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 100 - 45?',
    options: ['45', '55', '65', '75'],
    correctAnswer: '55',
    explanation: '100 - 45 = 55.',
  },
  {
    id: 'mat-g2-005',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: '5 × 6 = ?',
    options: ['25', '30', '35', '20'],
    correctAnswer: '30',
    explanation: '5 × 6 = 30.',
  },
  {
    id: 'mat-g2-006',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos centímetros tem 1 metro?',
    options: ['10', '50', '100', '1000'],
    correctAnswer: '100',
    explanation: '1 metro = 100 centímetros.',
  },
  {
    id: 'mat-g2-007',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '8 × 7 = _',
    correctAnswer: '56',
    explanation: '8 × 7 = 56.',
  },
  {
    id: 'mat-g2-008',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Maria tem 12 rebuçados e deu 5 ao João. Quantos rebuçados tem Maria agora?',
    options: ['5', '6', '7', '17'],
    correctAnswer: '7',
    explanation: '12 - 5 = 7 rebuçados.',
  },
  {
    id: 'mat-g2-009',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número que fica entre o 29 e o 31?',
    options: ['28', '30', '32', '29'],
    correctAnswer: '30',
    explanation: 'O número entre 29 e 31 é 30.',
  },
  {
    id: 'mat-g2-010',
    subject: 'Matematica',
    gradeLevel: 2,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'true_false',
    question: '9 × 3 = 27',
    correctAnswer: 'true',
    explanation: '9 × 3 = 27 está correto.',
  },

  // ============================================
  // MATEMATICA - GRADE 3
  // ============================================
  {
    id: 'mat-g3-001',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 156 + 278?',
    options: ['424', '434', '444', '454'],
    correctAnswer: '434',
    explanation: '156 + 278 = 434.',
  },
  {
    id: 'mat-g3-002',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Divisao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 48 ÷ 6?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: '48 ÷ 6 = 8.',
  },
  {
    id: 'mat-g3-003',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Fracoes',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que fração representa metade de um todo?',
    options: ['1/3', '1/2', '1/4', '2/3'],
    correctAnswer: '1/2',
    explanation: 'Metade é representada pela fração 1/2.',
  },
  {
    id: 'mat-g3-004',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Geometria',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos graus tem um ângulo reto?',
    options: ['45°', '60°', '90°', '180°'],
    correctAnswer: '90°',
    explanation: 'Um ângulo reto mede exatamente 90 graus.',
  },
  {
    id: 'mat-g3-005',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Medidas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos quilogramas tem 1 tonelada?',
    options: ['100', '500', '1000', '10000'],
    correctAnswer: '1000',
    explanation: '1 tonelada = 1000 quilogramas.',
  },
  {
    id: 'mat-g3-006',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Problemas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Pedro comprou 3 cadernos a 150$ cada. Quanto gastou no total?',
    options: ['350$', '400$', '450$', '500$'],
    correctAnswer: '450$',
    explanation: '3 × 150$ = 450$.',
  },
  {
    id: 'mat-g3-007',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'fill_blank',
    question: 'O número 356 tem _ centenas, _ dezenas e _ unidades.',
    correctAnswer: '3,5,6',
    explanation: '356 = 3 centenas + 5 dezenas + 6 unidades.',
  },
  {
    id: 'mat-g3-008',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Perimetros',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o perímetro de um quadrado com 5 cm de lado?',
    options: ['10 cm', '15 cm', '20 cm', '25 cm'],
    correctAnswer: '20 cm',
    explanation: 'Perímetro = 4 × 5 cm = 20 cm.',
  },
  {
    id: 'mat-g3-009',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Tabuada',
    difficulty: 'normal',
    type: 'fill_blank',
    question: '12 × 9 = _',
    correctAnswer: '108',
    explanation: '12 × 9 = 108.',
  },
  {
    id: 'mat-g3-010',
    subject: 'Matematica',
    gradeLevel: 3,
    topic: 'Aritmetica',
    difficulty: 'normal',
    type: 'true_false',
    question: '250 + 350 = 600',
    correctAnswer: 'true',
    explanation: '250 + 350 = 600 está correto.',
  },

  // ============================================
  // MATEMATICA - GRADE 4
  // ============================================
  {
    id: 'mat-g4-001',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Aritmetica',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quanto é 1234 + 5678?',
    options: ['6812', '6912', '7012', '7112'],
    correctAnswer: '6912',
    explanation: '1234 + 5678 = 6912.',
  },
  {
    id: 'mat-g4-002',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Fracoes',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o resultado de 1/4 + 1/4?',
    options: ['1/2', '2/8', '2/4', '1/8'],
    correctAnswer: '1/2',
    explanation: '1/4 + 1/4 = 2/4 = 1/2.',
  },
  {
    id: 'mat-g4-003',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Geometria',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quantos triângulos tem numa estrela de 5 pontas?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'Uma estrela de 5 pontas tem 5 triângulos.',
  },
  {
    id: 'mat-g4-004',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Ana tem o triplo da idade de Pedro. Se Pedro tem 8 anos, quantos anos tem Ana?',
    options: ['16', '24', '21', '18'],
    correctAnswer: '24',
    explanation: '3 × 8 = 24 anos.',
  },
  {
    id: 'mat-g4-005',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Decimal',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto é 3,5 + 2,7?',
    options: ['5,2', '6,2', '7,2', '8,2'],
    correctAnswer: '6,2',
    explanation: '3,5 + 2,7 = 6,2.',
  },
  {
    id: 'mat-g4-006',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Area',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é a área de um retângulo com 8 cm de comprimento e 5 cm de largura?',
    options: ['13 cm²', '30 cm²', '40 cm²', '45 cm²'],
    correctAnswer: '40 cm²',
    explanation: 'Área = 8 × 5 = 40 cm².',
  },
  {
    id: 'mat-g4-007',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Multiplicacao',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '25 × 12 = _',
    correctAnswer: '300',
    explanation: '25 × 12 = 300.',
  },
  {
    id: 'mat-g4-008',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Problemas',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Um comboio parte às 14h30 e chega ao destino às 16h45. Quanto tempo durou a viagem?',
    options: ['1h15', '2h15', '2h30', '3h15'],
    correctAnswer: '2h15',
    explanation: 'Das 14h30 às 16h45 são 2 horas e 15 minutos.',
  },
  {
    id: 'mat-g4-009',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Divisao',
    difficulty: 'hard',
    type: 'fill_blank',
    question: '144 ÷ 12 = _',
    correctAnswer: '12',
    explanation: '144 ÷ 12 = 12.',
  },
  {
    id: 'mat-g4-010',
    subject: 'Matematica',
    gradeLevel: 4,
    topic: 'Numeracao',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o número par entre o 17 e o 21?',
    options: ['17', '18', '19', '20'],
    correctAnswer: '18',
    explanation: 'Os números pares entre 17 e 21 são 18 e 20. O primeiro é 18.',
  },

  // ============================================
  // ESTUDO DO MEIO - GRADE 1
  // ============================================
  {
    id: 'em-g1-001',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Natureza',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos estados da matéria existem?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'Existem 3 estados: sólido, líquido e gasoso.',
  },
  {
    id: 'em-g1-002',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Animais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual animal faz "mu"?',
    options: ['Cão', 'Gato', 'Vaca', 'Galinha'],
    correctAnswer: 'Vaca',
    explanation: 'A vaca faz "mu".',
  },
  {
    id: 'em-g1-003',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Plantas',
    difficulty: 'easy',
    type: 'true_false',
    question: 'As plantas precisam de sol para crescer.',
    correctAnswer: 'true',
    explanation: 'As plantas fazem fotossíntese com a luz do sol.',
  },
  {
    id: 'em-g1-004',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Clima',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Em que estação do ano faz mais calor?',
    options: ['Inverno', 'Primavera', 'Veraão', 'Outono'],
    correctAnswer: 'Veraão',
    explanation: 'No verão as temperaturas são mais altas.',
  },
  {
    id: 'em-g1-005',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Corpo Humano',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Quantos sentidos temos?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'Temoss: visão, audição, olfato, paladar e tato.',
  },
  {
    id: 'em-g1-006',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Natureza',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual é a estrela mais próxima da Terra?',
    options: ['Lua', 'Marte', 'Sol', 'Estrela Polar'],
    correctAnswer: 'Sol',
    explanation: 'O Sol é a estrela mais próxima da Terra.',
  },
  {
    id: 'em-g1-007',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Animais',
    difficulty: 'easy',
    type: 'true_false',
    question: 'O peixe vive na água.',
    correctAnswer: 'true',
    explanation: 'Os peixes são animais aquáticos.',
  },
  {
    id: 'em-g1-008',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Materiais',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'De que é feita a água?',
    options: ['Oxigénio e carbono', 'Hidrogénio e oxigénio', 'Nitrogénio e oxigénio', 'Hidrogénio e carbono'],
    correctAnswer: 'Hidrogénio e oxigénio',
    explanation: 'A água é formada por hidrogénio e oxigénio (H₂O).',
  },
  {
    id: 'em-g1-009',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Alimentos',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Qual grupo alimentar nos dá energia rápida?',
    options: ['Proteínas', 'Hidratos de carbono', 'Vitaminas', 'Minerais'],
    correctAnswer: 'Hidratos de carbono',
    explanation: 'Os hidratos de carbono são a principal fonte de energia.',
  },
  {
    id: 'em-g1-010',
    subject: 'Estudo do Meio',
    gradeLevel: 1,
    topic: 'Sociedade',
    difficulty: 'easy',
    type: 'multiple_choice',
    question: 'Onde se compra pão?',
    options: ['Escola', 'Padaria', 'Farmácia', 'Biblioteca'],
    correctAnswer: 'Padaria',
    explanation: 'O pão é comprado na padaria.',
  },

  // ============================================
  // ESTUDO DO MEIO - GRADE 2
  // ============================================
  {
    id: 'em-g2-001',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o ciclo da água?',
    options: ['Evaporação, condensação, precipitação, escoamento', 'Fusão, ebulição, sublimação', 'Fusão, solidificação, condensação', 'Evaporação, sublimação, precipitação'],
    correctAnswer: 'Evaporação, condensação, precipitação, escoamento',
    explanation: 'O ciclo da água inclui evaporação, condensação, precipitação e escoamento.',
  },
  {
    id: 'em-g2-002',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Animais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que classe de animais inclui as rãs?',
    options: ['Mamíferos', 'Répteis', 'Anfíbios', 'Aves'],
    correctAnswer: 'Anfíbios',
    explanation: 'As rãs são anfíbios, vivem na água e na terra.',
  },
  {
    id: 'em-g2-003',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Plantas',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual parte da planta absorve a água do solo?',
    options: ['Folhas', 'Caule', 'Raízes', 'Flores'],
    correctAnswer: 'Raízes',
    explanation: 'As raízes absorvem a água e os nutrientes do solo.',
  },
  {
    id: 'em-g2-004',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Corpo Humano',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual órgão bombeia o sangue?',
    options: ['Pulmões', 'Fígado', 'Coração', 'Cérebro'],
    correctAnswer: 'Coração',
    explanation: 'O coração é o órgão que bombeia o sangue.',
  },
  {
    id: 'em-g2-005',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Materiais',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que material é melhor condutor de eletricidade?',
    options: ['Plástico', 'Madeira', 'Metal', 'Vidro'],
    correctAnswer: 'Metal',
    explanation: 'Os metais são bons condutores de eletricidade.',
  },
  {
    id: 'em-g2-006',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Clima',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que instrumento mede a temperatura?',
    options: ['Barómetro', 'Termómetro', 'Higrómetro', 'Anemómetro'],
    correctAnswer: 'Termómetro',
    explanation: 'O termómetro mede a temperatura.',
  },
  {
    id: 'em-g2-007',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Alimentos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que grupo alimentar ajuda a construir e reparar o corpo?',
    options: ['Hidratos de carbono', 'Gorduras', 'Proteínas', 'Vitaminas'],
    correctAnswer: 'Proteínas',
    explanation: 'As proteínas são essenciais para crescimento e reparação.',
  },
  {
    id: 'em-g2-008',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'true_false',
    question: 'O papel é feito de árvores.',
    correctAnswer: 'true',
    explanation: 'O papel é fabricado a partir de cellulose da madeira.',
  },
  {
    id: 'em-g2-009',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que tipo de rocha é formada por vulcões?',
    options: ['Sedimentar', 'Metamórfica', 'Ígnea', 'Calcária'],
    correctAnswer: 'Ígnea',
    explanation: 'As rochas ígneas são formadas pelo resfriamento de magma.',
  },
  {
    id: 'em-g2-010',
    subject: 'Estudo do Meio',
    gradeLevel: 2,
    topic: 'Corpo Humano',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quantos ossos tem o corpo humano adulto?',
    options: ['106', '206', '306', '406'],
    correctAnswer: '206',
    explanation: 'O corpo humano adulto tem 206 ossos.',
  },

  // ============================================
  // ESTUDO DO MEIO - GRADE 3
  // ============================================
  {
    id: 'em-g3-001',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Ecologia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é a fotossíntese?',
    options: ['Produção de energia pelo fogo', 'Produção de oxigénio pelas plantas', 'Decomposição da matéria', 'Absorção de água pelo solo'],
    correctAnswer: 'Produção de oxigénio pelas plantas',
    explanation: 'A fotossíntese é o processo pelo qual as plantas produzem oxigénio e energia.',
  },
  {
    id: 'em-g3-002',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Sistema Solar',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o maior planeta do sistema solar?',
    options: ['Terra', 'Marte', 'Júpiter', 'Saturno'],
    correctAnswer: 'Júpiter',
    explanation: 'Júpiter é o maior planeta do sistema solar.',
  },
  {
    id: 'em-g3-003',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Eletricidade',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'De onde vem a eletricidade que usamos em casa?',
    options: ['Da Lua', 'Do Sol', 'De usinas e barragens', 'Da chuva'],
    correctAnswer: 'De usinas e barragens',
    explanation: 'A eletricidade é produzida em usinas elétricas e barragens.',
  },
  {
    id: 'em-g3-004',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Geografia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é o maior oceano do mundo?',
    options: ['Atlântico', 'Índico', 'Pacífico', 'Ártico'],
    correctAnswer: 'Pacífico',
    explanation: 'O oceano Pacífico é o maior e mais profundo.',
  },
  {
    id: 'em-g3-005',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Alimentos',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que são os aditivos alimentares?',
    options: ['Alimentos naturais', 'Substâncias adicionadas aos alimentos', 'Alimentos biológicos', 'Frutas secas'],
    correctAnswer: 'Substâncias adicionadas aos alimentos',
    explanation: 'Aditivos são substâncias adicionadas para conservar ou melhorar os alimentos.',
  },
  {
    id: 'em-g3-006',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Corpo Humano',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Qual é a função dos pulmões?',
    options: ['Bombear sangue', 'Filtrar o sangue', 'Realizar trocas gasosas', 'Digirir os alimentos'],
    correctAnswer: 'Realizar trocas gasosas',
    explanation: 'Os pulmões permitem a entrada de oxigénio e saída de CO₂.',
  },
  {
    id: 'em-g3-007',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Recursos Naturais',
    difficulty: 'normal',
    type: 'true_false',
    question: 'O petróleo é um recurso natural renovável.',
    correctAnswer: 'false',
    explanation: 'O petróleo é um recurso não renovável, demora milhões de anos a formar-se.',
  },
  {
    id: 'em-g3-008',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Clima',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que gases formam a atmosfera terrestre?',
    options: ['Oxigénio e azoto', 'Hidrogénio e hélio', 'Dióxido de carbono e oxigénio', 'Azoto e hélio'],
    correctAnswer: 'Oxigénio e azoto',
    explanation: 'A atmosfera é composta principalmente por azoto (78%) e oxigénio (21%).',
  },
  {
    id: 'em-g3-009',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é o património cultural?',
    options: ['Apenas edifícios antigos', 'Bens materiais e imateriais de uma cultura', 'Apenas monumentos', 'Apenas tradições'],
    correctAnswer: 'Bens materiais e imateriais de uma cultura',
    explanation: 'O património cultural inclui bens físicos e tradições de um povo.',
  },
  {
    id: 'em-g3-010',
    subject: 'Estudo do Meio',
    gradeLevel: 3,
    topic: 'Natureza',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Que seres vivos produzem o seu próprio alimento?',
    options: ['Animais', 'Plantas', 'Fungos', 'Bactérias'],
    correctAnswer: 'Plantas',
    explanation: 'As plantas são seres autotróficos, produzem o seu próprio alimento.',
  },

  // ============================================
  // ESTUDO DO MEIO - GRADE 4
  // ============================================
  {
    id: 'em-g4-001',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Genetica',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é o ADN?',
    options: ['Uma proteína', 'Uma molécula que guarda informações genéticas', 'Um tipo de célula', 'Uma vitamina'],
    correctAnswer: 'Uma molécula que guarda informações genéticas',
    explanation: 'O ADN (Ácido Desoxirribonucleico) contém as instruções genéticas.',
  },
  {
    id: 'em-g4-002',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Forca e Movimento',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é a gravidade?',
    options: ['Uma força que empurra os objetos para cima', 'Uma força que atrai os corpos entre si', 'Um tipo de energia', 'Uma corrente de ar'],
    correctAnswer: 'Uma força que atrai os corpos entre si',
    explanation: 'A gravidade é uma força de atração entre dois corpos com massa.',
  },
  {
    id: 'em-g4-003',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Sistema Solar',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'Quanto tempo demora a Terra a dar uma volta completa ao Sol?',
    options: ['30 dias', '365 dias', '3650 dias', '1000 dias'],
    correctAnswer: '365 dias',
    explanation: 'A Terra demora aproximadamente 365 dias (1 ano) a orbitar o Sol.',
  },
  {
    id: 'em-g4-004',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Ecologia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é a biodiversidade?',
    options: ['Apenas a quantidade de árvores', 'A variedade de seres vivos num ecossistema', 'Apenas a quantidade de animais', 'A poluição do ar'],
    correctAnswer: 'A variedade de seres vivos num ecossistema',
    explanation: 'Biodiversidade é a diversidade de vida num determinado ambiente.',
  },
  {
    id: 'em-g4-005',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Tecnologia',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é um sistema solar fotovoltaico?',
    options: ['Um painel de aquecimento', 'Um sistema que converte luz solar em eletricidade', 'Um tipo de foguete', 'Uma estação de rádio'],
    correctAnswer: 'Um sistema que converte luz solar em eletricidade',
    explanation: 'Os painéis fotovoltaicos convertem energia solar em eletricidade.',
  },
  {
    id: 'em-g4-006',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Corpo Humano',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Qual é o maior órgão do corpo humano?',
    options: ['Fígado', 'Pulmão', 'Pele', 'Cérebro'],
    correctAnswer: 'Pele',
    explanation: 'A pele é o maior órgão do corpo humano.',
  },
  {
    id: 'em-g4-007',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Clima',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'O que é o efeito de estufa?',
    options: ['Resfriamento da Terra', 'Aquecimento da Terra por gases na atmosfera', 'Formação de buracos no ozono', 'Poluição da água'],
    correctAnswer: 'Aquecimento da Terra por gases na atmosfera',
    explanation: 'O efeito de estufa é causado por gases que retêm calor na atmosfera.',
  },
  {
    id: 'em-g4-008',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Recursos Naturais',
    difficulty: 'hard',
    type: 'true_false',
    question: 'A energia eólica é uma energia renovável.',
    correctAnswer: 'true',
    explanation: 'A energia eólica (dos ventos) é renovável e limpa.',
  },
  {
    id: 'em-g4-009',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Geografia',
    difficulty: 'hard',
    type: 'multiple_choice',
    question: 'Quantos continentes existem?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '7',
    explanation: 'Existem 7 continentes: Europa, Ásia, África, América do Norte, América do Sul, Oceânia e Antártida.',
  },
  {
    id: 'em-g4-010',
    subject: 'Estudo do Meio',
    gradeLevel: 4,
    topic: 'Sociedade',
    difficulty: 'normal',
    type: 'multiple_choice',
    question: 'O que é o reciclagem?',
    options: ['Jogar lixo fora', 'Transformar resíduos em novos materiais', 'Queimar lixo', 'Enterrar resíduos'],
    correctAnswer: 'Transformar resíduos em novos materiais',
    explanation: 'A reciclagem transforma resíduos em matéria-prima para novos produtos.',
  },
];

/**
 * Get all questions
 */
export function getAllQuestions(): Question[] {
  return QUESTIONS;
}

/**
 * Get questions filtered by subject, grade, topic, and/or difficulty
 */
export function getFilteredQuestions(filters: {
  subject?: Subject;
  gradeLevel?: GradeLevel;
  topic?: string;
  difficulty?: Difficulty;
  type?: QuestionType;
}): Question[] {
  return QUESTIONS.filter((q) => {
    if (filters.subject && q.subject !== filters.subject) return false;
    if (filters.gradeLevel && q.gradeLevel !== filters.gradeLevel) return false;
    if (filters.topic && q.topic !== filters.topic) return false;
    if (filters.difficulty && q.difficulty !== filters.difficulty) return false;
    if (filters.type && q.type !== filters.type) return false;
    return true;
  });
}

/**
 * Get a random subset of questions
 */
export function getRandomQuestions(
  count: number,
  filters?: {
    subject?: Subject;
    gradeLevel?: GradeLevel;
    topic?: string;
    difficulty?: Difficulty;
  }
): Question[] {
  const filtered = filters ? getFilteredQuestions(filters) : QUESTIONS;
  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

/**
 * Get questions by subject and grade
 */
export function getQuestionsBySubjectAndGrade(
  subject: Subject,
  gradeLevel: GradeLevel
): Question[] {
  return getFilteredQuestions({ subject, gradeLevel });
}

/**
 * Get available topics for a subject and grade
 */
export function getTopicsForSubjectAndGrade(
  subject: Subject,
  gradeLevel: GradeLevel
): string[] {
  const questions = getQuestionsBySubjectAndGrade(subject, gradeLevel);
  const topics = new Set(questions.map((q) => q.topic));
  return Array.from(topics);
}

/**
 * Get question stats
 */
export function getQuestionStats(): {
  total: number;
  bySubject: Record<Subject, number>;
  byGrade: Record<GradeLevel, number>;
  byDifficulty: Record<Difficulty, number>;
  byType: Record<QuestionType, number>;
} {
  const stats = {
    total: QUESTIONS.length,
    bySubject: {} as Record<Subject, number>,
    byGrade: {} as Record<GradeLevel, number>,
    byDifficulty: {} as Record<Difficulty, number>,
    byType: {} as Record<QuestionType, number>,
  };

  for (const q of QUESTIONS) {
    stats.bySubject[q.subject] = (stats.bySubject[q.subject] || 0) + 1;
    stats.byGrade[q.gradeLevel] = (stats.byGrade[q.gradeLevel] || 0) + 1;
    stats.byDifficulty[q.difficulty] = (stats.byDifficulty[q.difficulty] || 0) + 1;
    stats.byType[q.type] = (stats.byType[q.type] || 0) + 1;
  }

  return stats;
}

/**
 * Validate an answer against the correct answer
 */
export function validateAnswer(
  question: Question,
  userAnswer: string | string[]
): boolean {
  if (Array.isArray(question.correctAnswer)) {
    if (!Array.isArray(userAnswer)) return false;
    return (
      question.correctAnswer.length === userAnswer.length &&
      question.correctAnswer.every((a) => userAnswer.includes(a))
    );
  }
  return question.correctAnswer === userAnswer;
}
